<?php
/* @var $this SponsorsController */
/* @var $model Sponsors */
/* @var $form CActiveForm */
	$cs = Yii::app()->getClientScript();
   $cs->registerScriptFile( Yii::app()->baseUrl. '/protected/views/sponsors/js/script.js');
?>
<script>
     function changeSector(){
     	var sectorValue = $("#sector option:selected").val();

     	if(sectorValue =="ACTIVIDADES DEL GOBIERNO Y DE ORGANISMOS INTERNACIONALES Y EXTRATERRITORIALES"){
    		var ActividadesDelGoviernoIternacionalesExtraterritoriales = [
    							"ACTIVIDADES ADMINISTRATIVAS ESTATALES DE INSTITUCIONES DE BIENESTAR SOCIAL",
								"ACTIVIDADES ADMINISTRATIVAS FEDERALES DE INSTITUCIONES DE BIENESTAR SOCIAL",
								"ACTIVIDADES ADMINISTRATIVAS MUNICIPALES DE INSTITUCIONES DE BIENESTAR SOCIAL",
								"ACTIVIDADES DE SEGURIDAD NACIONAL",
								"ADMINISTRACION PUBLICA ESTATAL EN GENERAL",
								"ADMINISTRACION PUBLICA FEDERAL EN GENERAL",
								"ADMINISTRACION PUBLICA MUNICIPAL EN GENERAL",
								"IMPARTICION DE JUSTICIA Y MANTENIMIENTO DE LA SEGURIDAD Y EL ORDEN PUBLICO EN EL NIVEL ESTATAL",
								"IMPARTICION DE JUSTICIA Y MANTENIMIENTO DE LA SEGURIDAD Y EL ORDEN PUBLICO EN EL NIVEL FEDERAL",
								"IMPARTICION DE JUSTICIA Y MANTENIMIENTO DE LA SEGURIDAD Y EL ORDEN PUBLICO EN EL NIVEL MUNICIPAL",
								"ORGANISMOS INTERNACIONALES",
								"ORGANOS LEGISLATIVOS",
								"REGULACION Y FOMENTO ESTATAL DE ACTIVIDADES PARA MEJORAR Y PRESERVAR EL MEDIO AMBIENTE",
								"REGULACION Y FOMENTO ESTATAL DEL DESARROLLO ECONOMICO",
								"REGULACION Y FOMENTO FEDERAL DE ACTIVIDADES PARA MEJORAR Y PRESERVAR EL MEDIO AMBIENTE",
								"REGULACION Y FOMENTO FEDERAL DEL DESARROLLO ECONOMICO",
								"REGULACION Y FOMENTO MUNICIPAL DE ACTIVIDADES PARA MEJORAR Y PRESERVAR EL MEDIO AMBIENTE",
								"REGULACION Y FOMENTO MUNICIPAL DEL DESARROLLO ECONOMICO",
								"RELACIONES EXTERIORES",
								"SEDES DIPLOMATICAS Y OTRAS UNIDADES EXTRATERRITORIALES"]
    	sectorValue = ActividadesDelGoviernoIternacionalesExtraterritoriales;
   }
      	if(sectorValue =="AGRICULTURA GANADERIA APROVECHAMIENTO FORESTAL PESCA Y CAZA"){
    		var agriculturaGanaderaForestalPescayCaza = [
    							"ACUICULTURA ANIMAL EXCEPTO CAMARONICULTURA",
								"APICULTURA",
								"BENEFICIO DE PRODUCTOS AGRICOLAS",
								"CAMARONICULTURA",
								"CAZA Y CAPTURA",
								"CULTIVO ANUAL DE OTRAS SEMILLAS OLEAGINOSAS",
								"CULTIVO DE AGAVE ALCOHOLERO",
								"CULTIVO DE AGUACATE",
								"CULTIVO DE ALFALFA",
								"CULTIVO DE ALGODON",
								"CULTIVO DE ARBOLES DE CICLO PRODUCTIVO DE 10 ANOS O MENOS",
								"CULTIVO DE ARROZ",
								"CULTIVO DE AVENA FORRAJERA",
								"CULTIVO DE AVENA GRANO",
								"CULTIVO DE CACAHUATE",
								"CULTIVO DE CACAO",
								"CULTIVO DE CAFE",
								"CULTIVO DE CALABACITA",
								"CULTIVO DE CANA DE AZUCAR",
								"CULTIVO DE CARTAMO",
								"CULTIVO DE CEBADA GRANO",
								"CULTIVO DE CEBOLLA",
								"CULTIVO DE CHILE",
								"CULTIVO DE COCO",
								"CULTIVO DE FRIJOL GRANO",
								"CULTIVO DE GARBANZO GRANO",
								"CULTIVO DE GIRASOL",
								"CULTIVO DE JITOMATE O TOMATE ROJO",
								"CULTIVO DE LIMON",
								"CULTIVO DE MAIZ FORRAJERO",
								"CULTIVO DE MAIZ GRANO",
								"CULTIVO DE MANGO",
								"CULTIVO DE MANZANA",
								"CULTIVO DE MELON O SANDIA",
								"CULTIVO DE NARANJA",
								"CULTIVO DE OTRAS HORTALIZAS Y SEMILLAS DE HORTALIZAS",
								"CULTIVO DE OTRAS LEGUMBRES",
								"CULTIVO DE OTROS CEREALES",
								"CULTIVO DE OTROS CITRICOS",
								"CULTIVO DE OTROS FRUTALES NO CITRICOS Y DE NUECES",
								"CULTIVO DE PAPA",
								"CULTIVO DE PASTOS Y ZACATES",
								"CULTIVO DE PLATANO",
								"CULTIVO DE PRODUCTOS ALIMENTICIOS EN INVERNADEROS",
								"CULTIVO DE SORGO FORRAJERO",
								"CULTIVO DE SORGO GRANO",
								"CULTIVO DE SOYA",
								"CULTIVO DE TABACO",
								"CULTIVO DE TOMATE VERDE",
								"CULTIVO DE TRIGO",
								"CULTIVO DE UVA",
								"CUNICULTURA Y EXPLOTACION DE ANIMALES DE PIEL CON PELAJE FINO",
								"DESPEPITE DE ALGODON",
								"EXPLOTACION CONJUNTA DE OVINOS CON CAPRINOS",
								"EXPLOTACION DE BOVINOS PARA CARNE",
								"EXPLOTACION DE BOVINOS PARA LECHE",
								"EXPLOTACION DE BOVINOS SIN ESPECIALIZACION",
								"EXPLOTACION DE CAPRINOS",
								"EXPLOTACION DE EQUIDOS",
								"EXPLOTACION DE GALLINAS PONEDORAS DE HUEVO FERTIL",
								"EXPLOTACION DE GALLINAS PONEDORAS DE HUEVO PARA PLATO",
								"EXPLOTACION DE GUAJOLOTES O PAVOS",
								"EXPLOTACION DE OTRAS AVES PRODUCTORAS DE CARNE Y HUEVO",
								"EXPLOTACION DE OTROS ANIMALES",
								"EXPLOTACION DE OVINOS",
								"EXPLOTACION DE POLLOS PARA CARNE",
								"EXPLOTACION DE PORCINOS EN GRANJA",
								"EXPLOTACION DE PORCINOS EN TRASPATIO",
								"FLORICULTURA A CIELO ABIERTO",
								"FLORICULTURA EN INVERNADERO",
								"OTROS CULTIVOS EN INVERNADEROS Y VIVEROS",
								"OTROS CULTIVOS",
								"OTROS SERVICIOS RELACIONADOS CON LA AGRICULTURA",
								"PESCA DE CAMARON",
								"PESCA DE OTRAS ESPECIES",
								"PESCA DE SARDINA Y ANCHOVETA",
								"PESCA DE TUNIDOS",
								"PRODUCCION DE AVES DE CORRAL EN INCUBADORA",
								"RECOLECCION DE PRODUCTOS FORESTALES",
								"SERVICIOS DE FUMIGACION AGRICOLA",
								"SERVICIOS RELACIONADOS CON EL APROVECHAMIENTO FORESTAL",
								"SERVICIOS RELACIONADOS CON LA GANADERIA",
								"SILVICULTURA",
								"TALA DE ARBOLES",
								"VIVEROS FORESTALES"]
    	sectorValue = agriculturaGanaderaForestalPescayCaza;
   }
   if(sectorValue =="COMERCIO AL POR MAYOR"){
    		var comercionAlPorMayor = [
    									"COMERCIO AL PO R MAYOR DE CAMIONES",
										"COMERCIO AL POR MAYOR DE ABARROTES",
										"COMERCIO AL POR MAYOR DE ARTICULOS DE JOYERIA Y OTROS ACCESORIOS DE VESTIR",
										"COMERCIO AL POR MAYOR DE ARTICULOS DE PAPELERIA",
										"COMERCIO AL POR MAYOR DE ARTICULOS DE PERFUMERIA",
										"COMERCIO AL POR MAYOR DE ARTICULOS Y ACCESORIOS PARA DISEÑO Y PINTURA ARTISTICA",
										"COMERCIO AL POR MAYOR DE ARTICULOS Y APARATOS DEPORTIVOS",
										"COMERCIO AL POR MAYOR DE BLANCOS",
										"COMERCIO AL POR MAYOR DE BOTANAS Y FRITURAS",
										"COMERCIO AL POR MAYOR DE CALZADO",
										"COMERCIO AL POR MAYOR DE CARNE DE AVES",
										"COMERCIO AL POR MAYOR DE CARNES ROJAS",
										"COMERCIO AL POR MAYOR DE CEMENTO TABIQUE Y GRAVA",
										"COMERCIO AL POR MAYOR DE CERVEZA",
										"COMERCIO AL POR MAYOR DE CIGARROS PUROS Y TABACO",
										"COMERCIO AL POR MAYOR DE CONSERVAS ALIMENTICIAS",
										"COMERCIO AL POR MAYOR DE DESECHOS DE PAPEL Y DE CARTON",
										"COMERCIO AL POR MAYOR DE DESECHOS DE PLASTICO",
										"COMERCIO AL POR MAYOR DE DESECHOS DE VIDRIO",
										"COMERCIO AL POR MAYOR DE DESECHOS METALICOS",
										"COMERCIO AL POR MAYOR DE DISCOS Y CASETES",
										"COMERCIO AL POR MAYOR DE DULCES Y MATERIAS PRIMAS PARA REPOSTERIA",
										"COMERCIO AL POR MAYOR DE ELECTRODOMESTICOS MENORES Y APARATOS DE LINEA BLANCA",
										"COMERCIO AL POR MAYOR DE EMBUTIDOS",
										"COMERCIO AL POR MAYOR DE ENVASES PAPEL Y CARTON",
										"COMERCIO AL POR MAYOR DE EQUIPO DE TELECOMUNICACIONES FOTOGRAFIA Y CINEMATOGRAFIA",
										"COMERCIO AL POR MAYOR DE EQUIPO Y ACCESORIOS DE COMPUTO",
										"COMERCIO AL POR MAYOR DE EQUIPO Y MATERIAL ELECTRICO",
										"COMERCIO AL POR MAYOR DE FERTILIZANTES PLAGUICIDAS Y SEMILLAS PARA SIEMBRA",
										"COMERCIO AL POR MAYOR DE FIBRAS HILOS Y TELAS",
										"COMERCIO AL POR MAYOR DE FRUTAS Y VERDURAS FRESCAS",
										"COMERCIO AL POR MAYOR DE GANADO Y AVES DE CORRAL EN PIE",
										"COMERCIO AL POR MAYOR DE HUEVO",
										"COMERCIO AL POR MAYOR DE JUGUETES",
										"COMERCIO AL POR MAYOR DE LECHE Y OTROS PRODUCTOS LACTEOS",
										"COMERCIO AL POR MAYOR DE LIBROS",
										"COMERCIO AL POR MAYOR DE MADERA",
										"COMERCIO AL POR MAYOR DE MAQUINARIA Y EQUIPO AGROPECUARIO FORESTAL Y PARA LA PESCA",
										"COMERCIO AL POR MAYOR DE MAQUINARIA Y EQUIPO PARA LA CONSTRUCCION Y LA MINERIA",
										"COMERCIO AL POR MAYOR DE MAQUINARIA Y EQUIPO PARA LA INDUSTRIA MANUFACTURERA",
										"COMERCIO AL POR MAYOR DE MAQUINARIA Y EQUIPO PARA OTROS SERVICIOS Y PARA ACTIVIDADES COMERCIALES",
										"COMERCIO AL POR MAYOR DE MATERIALES METALICOS",
										"COMERCIO AL POR MAYOR DE MEDICAMENTOS VETERINARIOS Y ALIMENTOS PARA ANIMALES",
										"COMERCIO AL POR MAYOR DE MOBILIARIO EQUIPO E INSTRUMENTAL MEDICO Y DE LABORATORIO",
										"COMERCIO AL POR MAYOR DE MOBILIARIO Y EQUIPO DE OFICINA",
										"COMERCIO AL POR MAYOR DE OTRA MAQUINARIA Y EQUIPO DE USO GENERAL",
										"COMERCIO AL POR MAYOR DE OTRAS MATERIAS PRIMAS PARA OTRAS INDUSTRIAS",
										"COMERCIO AL POR MAYOR DE OTROS ALIMENTOS",
										"COMERCIO AL POR MAYOR DE OTROS MATERIALES DE DESECHO",
										"COMERCIO AL POR MAYOR DE OTROS MATERIALES PARA LA CONSTRUCCION EXCEPTO DE MADERA",
										"COMERCIO AL POR MAYOR DE OTROS PRODUCTOS TEXTILES",
										"COMERCIO AL POR MAYOR DE PAN Y PASTELES",
										"COMERCIO AL POR MAYOR DE PESCADOS Y MARISCOS",
										"COMERCIO AL POR MAYOR DE PINTURA",
										"COMERCIO AL POR MAYOR DE PRODUCTOS FARMACEUTICOS",
										"COMERCIO AL POR MAYOR DE PRODUCTOS QUIMICOS PARA USO INDUSTRIAL",
										"COMERCIO AL POR MAYOR DE REFRESCOS AGUA PURIFICADA Y HIELO",
										"COMERCIO AL POR MAYOR DE REVISTAS Y PERIODICOS",
										"COMERCIO AL POR MAYOR DE ROPA",
										"COMERCIO AL POR MAYOR DE SEMILLAS Y GRANOS ALIMENTICIOS ESPECIAS Y CHILES SECOS",
										"COMERCIO AL POR MAYOR DE VIDRIOS Y ESPEJOS",
										"COMERCIO AL POR MAYOR DE VINOS Y LICORES",
										"COMERCIO AL POR MAYOR POR MEDIOS MASIVOS DE COMUNICACION Y OTROS MEDIOS",
										"OTROS INTERMEDIARIOS DE COMERCIO AL POR MAYOR",
										"VENTA AL POR MAYOR POR COMISION Y CONSIGNACION"]
    	sectorValue = comercionAlPorMayor;
   }
      if(sectorValue =="COMERCIO AL POR MENOR"){
    		var comercionAlPorMenor = [
    											"COMERCIO AL POR MENOR DE OTROS ARTICULOS DE USO PERSONAL",
												"COMERCIO AL PO R MENOR DE MOTOCICLETAS",
												"COMERCIO AL POR ME NOR DE GASOLINA Y DIESEL",
												"COMERCIO AL POR MENOR DE ACCESORIOS DE VESTIR",
												"COMERCIO AL POR MENOR DE ACEITES Y GRASAS LUBRICANTES ADITIVOS Y SIMILARES",
												"COMERCIO AL POR MENOR DE ALFOMBRAS CORTINAS TAPICES Y SIMILARES",
												"COMERCIO AL POR MENOR DE ANTIGÜEDADES Y OBRAS DE ARTE",
												"COMERCIO AL POR MENOR DE APARATOS ORTOPEDICOS",
												"COMERCIO AL POR MENOR DE ARTESANIAS",
												"COMERCIO AL POR MENOR DE ARTICULOS DE JOYERIA Y RELOJES",
												"COMERCIO AL POR MENOR DE ARTICULOS DE MERCERIA Y BONETERIA",
												"COMERCIO AL POR MENOR DE ARTICULOS DE PAPELERIA",
												"COMERCIO AL POR MENOR DE ARTICULOS DE PERFUMERIA Y COSMETICOS",
												"COMERCIO AL POR MENOR DE ARTICULOS PARA LA LIMPIEZA",
												"COMERCIO AL POR MENOR DE ARTICULOS RELIGIOSOS",
												"COMERCIO AL POR MENOR DE ARTICULOS USADOS",
												"COMERCIO AL POR MENOR DE ARTICULOS Y APARATOS DEPORTIVOS",
												"COMERCIO AL POR MENOR DE AUTOMOVILES Y CAMIONETAS NUEVOS",
												"COMERCIO AL POR MENOR DE AUTOMOVILES Y CAMIONETAS USADOS",
												"COMERCIO AL POR MENOR DE BLANCOS",
												"COMERCIO AL POR MENOR DE CALZADO",
												"COMERCIO AL POR MENOR DE CARNE DE AVES",
												"COMERCIO AL POR MENOR DE CARNES ROJAS",
												"COMERCIO AL POR MENOR DE CERVEZA",
												"COMERCIO AL POR MENOR DE CIGARROS PUROS Y TABACO",
												"COMERCIO AL POR MENOR DE COMPUTADORAS Y SUS ACCESORIOS",
												"COMERCIO AL POR MENOR DE CRISTALERIA LOZA Y UTENSILIOS DE COCINA",
												"COMERCIO AL POR MENOR DE DISCOS Y CASETES",
												"COMERCIO AL POR MENOR DE DULCES Y MATERIAS PRIMAS PARA REPOSTERIA",
												"COMERCIO AL POR MENOR DE ENSERES ELECTRODOMESTICOS MENORES Y APARATOS DE LINEA BLANCA",
												"COMERCIO AL POR MENOR DE EQUIPO Y MATERIAL FOTOGRAFICO",
												"COMERCIO AL POR MENOR DE FRUTAS Y VERDURAS FRESCAS",
												"COMERCIO AL POR MENOR DE GAS EN CILINDROS Y PARA TANQUES ESTACIONARIOS",
												"COMERCIO AL POR MENOR DE INSTRUMENTOS MUSICALES",
												"COMERCIO AL POR MENOR DE JUGUETES Y BICICLETAS",
												"COMERCIO AL POR MENOR DE LAMPARAS ORNAMENTALES Y CANDILES",
												"COMERCIO AL POR MENOR DE LECHE PROCESADA OTROS PRODUCTOS LACTEOS Y EMBUTIDOS",
												"COMERCIO AL POR MENOR DE LENTES",
												"COMERCIO AL POR MENOR DE LIBROS",
												"COMERCIO AL POR MENOR DE LLANTAS Y CAMARAS PARA AUTOMOVILES CAMIONETAS Y CAMIONES",
												"COMERCIO AL POR MENOR DE MASCOTAS",
												"COMERCIO AL POR MENOR DE MATERIALES PARA LA AUTOCONSTRUCCION",
												"COMERCIO AL POR MENOR DE MUEBLES PARA EL HOGAR",
												"COMERCIO AL POR MENOR DE OTROS ALIMENTOS",
												"COMERCIO AL POR MENOR DE OTROS ARTICULOS PARA LA DECORACION DE INTERIORES",
												"COMERCIO AL POR MENOR DE OTROS COMBUSTIBLES",
												"COMERCIO AL POR MENOR DE OTROS VEHICULOS DE MOTOR",
												"COMERCIO AL POR MENOR DE PARTES Y REFACCIONES NUEVAS PARA AUTOMOVILES CAMIONETAS Y CAMIONES",
												"COMERCIO AL POR MENOR DE PARTES Y REFACCIONES USADAS PARA AUTOMOVILES CAMIONETAS Y CAMIONES",
												"COMERCIO AL POR MENOR DE PAÑALES DESECHABLES",
												"COMERCIO AL POR MENOR DE PERIODICOS Y REVISTAS",
												"COMERCIO AL POR MENOR DE PESCADOS Y MARISCOS",
												"COMERCIO AL POR MENOR DE PINTURA",
												"COMERCIO AL POR MENOR DE PLANTAS Y FLORES NATURALES",
												"COMERCIO AL POR MENOR DE PRODUCTOS NATURISTAS Y DE COMPLEMENTO S ALIMENTICIOS",
												"COMERCIO AL POR MENOR DE REFRESCOS AGUA PURIFICADA Y HIELO",
												"COMERCIO AL POR MENOR DE REGALOS",
												"COMERCIO AL POR MENOR DE ROPA DE CUERO Y PIEL Y DE OTROS ARTICULOS DE ESTOS MATERIALES",
												"COMERCIO AL POR MENOR DE ROPA EXCEPTO DE CUERO Y PIEL",
												"COMERCIO AL POR MENOR DE SEMILLAS Y GRANOS ALIMENTICIOS ESPECIAS Y CHILES SECOS",
												"COMERCIO AL POR MENOR DE SOMBREROS",
												"COMERCIO AL POR MENOR DE TELAS",
												"COMERCIO AL POR MENOR DE TELEFONOS Y OTROS APARATOS DE COMUNICACION",
												"COMERCIO AL POR MENOR DE VIDRIOS Y ESPEJOS",
												"COMERCIO AL POR MENOR DE VINOS Y LICORES",
												"COMERCIO AL POR MENOR EN FERRETERIAS Y TLAPALERIAS",
												"COMERCIO AL POR MENOR EN MINISUPERS",
												"COMERCIO AL POR MENOR EN SUPERMERCADOS",
												"COMERCIO AL POR MENOR EN TIENDAS DE ABARROTES ULTRAMARINOS Y MISCELANEAS",
												"COMERCIO AL POR MENOR EN TIENDAS DEPARTAMENTALES",
												"COMERCIO AL POR MENOR EN TIENDAS IMPORTADORAS",
												"COMERCIO AL POR MENOR POR MEDIOS MASIVOS DE COMUNICACION Y OTROS MEDICAMENTOS",
												"FARMACIAS CON MINISUPER",
												"FARMACIAS SIN MINISUPER",
												"OTROS INTERMEDIARIOS DE COMERCIO AL POR MENOR",
												"VENTA AL POR MENOR POR COMISION Y CONSIGNACION",]
    	sectorValue = comercionAlPorMenor;
   }
     if(sectorValue =="CONSTRUCCION"){
    		var construccion = [
    	"ADMINISTRACION Y SUPERVISION DE CONSTRUCCION DE OBRAS DE GENERACION Y CONDUCCION DE ENERGIA ELECTRICA Y",
		"ADMINISTRACION Y SUPERVISION DE CONSTRUCCION DE OBRAS PARA EL TRATAMIENTO DISTRIBUCION Y SUMINISTRO DE",
		"ADMINISTRACION Y SUPERVISION DE CONSTRUCCION DE OBRAS PARA PETROLEO Y GAS",
		"ADMINISTRACION Y SUPERVISION DE CONSTRUCCION DE OTRAS OBRAS DE INGENIERIA CIVIL U OBRA PESADA",
		"ADMINISTRACION Y SUPERVISION DE CONSTRUCCION DE VIAS DE COMUNICACION",
		"ADMINISTRACION Y SUPERVISION DE DIVISION DE TERRENOS Y DE CONSTRUCCION DE OBRAS DE URBANIZACION",
		"ADMINISTRACION Y SUPERVISION DE EDIFICACION DE INMUEBLES COMERCIALES INSTITUCIONALES Y DE SERVICIOS",
		"ADMINISTRACION Y SUPERVISION DE EDIFICACION DE NAVES Y PLANTAS INDUSTRIALES",
		"ADMINISTRACION Y SUPERVISION DE EDIFICACION RESIDENCIAL",
		"COLOCACION DE MUROS FALSOS Y AISLAMIENTO",
		"COLOCACION DE PISOS CERAMICOS Y AZULEJOS",
		"COLOCACION DE PISOS FLEXIBLES Y DE MADERA",
		"CONSTRUCCION DE CARRETERAS PUENTES Y SIMILARES",
		"CONSTRUCCION DE OBRAS DE GENERACION Y CONDUCCION DE ENERGIA ELECTRICA",
		"CONSTRUCCION DE OBRAS DE URBANIZACION",
		"CONSTRUCCION DE OBRAS MARITIMAS FLUVIALES Y SUBACUATICAS",
		"CONSTRUCCION DE OBRAS PARA EL TRATAMIENTO DISTRIBUCION Y SUMINISTRO DE AGUA Y DRENAJE",
		"CONSTRUCCION DE OBRAS PARA TELECOMUNICACIONES",
		"CONSTRUCCION DE OBRAS PARA TRANSPORTE ELECTRICO Y FERROVIARIO",
		"CONSTRUCCION DE PLANTAS DE REFINERIA Y PETROQUIMICA",
		"CONSTRUCCION DE PRESAS Y REPRESAS",
		"CONSTRUCCION DE SISTEMAS DE DISTRIBUCION DE PETROLEO Y GAS",
		"CONSTRUCCION DE SISTEMAS DE RIEGO AGRICOLA",
		"DIVISION DE TERRENOS",
		"EDIFICACION DE INMUEBLES COMERCIALES INSTITUCIONALES Y DE SERVICIOS EXCEPTO SU ADMINISTRACION Y SUPERV",
		"EDIFICACION DE NAVES Y PLANTAS INDUSTRIALES EXCEPTO SU ADMINISTRACION Y SUPERVISION",
		"EDIFICACION DE VIVIENDA MULTIFAMILIAR",
		"EDIFICACION DE VIVIENDA UNIFAMILIAR",
		"INSTALACION DE PRODUCTOS DE CARPINTERIA",
		"INSTALACION DE SEÑALAMIENTOS Y PROTECCIONES DE OBRAS VIALES",
		"INSTALACIONES DE AIRE ACONDICIONADO Y CALEFACCION",
		"INSTALACIONES ELECTRICAS EN CONSTRUCCIONES",
		"INSTALACIONES HIDROSANITARIAS Y DE GAS",
		"MONTAJE DE ESTRUCTURAS DE ACERO PREFABRICADAS",
		"MONTAJE DE ESTRUCTURAS DE CONCRETO PREFABRICADAS",
		"PREPARACION DE TERRENOS PARA LA CONSTRUCCION",
		"TRABAJOS DE ALBAÑILERIA",
		"TRABAJOS DE CIMENTACIONES",
		"TRABAJOS DE ENYESADO EMPASTADO Y TIROLEADO",
		"TRABAJOS DE PINTURA Y OTROS CUBRIMIENTOS DE PAREDES",
		"OTRAS CONSTRUCCIONES DE INGENIERIA CIVIL U OBRA PESADA",
		"OTRAS INSTALACIONES Y EQUIPAMIENTO EN CONSTRUCCIONES",
		"OTROS TRABAJOS DE ACABADOS EN EDIFICACIONES",
		"OTROS TRABAJOS EN EXTERIORES",
		"OTROS TRABAJOS ESPECIALIZADOS PARA LA CONSTRUCCION"]
    	sectorValue = construccion;
   }
   if(sectorValue =="DIRECCION DE CORPORATIVOS Y EMPRESAS"){
    		var direccionDeCorporativosyEmpresas = [
    	"DIRECCION DE CORPORATIVOS Y EMPRESAS FINANCIERAS",
		"DIRECCION DE CORPORATIVOS Y EMPRESAS NO FINANCIERAS"]
    	sectorValue = direccionDeCorporativosyEmpresas;
   }
    if(sectorValue =="ELECTRICIDAD AGUA Y SUMINISTRO DE GAS POR DUCTOS AL CONSUMIDOR FINAL"){
    		var electricidadAguaySuministroDeGasPorDuctosAlConsumidorFinal = [
    	"CAPTACION TRATAMIENTO Y SUMINISTRO DE AGUA REALIZADOS POR EL SECTOR PRIVADO",
		"CAPTACION TRATAMIENTO Y SUMINISTRO DE AGUA REALIZADOS POR EL SECTOR PUBLICO",
		"DE GAS POR DUCTOS AL CONSUMIDOR FINAL",
		"GENERACION Y TRANSMISION DE ENERGIA ELECTRICA",
		"SUMINISTRO DE ENERGIA ELECTRICA"]
    	sectorValue = electricidadAguaySuministroDeGasPorDuctosAlConsumidorFinal;
   }
    if(sectorValue =="INDUSTRIA MANUFACTURERA ALIMENTARIA, TABACO, BEBIDAS Y FABRICACIÓN DE TEXTILES"){
    		var indistruiaManufacturaAlimentariaTabacoBebidasyFabricacionDeTextiles = [
    		"ACABADO DE FIBRAS HILADOS HILOS Y TELAS",
			"BENEFICIO DEL ARROZ",
			"BENEFICIO DEL CAFE",
			"BENEFICIO DEL TABACO",
			"CONFECCION DE CORTINAS BLANCOS Y SIMILARES",
			"CONFECCION DE COSTALES",
			"CONFECCION DE OTRA ROPA DE MATERIALES TEXTILES",
			"CONFECCION DE OTROS ACCESORIOS DE VESTIR",
			"CONFECCION DE PRODUCTOS BORDADOS Y DESHILADOS",
			"CONFECCION DE PRODUCTOS DE TEXTILES RECUBIERTOS Y DE MATERIALES SUCEDANEOS",
			"CONFECCION DE ROPA DE CUERO PIEL Y MATERIALES SUCEDANEOS",
			"CONFECCION DE ROPA SOBRE MEDIDA",
			"CONFECCION EN SERIE DE CAMISAS",
			"CONFECCION EN SERIE DE ROPA ESPECIAL",
			"CONFECCION EN SERIE DE ROPA INTERIOR Y DE DORMIR",
			"CONFECCION EN SERIE DE UNIFORMES",
			"CONGELACION DE FRUTAS Y VERDURAS",
			"CONGELACION DE GUISOS",
			"CONSERVACION DE FRUTAS Y VERDURAS POR PROCESOS DISTINTOS A LA CONGELACION Y LA DESHIDRATACION",
			"CONSERVACION DE GUISOS POR PROCESOS DISTINTOS A LA CONGELACION",
			"CORTE Y EMPACADO DE CARNE DE GANADO Y AVES",
			"CURTIDO Y ACABADO DE CUERO Y PIEL",
			"DESHIDRATACION DE FRUTAS Y VERDURAS",
			"ELABORACION DE ACEITES Y GRASAS VEGETALES COMESTIBLES",
			"ELABORACION DE AGUAMIEL Y PULQUE",
			"ELABORACION DE ALIMENTOS FRESCOS PARA CONSUMO INMEDIATO",
			"ELABORACION DE ALIMENTOS PARA ANIMALES",
			"ELABORACION DE AZUCAR DE CAÑA",
			"ELABORACION DE BEBIDAS ALCOHOLICAS A BASE DE UVA",
			"ELABORACION DE BEBIDAS DESTILADAS DE AGAVE",
			"ELABORACION DE BOTANAS",
			"ELABORACION DE CAFE SOLUBLE",
			"ELABORACION DE CEREALES PARA EL DESAYUNO",
			"ELABORACION DE CERVEZA",
			"ELABORACION DE CHOCOLATE Y PRODUCTOS DE CHOCOLATE A PARTIR DE CACAO",
			"ELABORACION DE CIGARROSEEUU",
			"ELABORACION DE CONCENTRADOS POLVOS JARABES Y ESCENCIAS DE SABRO PARA REFRESCO",
			"ELABORACION DE CONDIMENTOS Y ADEREZOS",
			"ELABORACION DE DERIVADOS Y FERMENTOS LACTEOS",
			"ELABORACION DE DULCES CHICLES Y PRODUCTOS DE CONFITERIA QUE NO SEAN DE CHOCOLATE",
			"ELABORACION DE FECULAS Y OTROS ALMIDONES",
			"ELABORACION DE GALLETAS Y PASTAS PARA SOPA",
			"ELABORACION DE HARINA DE MAIZ",
			"ELABORACION DE HARINA DE OTROS PRODUCTOS AGRICOLAS",
			"ELABORACION DE HARINA DE TRIGO",
			"ELABORACION DE HELADOS Y PALETAS",
			"ELABORACION DE HIELO EEUU",
			"ELABORACION DE LECHE EN POLVO CONDENSADA Y EVAPORADA",
			"ELABORACION DE LEVADURA",
			"ELABORACION DE MALTA",
			"ELABORACION DE MANTECA Y OTRAS GRASAS ANIMALES COMESTIBLES",
			"ELABORACION DE OTRAS BEBIDAS DESTILADAS",
			"ELABORACION DE OTROS ALIMENTOS",
			"ELABORACION DE OTROS AZUCARES",
			"ELABORACION DE POSTRES EN POLVO",
			"ELABORACION DE PRODUCTOS DE CHOCOLATE A PARTIR DE CHOCOLATE",
			"ELABORACION DE PUROS Y OTROS PRODUCTOS DE TABACO",
			"ELABORACION DE REFRESCOSEEUU",
			"ELABORACION DE RON Y OTRAS BEBIDAS DESTILADAS DE CAÑA",
			"ELABORACION DE SIDRA Y OTRAS BEBIDAS FERMENTADAS",
			"ELABORACION DE TORTILLAS DE MAIZ Y MOLIENDA DE NIXTAMAL",
			"FABRICACION DE ARTICULOS DE TALABARTERIA",
			"FABRICACION DE BANDERAS Y OTROS PRODUCTOS CONFECCIONADOS",
			"FABRICACION DE BOLSOS DE MANO MALETAS Y SIMILARES",
			"FABRICACION DE CALZADO CON CORTE DE PIEL Y CUERO",
			"FABRICACION DE CALZADO CON CORTE DE TELA",
			"FABRICACION DE CALZADO DE HULE",
			"FABRICACION DE CALZADO DE PLASTICO",
			"FABRICACION DE HILOS PARA COSER Y BORDAREEUU",
			"FABRICACION DE HUARACHES Y CALZADO DE OTRO TIPO DE MATERIALES",
			"FABRICACION DE PRODUCTOS TEXTILES RECICLADOS",
			"FABRICACION DE REDES Y OTROS PRODUCTOS DE CORDELERIA",
			"FABRICACION DE SOMBREROS Y GORRASEEUU",
			"FABRICACION DE TELAS ANCHAS DE TRAMA",
			"FABRICACION DE TELAS ANGOSTAS DE TRAMA Y PASAMANERIA",
			"FABRICACION DE TELAS DE PUNTO",
			"FABRICACION DE TELAS NO TEJIDAS",
			"MATANZA DE GANADO Y AVES",
			"OBTENCION DE ALCOHOL ETILICO POTABLE",
			"PANIFICACION INDUSTRIAL",
			"PANIFICACION TRADICIONAL",
			"PREPARACION DE EMBUTIDOS Y OTRAS CONSERVAS DE CARNE DE GANADO Y AVES",
			"PREPARACION E HILADO DE FIBRAS BLANDAS",
			"PREPARACION E HILADO DE FIBRAS DURAS NATURALES",
			"PREPARACION Y ENVASADO DE PESCADOS Y MARISCOS",
			"PREPARACION Y ENVASADO DE TE",
			"PURIFICACION DE AGUAEEUU",
			"RECUBRIMIENTO DE TELAS",
			"TEJIDO DE CALCETINES Y MEDIASCAN",
			"TEJIDO DE ROPA EXTERIOR DE PUNTO",
			"TEJIDO DE ROPA INTERIOR DE PUNTO",
			"TEJIDO Y CONFECCION DE ALFOMBRAS Y TAPETES",
			"TOSTADO Y MOLIENDA DE CAFE",
			"TRATAMIENTO Y ENVASADO DE LECHE LIQUIDA"]
    	sectorValue = indistruiaManufacturaAlimentariaTabacoBebidasyFabricacionDeTextiles;
   }
   if(sectorValue =="INDUSTRIA MANUFACTURERA DE MADERA, PAPEL, DERIVADOS DEL PETRÓLEO E INDUSTRIA QUÍMICA"){
    		var indistruiaManufacturaDeMaderaPapelDerivadosDelPetroleeIndustriaQuimica = [
    			"ASERRADEROS INTEGRADOSCAN",
				"ASERRADO DE TABLAS Y TABLONESCAN",
				"CORTE PULIDO Y LAMINADO DE MARMOL",
				"CORTE Y PULIDO DE PIEDRAS DE CANTERA EXCEPTO MARMOL",
				"FABRICAC ION DE LLANTAS Y CAMARAS",
				"FABRICACION DE ACEITES Y GRASAS LUBRICANTES",
				"FABRICACION DE ADHESIVOS Y SELLADORES",
				"FABRICACION DE ARTICULOS DE ALFARERIA PORCELANA Y LOZA",
				"FABRICACION DE ARTICULOS DE PLASTICO PARA EL HOGAR",
				"FABRICACION DE ARTICULOS DE VIDRIO DE USO DOMESTICO",
				"FABRICACION DE ARTICULOS DE VIDRIO DE USO INDUSTRIAL Y COMERCIAL",
				"FABRICACION DE ARTICULOS Y UTENSILIOS DE MADERA PARA EL HOGAR",
				"FABRICACION DE AUTOPARTES DE PLASTICO",
				"FABRICACION DE AZULEJOS Y LOSETAS NO REFRACTARIAS",
				"FABRICACION DE BANDAS Y MANGUERAS DE HULE Y DE PLASTICO",
				"FABRICACION DE BOLSAS DE PAPEL Y PRODUCTOS CELULOSICOS RECUBIERTOS Y TRATADOS",
				"FABRICACION DE BOLSAS Y PELICULAS DE PLASTICO FLEXIBLE SIN SOPORTE",
				"FABRICACION DE BOTELLAS DE PLASTICO",
				"FABRICACION DE CAL",
				"FABRICACION DE CARTON EN PLANTAS INTEGRADAS",
				"FABRICACION DE CARTON Y CARTONCILLO A PARTIR DE CELULOSA",
				"FABRICACION DE CELULOSA",
				"FABRICACION DE CEMENTO PARA LA CONSTRUCCION",
				"FABRICACION DE CERILLOS",
				"FABRICACION DE CONCRETO",
				"FABRICACION DE COQUE Y OTROS PRODUCTOS DERIVADOS DEL PETROLEO Y DEL CARBON",
				"FABRICACION DE COSMETICOS PERFUMES Y OTRAS PREPARACIONES DE TOCADOR",
				"FABRICACION DE ENVASES DE CARTON",
				"FABRICACION DE ENVASES Y AMPOLLETAS DE VIDRIO",
				"FABRICACION DE ENVASES Y CONTENEDORES DE PLASTICO",
				"FABRICACION DE ESPEJOS",
				"FABRICACION DE ESPUMAS Y PRODUCTOS DE POLIESTIRENO",
				"FABRICACION DE ESPUMAS Y PRODUCTOS DE URETANO",
				"FABRICACION DE EXPLOSIVOS",
				"FABRICACION DE FERTILIZANTES",
				"FABRICACION DE FIBRA DE VIDRIO",
				"FABRICACION DE FIBRAS QUIMICAS",
				"FABRICACION DE GASES INDUSTRIALES",
				"FABRICACION DE HULES SINTETICOS",
				"FABRICACION DE JABONES LIMPIADORES Y DENTIFRICOS",
				"FABRICACION DE LADRILLOS NO REFRACTARIOS",
				"FABRICACION DE LAMINADOS RIGIDOS DE PLASTICO SIN SOPORTE",
				"FABRICACION DE LAMINADOS Y AGLUTINADOS DE MADERA",
				"FABRICACION DE MATERIAS PRIMAS PARA LA INDUSTRIA FARMACEUTICA",
				"FABRICACION DE MUEBLES DE BAÑO",
				"FABRICACION DE OTROS ARTICULOS DE PLASTICO DE USO INDUSTRIAL SIN REFORZAMIENTO",
				"FABRICACION DE OTROS ARTICULOS DE PLASTICO REFORZADO",
				"FABRICACION DE OTROS PRODUCTOS A BASE DE MINERALES NO METALICOS",
				"FABRICACION DE OTROS PRODUCTOS DE CEMENTO Y CONCRETO",
				"FABRICACION DE OTROS PRODUCTOS DE HULE",
				"FABRICACION DE OTROS PRODUCTOS DE MADERA",
				"FABRICACION DE OTROS PRODUCTOS DE PAPEL Y CARTON",
				"FABRICACION DE OTROS PRODUCTOS DE PLASTICO",
				"FABRICACION DE OTROS PRODUCTOS DE VIDRIO",
				"FABRICACION DE OTROS PRODUCTOS QUIMICOS BASICOS INORGANICOS",
				"FABRICACION DE OTROS PRODUCTOS QUIMICOS BASICOS ORGANICOS",
				"FABRICACION DE OTROS PRODUCTOS QUIMICOS",
				"FABRICACION DE PAPEL A PARTIR DE CELULOSA",
				"FABRICACION DE PAPEL EN PLANTAS INTEGRADAS",
				"FABRICACION DE PAÑALES DESECHABLES Y PRODUCTOS SANITARIOS",
				"FABRICACION DE PELICULAS PLACAS Y PAPEL FOTOSENSIBLE PARA FOTOGRAFIA",
				"FABRICACION DE PERFILES TUBERIA Y CONEXIONES DE PLASTICO RIGIDO SIN SOPORTE",
				"FABRICACION DE PESTICIDAS Y AGROQUIMICOS EXCEPTO FERTILIZANTES",
				"FABRICACION DE PIGMENTOS Y COLORANTES SINTETICOS",
				"FABRICACION DE PINTURAS Y RECUBRIMIENTOS",
				"FABRICACION DE PREPARACIONES FARMACEUTICAS",
				"FABRICACION DE PRODUCTOS ABRASIVOS",
				"FABRICACION DE PRODUCTOS DE ASFALTO",
				"FABRICACION DE PRODUCTOS DE MADERA DE USO INDUSTRIAL",
				"FABRICACION DE PRODUCTOS DE MADERA PARA LA CONSTRUCCION",
				"FABRICACION DE PRODUCTOS DE MATERIALES TRENZABLES EXCEPTO PALMA",
				"FABRICACION DE PRODUCTOS DE PAPELERIA",
				"FABRICACION DE PRODUCTOS PARA EMBALAJE Y ENVASES DE MADERA",
				"FABRICACION DE PRODUCTOS PETROQUIMICOS",
				"FABRICACION DE PRODUCTOS PREESFORZADOS",
				"FABRICACION DE PRODUCTOS REFRACTARIOS",
				"FABRICACION DE RESINAS PLASTICAS RECICLADAS",
				"FABRICACION DE RESINAS SINTETICAS",
				"FABRICACION DE TINTAS PARA IMPRESION",
				"FABRICACION DE TUBOS Y BLOQUES DE CEMENTO Y CONCRETO",
				"FABRICACION DE VIDRIO",
				"FABRICACION DE YESO Y PRODUCTOS DE YESO",
				"IMPRESION DE FORMAS CONTINUAS Y OTROS IMPRESOS",
				"IMPRESION DE LIBROS PERIODICOS Y REVISTAS",
				"INDUSTRIAS CONEXAS A LA IMPRESION",
				"REFINACION DE PETROLEO",
				"REVITALIZACION DE LLANTAS",
				"TRATAMIENTO DE LA MADERA Y PRODUCCION DE POSTES Y DURMIENTES"]
    	sectorValue = indistruiaManufacturaDeMaderaPapelDerivadosDelPetroleeIndustriaQuimica;
   }
      if(sectorValue =="INDUSTRIA MANUFACTURERA MAQUINARÍA EQUIPO"){
    		var industriaManufacturaMaquinariaEquipo = [
    				"COMPLEJOS SIDERURGICOS",
					"FABRICACION DE ACUMULADORES Y PILAS",
					"FABRICACION DE ALAMBRE PRODUCTOS DE ALAMBRE Y RESORTES",
					"FABRICACION DE APARATOS DE LINEA BLANCA",
					"FABRICACION DE APARATOS E INSTRUMENTOS PARA PESAR",
					"FABRICACION DE APARATOS FOTOGRAFICOS",
					"FABRICACION DE APARATOS TELEFONICOS",
					"FABRICACION DE ARTICULOS DEPORTIVOS",
					"FABRICACION DE ASIENTOS PARA VEHICULOS AUTOMOTORES",
					"FABRICACION DE AUTOMOVILES Y CAMIONETAS",
					"FABRICACION DE BALEROS Y RODAMIENTOS",
					"FABRICACION DE BICICLETAS Y TRICICLOS",
					"FABRICACION DE BOMBAS",
					"FABRICACION DE CABLES DE CONDUCCION ELECTRICA",
					"FABRICACION DE CALDERAS INDUSTRIALES",
					"FABRICACION DE CAMIONES Y TRACTOCAMIONES",
					"FABRICACION DE CARROCERIAS Y REMOLQUES",
					"FABRICACION DE COCINAS",
					"FABRICACION DE COLCHONES",
					"FABRICACION DE COMPONENTES ELECTRONICOS",
					"FABRICACION DE COMPUTADORAS Y EQUIPO PERIFERICO",
					"FABRICACION DE DESBASTES PRIMARIOS Y FERROALEACIONES",
					"FABRICACION DE EMBARCACIONES",
					"FABRICACION DE ENCHUFES CONTACTOS FUSIBLES Y OTROS ACCESORIOS PARA INSTALACIONES ELECTRICAS",
					"FABRICACION DE ENSERES ELECTRODOMESTICOS MENORES",
					"FABRICACION DE ENVASES METALICOS DE CALIBRE LIGERO",
					"FABRICACION DE EQUIPO AEROESPACIAL",
					"FABRICACION DE EQUIPO DE AUDIO Y DE VIDEO",
					"FABRICACION DE EQUIPO DE TRANSMISION Y RECEPCION DE SEÑALES DE RADIO TELEVISION Y CABLE",
					"FABRICACION DE EQUIPO ELECTRICO Y ELECTRONICO PARA VEHICULOS AUTOMOTORES",
					"FABRICACION DE EQUIPO FERROVIARIO",
					"FABRICACION DE EQUIPO PARA SOLDAR Y SOLDADURAS",
					"FABRICACION DE EQUIPO Y APARATOS DE DISTRIBUCION DE ENERGIA ELECTRICA",
					"FABRICACION DE EQUIPO Y APARATOS PARA USO MEDICO DENTAL Y PARA LABORATORIO",
					"FABRICACION DE ESTRUCTURAS METALICAS",
					"FABRICACION DE FOCOS",
					"FABRICACION DE HERRAJES Y CERRADURAS",
					"FABRICACION DE HERRAMIENTAS DE MANO METALICAS SIN MOTOR",
					"FABRICACION DE INSTRUMENTOS Y APARATOS OPTICOS DE USO OFTALMICO",
					"FABRICACION DE LAMPARAS ORNAMENTALES",
					"FABRICACION DE MAQUINARIA Y EQUIPO AGRICOLA",
					"FABRICACION DE MAQUINARIA Y EQUIPO PARA ENVASAR Y EMPACAR",
					"FABRICACION DE MAQUINARIA Y EQUIPO PARA LA CONSTRUCCION",
					"FABRICACION DE MAQUINARIA Y EQUIPO PARA LA IMPRESI¢N",
					"FABRICACION DE MAQUINARIA Y EQUIPO PARA LA INDUSTRIA ALIMENTARIA Y DE LAS BEBIDAS",
					"FABRICACION DE MAQUINARIA Y EQUIPO PARA LA INDUSTRIA DE LA MADERA",
					"FABRICACION DE MAQUINARIA Y EQUIPO PARA LA INDUSTRIA DEL HULE Y DEL PLASTICO",
					"FABRICACION DE MAQUINARIA Y EQUIPO PARA LA INDUSTRIA DEL VIDRIO Y OTROS MINERALES NO METALICOS",
					"FABRICACION DE MAQUINARIA Y EQUIPO PARA LA INDUSTRIA EXTRACTIVA",
					"FABRICACION DE MAQUINARIA Y EQUIPO PARA LA INDUSTRIA TEXTIL",
					"FABRICACION DE MAQUINARIA Y EQUIPO PARA LEVANTAR Y TRASLADAR",
					"FABRICACION DE MAQUINARIA Y EQUIPO PARA OTRAS INDUSTRIAS MANUFACTURERAS",
					"FABRICACION DE MAQUINARIA Y EQUIPO PECUARIO",
					"FABRICACION DE MAQUINAS FOTOCOPIADORAS",
					"FABRICACION DE MATERIAL DE CURACION",
					"FABRICACION DE MOTOCICLETAS",
					"FABRICACION DE MOTORES DE COMBUSTION INTERNA TURBINAS Y TRANSMISIONES",
					"FABRICACION DE MOTORES DE GASOLINA Y SUS PARTES PARA VEHICULOS AUTOMOTRICES",
					"FABRICACION DE MOTORES Y GENERADORES ELECTRICOS",
					"FABRICACION DE MUEBLES DE OFICINA Y ESTANTERIA",
					"FABRICACION DE MUEBLES EXCEPTO COCINAS Y MUEBLES DE OFICINA Y ESTANTERIA",
					"FABRICACION DE OTRA MAQUINARIA Y EQUIPO PARA EL COMERC IO Y LOS SERVICIOS",
					"FABRICACION DE OTRA MAQUINARIA Y EQUIPO PARA LA INDUSTRIA EN GENERAL",
					"FABRICACION DE OTRAS PARTES PARA VEHICULOS AUTOMOTRICES",
					"FABRICACION DE OTRO EQUIPO DE TRANSPORTE",
					"FABRICACION DE OTROS INSTRUMENTOS DE NAVEGACION MEDICION MEDICOS Y DE CONTROL",
					"FABRICACION DE OTROS PRODUCTOS DE HIERRO Y ACERO DE MATERIAL COMPRADO",
					"FABRICACION DE OTROS PRODUCTOS ELECTRICOS",
					"FABRICACION DE OTROS PRODUCTOS METALICOS",
					"FABRICACION DE PARTES DE SISTEMAS DE DIRECCION Y DE SUSPENSION PARA VEHICULOS AUTOMOTRICES",
					"FABRICACION DE PARTES DE SISTEMAS DE FRENOS PARA VEHICULOS AUTOMOTRICES",
					"FABRICACION DE PARTES DE SISTEMAS DE TRANSMISION",
					"FABRICACION DE PERSIANAS Y CORTINEROS",
					"FABRICACION DE PIEZAS METALICAS TROQUELADAS PARA VEHICULOS AUTOMOTRICES",
					"FABRICACION DE PRODUCTOS DE HERRERIA",
					"FABRICACION DE PRODUCTOS ELECTRICOS DE CARBON Y GRAFITO",
					"FABRICACION DE PRODUCTOS METALICOS FORJADOS Y TRO QUELADOS",
					"FABRICACION DE RELOJES",
					"FABRICACION DE SISTEMAS DE AIRE ACONDICIONADO Y CALEFACCION",
					"FABRICACION DE SISTEMAS DE BOMBEO",
					"FABRICACION DE SISTEMAS DE REFRIGERACION INDUSTRIAL Y COMERCIAL",
					"FABRICACION DE TANQUES METALICOS DE CALIBRE GRUESO",
					"FABRICACION DE TORNILLOS TUERCAS REMACHES Y SIMILARES",
					"FABRICACION DE TUBOS Y POSTES DE HIERRO Y ACERO DE MATERIAL COMPRADO",
					"FABRICACION DE UTENSILIOS DE COCINA METALICOS",
					"FABRICACION DE VALVULAS METALICAS",
					"FABRICACION Y REPRODUCCION DE MEDIOS MAGNETICOS Y OPTICOS",
					"INDUSTRIA DEL ALUMINIO",
					"JOYERIA DE METALES Y PIEDRAS NO PRECIOSOS Y DE OTROS MATERIALES",
					"LAMINACION SECUNDARIA DE COBRE",
					"LAMINACION SECUNDARIA DE OTROS METALES NO FERROSOS",
					"MAQUINADO DE PIEZAS METALICAS PARA MAQUINARIA Y EQUIPO EN GENERAL",
					"METALISTERIA DE METALES NO PRECIOSOS",
					"MOLDEO POR FUNDICION DE PIEZAS DE HIERRO Y ACERO",
					"MOLDEO POR FUNDICION DE PIEZAS METALICAS NO FERROSAS",
					"N/A",
					"ORFEBRERIA Y JOYERIA DE METALES Y PIEDRAS PRECIOSOS",
					"RECUBRIMIENTOS Y TERMINADOS METALICOS",
					"REFINACION DE COBRE",
					"REFINACION DE OTROS METALES NO FERROSOS"]
    	sectorValue = industriaManufacturaMaquinariaEquipo;
   }
   if(sectorValue =="INFORMACION EN MEDIOS MASIVOS"){
    		var informacionEnMediosMasivos = [
    					"AGENCIAS NOTICIOSAS",
						"BIBLIOTECAS Y ARCHIVOS DEL SECTOR PRIVADO",
						"BIBLIOTECAS Y ARCHIVOS DEL SECTOR PUBLICO",
						"CREACION Y DIFUSION DE CONTENIDO EXCLUSIVAMENTE A TRAVES DE INTERNET",
						"DISTRIBUCION DE PELIC ULAS CINEMATOGRAFICAS VIDEOS Y OTROS MATERIALES AUDIOVISUALES",
						"DISTRIBUCION POR SUSCRIPCION DE PROGRAMAS DE TELEVISION EXCEPTO A TRAVES DE INTERNET",
						"EDICION DE DIRECTORIOS Y DE LISTAS DE CORREO INTEGRADA CON LA IMPRESION",
						"EDICION DE DIRECTORIOS Y DE LISTAS DE CORREO NO INTEGRADA CON LA IMPRESION EXCEPTO A TRAVES DE INTERNET",
						"EDICION DE LIBROS INTEGRADA CON LA IMPRESION",
						"EDICION DE LIBROS NO INTEGRADA CON LA IMPRESION EXCEPTO A TRAVES DE INTERNET",
						"EDICION DE OTROS MATERIALES INTEGRADA CON LA IMPRESION",
						"EDICION DE OTROS MATERIALES NO INTEGRADA CON LA IMPRESION EXCEPTO A TRAVES DE INTERNET",
						"EDICION DE PERIODICOS INTEGRADA CON LA IMPRESION",
						"EDICION DE PERIODICOS NO INTEGRADA CON LA IMPRESION EXCEPTO A TRAVES DE INTERNET",
						"EDICION DE REVISTAS Y OTRAS PUBLICACIONES PERIODICAS INTEGRADA CON LA IMPRESION",
						"EDICION DE REVISTAS Y OTRAS PUBLICACIONES PERIODICAS NO INTEGRADA CON LA IMPRESION EXCEPTO A TRAVES DE INTERNET",
						"EDICION DE SOFTWARE EXCEPTO A TRAVES DE INTERNET",
						"EDITORAS DE MUSICA",
						"EXHIBICION DE PELICULAS CINEMATOGRAFICAS VIDEOS Y OTROS MATERIALES AUDIOVISUALES",
						"GRABACION DE DISCOS Y CINTAS MAGNETOFONICAS",
						"PROCESAMIENTO ELECTRONICO DE INFORMACION HOSPEDAJE DE PAGINAS WEB Y OTROS SERVICIOS RELACIONADOS",
						"PRODUCCION DE PELICULAS CINEMATOGRAFICAS Y VIDEOS",
						"PRODUCCION DE PROGRAMACION DE CANALES PARA SISTEMAS DE TELEVISION POR CABLE O SATELITALES EXCEPTO A TRAVES DE INTERNET",
						"PRODUCCION DE PROGRAMAS PARA LA TELEVISION",
						"PRODUCCION DE VIDEOCLIPS COMERCIALES Y OTROS MATERIALES AUDIOVISUALES",
						"PRODUCCION Y DISTRIBUCION DE DISCOS Y CINTAS MAGNETOFONICAS",
						"PRODUCTORAS DISCOGRAFICAS",
						"PROVEEDORES DE ACCESO A INTERNET Y SERVICIOS DE BUSQUEDA EN LA RED",
						"REVENTA DE SERVICIOS DE TELECOMUNICACIONES",
						"SERVICIOS DE POSTPRODUCCION Y OTROS SERVICIOS PARA LA INDUSTRIA FILMICA Y DEL VIDEO",
						"SERVICIOS DE SATELITES",
						"TELEFONIA CELULAR",
						"TELEFONIA TRADICIONAL",
						"TELEGRAFIA Y OTRAS TELECOMUNICACIONES ALAMBRICAS",
						"TRANSMISION DE PROGRAMAS DE RADIO EXCEPTO A TRAVES DE INTERNET",
						"TRANSMISION DE PROGRAMAS DE TELEVISION EXCEPTO A TRAVES DE INTERNET",
						"OTRAS TELECOMUNICACIONES INALAMBRICAS EXCEPTO LOS SERVICIOS DE SATELITES",
						"OTROS SERVICIOS DE GRABACION DEL SONIDO",
						"OTROS SERVICIOS DE SUMINISTRO DE INFORMACION",
						"OTROS SERVICIOS DE TELECOMUNICACIONES"]
    	sectorValue = informacionEnMediosMasivos;
   }
      if(sectorValue =="MINERIA"){
    		var mineria = [
    						"EXTRACCION DE PETROLEO Y GAS",
							"MINERIA DE ARENA Y GRAVA PARA LA CONSTRUCCION",
							"MINERIA DE AZUFRE",
							"MINERIA DE BARITA",
							"MINERIA DE CAOLIN",
							"MINERIA DE CARBON MINERAL",
							"MINERIA DE COBRE Y NIQUEL",
							"MINERIA DE FELDESPATO",
							"MINERIA DE FLUORITA",
							"MINERIA DE GRAFITO",
							"MINERIA DE HIERRO",
							"MINERIA DE MANGANESO",
							"MINERIA DE MARMOL",
							"MINERIA DE MERCURIO Y ANTIMONIO",
							"MINERIA DE MINERALES NO METALICOS PARA PRODUCTOS QUIMICOS",
							"MINERIA DE ORO",
							"MINERIA DE OTRAS ARCILLAS Y OTROS MINERALES REFRACTARIOS",
							"MINERIA DE OTRAS PIEDRAS DIMENSIONADAS",
							"MINERIA DE OTROS MINERALES METALICOS",
							"MINERIA DE OTROS MINERALES NO METALICOS",
							"MINERIA DE PIEDRA DE CAL",
							"MINERIA DE PIEDRA DE YESO",
							"MINERIA DE PLATA",
							"MINERIA DE PLOMO Y ZINC",
							"MINERIA DE ROCA FOSFORICA",
							"MINERIA DE SAL",
							"MINERIA DE SILICE",
							"MINERIA DE TEZONTLE Y TEPETATE",
							"MINERIA DE URANIO Y MINERALES RADIACTIVOS",
							"PERFORACION DE POZOS PETROLEROS Y DE GAS",
							"OTROS SERVICIOS RELACIONADOS CON LA MINERIA"]
    	sectorValue = mineria;
   }
     if(sectorValue =="SERVICIOS DE ALOJAMIENTO TEMPORAL Y DE PREPARACION DE ALIMENTOS Y BEBIDAS"){
    		var serviciosDeAlojamientoTemporalyDePreparacionDeAlimentosyBebidas = [
    						"BARES Y CANTINAS",
							"CABAÑAS VILLAS SIMILARES",
							"CAMPAMENTOS Y ALBERGUES RECREATIVOS",
							"CENTROS NOCTURNOS DISCOTECAS Y SIMILARES",
							"CERVECERIAS",
							"DEPARTAMENTOS Y CASAS AMUEBLADOS CON SERVICIOS DE HOTELERIA",
							"HOTELES CON CASINO",
							"HOTELES CON OTROS SERVICIOS INTEGRADOS",
							"HOTELES SIN OTROS SERVICIOS INTEGRADOS",
							"MOTELES",
							"PENSIONES Y CASAS DE HUESPEDES",
							"PULQUERIAS",
							"RESTAURANTES DE AUTOSERVICIO",
							"RESTAURANTES DE COMIDA PARA LLEVAR",
							"RESTAURANTES SIN BAR Y CON SERVICIO DE MESEROS",
							"RESTAURANTES-BAR CON SERVICIO DE MESEROS",
							"SERVICIOS DE COMEDOR PARA EMPRESAS E INSTITUCIONES",
							"SERVICIOS DE PREPARACION DE ALIMENTOS EN UNIDADES MOVILES",
							"SERVICIOS DE PREPARACION DE ALIMENTOS PARA OCASIONES ESPECIALES"]
    	sectorValue = serviciosDeAlojamientoTemporalyDePreparacionDeAlimentosyBebidas;
   }
       if(sectorValue =="SERVICIOS DE APOYO A LOS NEGOCIOS Y MANEJO DE DERECHOS Y SERVICIOS DE REMEDIACION"){
    		var serviciosDeApoyoaLosNegociosyManejoDeDerechosYServiciosDeRemediacion = [
    							"AGENCIAS DE COBRANZA",
								"AGENCIAS DE COLOCACION",
								"AGENCIAS DE EMPLEO TEMPORAL",
								"AGENCIAS DE VIAJES",
								"DESPACHOS DE INVESTIGACION DE SOLVENCIA FINANCIERA",
								"MANEJO DE DESECHOS NO PELIGROSOS Y SERVICIOS DE REMEDIACION A ZONAS DAÑADAS POR DESECHOS NO PELIGROSOS",
								"MANEJO DE DESECHOS PELIGROSOS Y SERVICIOS DE REMEDIACION A ZONAS DAÑADAS POR DESECHOS PELIGROSOS",
								"ORGANIZACION DE EXCURSIONES Y PAQUETES TURISTICOS PARA AGENCIAS DE VIAJES",
								"ORGANIZADORES DE CONVENCIONES Y FERIAS COMERCIALES E INDUSTRIALES",
								"OTROS SERVICIOS DE APOYO A LOS NEGOCIOS",
								"OTROS SERVICIOS DE APOYO SECRETARIAL Y SIMILARES",
								"OTROS SERVICIOS DE LIMPIEZA",
								"OTROS SERVICIOS DE RESERVACIONES",
								"SERVICIOS COMBINADOS DE APOYO EN INSTALACIONES",
								"SERVICIOS DE ADMINISTRACION DE NEGOCIOS",
								"SERVICIOS DE CASETAS TELEFONICAS",
								"SERVICIOS DE CONTROL Y EXTERMINACION DE PLAGAS",
								"SERVICIOS DE EMPACADO Y ETIQUETADO",
								"SERVICIOS DE FOTOCOPIADO FAX Y AFINES",
								"SERVICIOS DE INSTALACION Y MANTENIMIENTO DE AREAS VERDES",
								"SERVICIOS DE INVESTIGACION Y DE PROTECCION Y CUSTODIA EXCEPTO MEDIANTE MONITOREO",
								"SERVICIOS DE LIMPIEZA DE INMUEBLES",
								"SERVICIOS DE LIMPIEZA DE TAPICERIA ALFOMBRAS Y MUEBLES",
								"SERVICIOS DE PREPARACION DE DOCUMENTOS",
								"SERVICIOS DE PROTECCION Y CUSTODIA MEDIANTE EL MONITOREO DE SISTEMAS DE SEGURIDAD",
								"SERVICIOS DE RECEPCION DE LLAMADAS TELEFONICAS Y PROMOCION POR TELEFONO",
								"SUMINISTRO DE PERSONAL PERMANENTE"]
    	sectorValue = serviciosDeApoyoaLosNegociosyManejoDeDerechosYServiciosDeRemediacion;
   }
   if(sectorValue =="SERVICIOS DE ESPARCIMIENTO CULTURALES Y DEPORTIVOS Y OTROS SERVICIOS RECREATIVOS"){
    		var serviciosDeEsparcimientoCulturalesyDeportivos = [
    								"AGENTES Y REPRESENTANTES DE ARTISTAS DEPORTISTAS Y SIMILARES",
									"ARTISTAS Y TECNICOS INDEPENDIENTES",
									"BALNEARIOS DEL SECTOR PRIVADO",
									"BALNEARIOS DEL SECTOR PUBLICO",
									"BILLARES",
									"BOLICHES",
									"CAMPOS DE GOLF",
									"CANTANTES Y GRUPOS MUSICALES DEL SECTOR PRIVADO",
									"CASAS DE JUEGOS ELECTRONICOS",
									"CASINOS",
									"CENTROS DE ACONDICIONAMIENTO FISICO PERTENECIENTES AL SECTOR PRIVADO",
									"CENTROS DE ACONDICIONAMIENTO FISICO PERTENECIENTES AL SECTOR PUBLICO",
									"CLUBES DEPORTIVOS DEL SECTOR PRIVADO",
									"CLUBES DEPORTIVOS DEL SECTOR PUBLICO",
									"COMPAÑIAS DE DANZA DEL SECTOR PRIVADO",
									"COMPAÑIAS DE DANZA DEL SECTOR PUBLICO",
									"COMPAÑIAS DE TEATRO DEL SECTOR PRIVADO",
									"COMPAÑIAS DE TEATRO DEL SECTOR PUBLICO",
									"DEPORTISTAS PROFESIONALES Y SEMIPROFESIONALES",
									"EQUIPOS DEPORTIVOS PROFESIONALES Y SEMIPROFESIONALES",
									"GRUPOS MUSICALES DEL SECTOR PUBLICO",
									"GRUTAS PARQUES NATURALES Y OTROS SITIOS DEL PATRIMONIO NACIONAL",
									"JARDINES BOTANICOS Y ZOOLOGICOS DEL SECTOR PRIVADO",
									"JARDINES BOTANICOS Y ZOOLOGICOS DEL SECTOR PUBLICO",
									"MARINAS TURISTICAS",
									"MUSEOS DEL SECTOR PRIVADO",
									"MUSEOS DEL SECTOR PUBLICO",
									"PARQUES DEL SECTOR PRIVADO CON INSTALACIONES RECREATIVAS",
									"PARQUES DEL SECTOR PUBLICO CON INSTALACIONES RECREATIVAS",
									"PISTAS PARA ESQUIAR",
									"PROMOTORES DE ESPECTACULOS ARTISTICOS DEPORTIVOS Y SIMILARES QUE NO CUENTAN CON INSTALACIONES PARA PRES",
									"PROMOTORES DEL SECTOR PRIVADO CON INSTALACIONES PARA LA PRESENTACION DE ESPECTACULOS ARTISTICOS DEPORTI",
									"PROMOTORES DEL SECTOR PUBLICO CON INSTALACIONES PARA LA PRESENTACION DE ESPECTACULOS ARTISTICOS DEPORTI",
									"SITIOS HISTORICOS",
									"VENTA DE BILLETES DE LOTERIA",
									"OTRAS COMPAÑIAS Y GRUPOS DE ESPECTACULOS ARTISTICOS DEL SECTOR PRIVADO",
									"OTRAS COMPAÑIAS Y GRUPOS DE ESPECTACULOS ARTISTICOS DEL SECTOR PUBLICO",
									"OTROS JUEGOS DE AZAR",
									"OTROS SERVICIOS RECREATIVOS PRESTADOS POR EL SECTOR PRIVADO",
									"OTROS SERVICIOS RECREATIVOS PRESTADOS POR EL SECTOR PUBLICO"]
    	sectorValue = serviciosDeEsparcimientoCulturalesyDeportivos;
   }
        if(sectorValue =="SERVICIOS DE SALUD Y DE ASISTENCIA SOCIAL"){
    		var serviciosDeSaludyDeAsistenciaSocial = [
    								"ASILOS Y OTRAS RESIDENCIAS DEL SECTOR PRIVADO PARA EL CUIDADO DE ANCIANOS Y DISCAPACITADOS",
									"ASILOS Y OTRAS RESIDENCIAS DEL SECTOR PUBLICO PARA EL CUIDADO DE ANCIANOS Y DISCAPACITADOS",
									"ASISTENCIA SOCIAL DE AYUDA MUTUA",
									"CENTROS DE PLANIFICACION FAMILIAR PERTENECIENTES AL SECTOR PRIVADO",
									"CENTROS DE PLANIFICACION FAMILIAR PERTENECIENTES AL SECTOR PUBLICO",
									"CENTROS DEL SECTOR PRIVADO DEDICADOS A LA ATENCION MEDICA EXTERNA DE ENFERMOS MENTALES Y ADICTOS",
									"CENTROS DEL SECTOR PRIVADO DEDICADOS A LA ATENCION Y CUIDADO DIURNO DE ANCIANOS Y DISCAPACITADOS",
									"CENTROS DEL SECTOR PUBLICO DEDICADOS A LA ATENCION MEDICA EXTERNA DE ENFERMOS MENTALES Y ADICTOS",
									"CENTROS DEL SECTOR PUBLICO DEDICADOS A LA ATENCION Y CUIDADO DIURNO DE ANCIANOS Y DISCAPACITADOS",
									"CONSULTORIOS DE AUDIOLOGIA Y DE TERAPIA OCUPACIONAL FISICA Y DEL LENGUAJE PERTENECIENTES AL SECTOR PRIV",
									"CONSULTORIOS DE AUDIOLOGIA Y DE TERAPIA OCUPACIONAL FISICA Y DEL LENGUAJE PERTENECIENTES AL SECTOR PUBL",
									"CONSULTORIOS DE MEDICINA ESPECIALIZADA PERTENECIENTES AL SECTOR PRIVADO",
									"CONSULTORIOS DE MEDICINA ESPECIALIZADA PERTENECIENTES AL SECTOR PUBLICO",
									"CONSULTORIOS DE MEDICINA GENERAL PERTENECIENTES AL SECTOR PRIVADO",
									"CONSULTORIOS DE MEDICINA GENERAL PERTENECIENTES AL SECTOR PUBLICO",
									"CONSULTORIOS DE OPTOMETRIA",
									"CONSULTORIOS DE PSICOLOGIA PERTENECIENTES AL SECTOR PRIVADO",
									"CONSULTORIOS DE PSICOLOGIA PERTENECIENTES AL SECTOR PUBLICO",
									"CONSULTORIOS DE QUIRO PRACTICA PERTENECIENTES AL SECTOR PRIVADO",
									"CONSULTORIOS DE QUIROPRACTICA PERTENECIENTES AL SECTOR PUBLICO",
									"CONSULTORIOS DEL SECTOR PRIVADO DE NUTRIOLOGOS Y DIETISTAS",
									"CONSULTORIOS DEL SECTOR PUBLICO DE NUTRIOLOGOS Y DIETISTAS",
									"CONSULTORIOS DENTALES DEL SECTOR PRIVADO",
									"CONSULTORIOS DENTALES DEL SECTOR PUBLICO",
									"GUARDERIAS DEL SECTOR PRIVADO",
									"GUARDERIAS DEL SECTOR PUBLICO",
									"HOSPITALES DEL SECTOR PRIVADO DEDICADOS A OTRAS ESPECIALIDADES MEDICAS",
									"HOSPITALES DEL SECTOR PRIVADO PSIQUIATRICOS Y PARA EL TRATAMIENTO POR ABUSO DE SUBSTANCIAS",
									"HOSPITALES DEL SECTOR PUBLICO DEDICADOS A OTRAS ESPECIALIDADES MEDICAS",
									"HOSPITALES DEL SECTOR PUBLICO PSIQUIATRICOS Y PARA EL TRATAMIENTO POR ABUSO DE SUBSTANCIAS",
									"HOSPITALES GENERALES DEL SECTOR PRIVADO",
									"HOSPITALES GENERALES DEL SECTOR PUBLICO",
									"LABORATORIOS MEDICOS Y DE DIAGNOSTICO PERTENECIENTES AL SECTOR PRIVADO",
									"LABORATORIOS MEDICOS Y DE DIAGNOSTICO PERTENECIENTES AL SECTOR PUBLICO",
									"ORFANATOS Y OTRAS RESIDENCIAS DE ASISTENCIA SOCIAL PERTENECIENTES AL SECTOR PRIVADO",
									"ORFANATOS Y OTRAS RESIDENCIAS DE ASISTENCIA SOCIAL PERTENECIENTES AL SECTOR PUBLICO",
									"REFUGIOS TEMPORALES COMUNITARIOS PERTENECIENTES AL SECTOR PRIVADO",
									"REFUGIOS TEMPORALES COMUNITARIOS PERTENECIENTES AL SECTOR PUBLICO",
									"RESIDENCIAS DEL SECTOR PRIVADO CON CUIDADOS DE ENFERMERAS PARA ENFERMOS CONVALECIENTES EN REHABILITACIO",
									"RESIDENCIAS DEL SECTOR PRIVADO PARA EL CUIDADO DE PERSONAS CON PROBLEMAS DE RETARDO MENTAL",
									"RESIDENCIAS DEL SECTOR PRIVADO PARA EL CUIDADO DE PERSONAS CON PROBLEMAS DE SALUD MENTAL Y ABUSO DE SUBS",
									"RESIDENCIAS DEL SECTOR PUBLICO CON CUIDADOS DE ENFERMERAS PARA ENFERMOS CONVALECIENTES EN REHABILITACIO",
									"RESIDENCIAS DEL SECTOR PUBLICO PARA EL CUIDADO DE PERSONAS CON PROBLEMAS DE RETARDO MENTAL",
									"RESIDENCIAS DEL SECTOR PUBLICO PARA EL CUIDADO DE PERSONAS CON PROBLEMAS DE SALUD MENTAL Y ABUSO DE SUBS",
									"SERVICIOS DE ALIMENTACION COMUNITARIOS PRESTADOS POR EL SECTOR PRIVADO",
									"SERVICIOS DE ALIMENTACION COMUNITARIOS PRESTADOS POR EL SECTOR PUBLICO",
									"SERVICIOS DE AMBULANCIAS",
									"SERVICIOS DE BANCOS DE ORGANOS DE BANCOS DE SANGRE Y OTROS SERVICIOS AUXILIARES AL TRATAMIENTO MEDICO P",
									"SERVICIOS DE BANCOS DE ORGANOS DE BANCOS DE SANGRE Y OTROS SERVICIOS AUXILIARES AL TRATAMIENTO MEDICO P",
									"SERVICIOS DE CAPACITACION PARA EL TRABAJO PRESTADOS POR EL SECTOR PRIVADO A PERSONAS DESEMPLEADAS SUBEM",
									"SERVICIOS DE CAPACITACION PARA EL TRABAJO PRESTADOS POR EL SECTOR PUBLICO A PERSONAS DESEMPLEADAS SUBEM",
									"SERVICIOS DE EMERGENCIA COMUNITARIOS PRESTADOS POR EL SECTOR PRIVADO",
									"SERVICIOS DE EMERGENCIA COMUNITARIOS PRESTADOS POR EL SECTOR PUBLICO",
									"SERVICIOS DE ENFERMERIA A DOMICILIO",
									"SERVICIOS DE ORIENTACION Y TRABAJO SOCIAL PARA LA NIÑEZ Y LA JUVENTUD PRESTADOS POR EL SECTOR PRIVADO",
									"SERVICIOS DE ORIENTACION Y TRABAJO SOCIAL PARA LA NIÑEZ Y LA JUVENTUD PRESTADOS POR EL SECTOR PUBLICO",
									"OTROS CENTROS DEL SECTOR PRIVADO PARA LA ATENCION DE PACIENTES QUE NO REQUIEREN HOSPITALIZACION",
									"OTROS CENTROS DEL SECTOR PUBLICO PARA LA ATENCION DE PACIENTES QUE NO REQUIEREN HOSPITALIZACION",
									"OTROS CONSULTORIOS DEL SECTOR PRIVADO PARA EL CUIDADO DE LA SALUD",
									"OTROS CONSULTORIOS DEL SECTOR PUBLICO PARA EL CUIDADO DE LA SALUD",
									"OTROS SERVICIOS DE ORIENTACION Y TRABAJO SOCIAL PRESTADOS POR EL SECTOR PRIVADO",
									"OTROS SERVICIOS DE ORIENTACION Y TRABAJO SOCIAL PRESTADOS POR EL SECTOR PUBLICO"]
    	sectorValue = serviciosDeSaludyDeAsistenciaSocial;
   }

        if(sectorValue =="SERVICIOS EDUCATIVOS"){
    		var serviciosEducativos = [
    									"ESCUELAS DEL SECTOR PUBLICO DEDICADAS A LA ENSEÑANZA DE IDIOMAS",
										"ESCUELAS COMERCIALES Y SECRETARIALES DEL SECTOR PRIVADO",
										"ESCUELAS COMERCIALES Y SECRETARIALES DEL SECTOR PUBLICO",
										"ESCUELAS DE ARTE PERTENECIENTES AL SECTOR PRIVADO",
										"ESCUELAS DE ARTE PERTENECIENTES AL SECTOR PUBLICO",
										"ESCUELAS DE COMPUTACION PERTENECIENTES AL SECTOR PRIVADO",
										"ESCUELAS DE COMPUTACION PERTENECIENTES AL SECTOR PUBLICO",
										"ESCUELAS DE DEPORTE PERTENECIENTES AL SECTOR PRIVADO",
										"ESCUELAS DE DEPORTE PERTENECIENTES AL SECTOR PUBLICO",
										"ESCUELAS DE EDUCACION ESPECIAL PERTENECIENTES AL SECTOR PRIVADO",
										"ESCUELAS DE EDUCACION ESPECIAL PERTENECIENTES AL SECTOR PUBLICO",
										"ESCUELAS DE EDUCACION MEDIA SUPERIOR PERTENECIENTES AL SECTOR PRIVADO",
										"ESCUELAS DE EDUCACION MEDIA SUPERIOR PERTENECIENTES AL SECTOR PUBLICO",
										"ESCUELAS DE EDUCACION MEDIA TECNICA TERMINAL PERTENECIENTES AL SECTOR PRIVADO",
										"ESCUELAS DE EDUCACION MEDIA TECNICA TERMINAL PERTENECIENTES AL SECTOR PUBLICO",
										"ESCUELAS DE EDUCACION POSTBACHILLERATO NO UNIVERSITARIA PERTENECIENTES AL SECTOR PRIVADO",
										"ESCUELAS DE EDUCACION POSTBACHILLERATO NO UNIVERSITARIA PERTENECIENTES AL SECTOR PUBLICO",
										"ESCUELAS DE EDUCACION PREESCOLAR PERTENECIENTES AL SECTOR PRIVADO",
										"ESCUELAS DE EDUCACION PREESCOLAR PERTENECIENTES AL SECTOR PUBLICO",
										"ESCUELAS DE EDUCACION PRIMARIA PERTENECIENTES AL SECTOR PRIVADO",
										"ESCUELAS DE EDUCACION PRIMARIA PERTENECIENTES AL SECTOR PUBLICO",
										"ESCUELAS DE EDUCACION SECUNDARIA GENERAL PERTENECIENTES AL SECTOR PRIVADO",
										"ESCUELAS DE EDUCACION SECUNDARIA GENERAL PERTENECIENTES AL SECTOR PUBLICO",
										"ESCUELAS DE EDUCACION SECUNDARIA TECNICA PERTENECIENTES AL SECTOR PRIVADO",
										"ESCUELAS DE EDUCACION SECUNDARIA TECNICA PERTENECIENTES AL SECTOR PUBLICO",
										"ESCUELAS DE EDUCACION SUPERIOR PERTENECIENTES AL SECTOR PRIVADO",
										"ESCUELAS DE EDUCACION SUPERIOR PERTENECIENTES AL SECTOR PUBLICO",
										"ESCUELAS DEL SECTOR PRIVADO DEDICADAS A LA ENSEÑANZA DE IDIOMAS",
										"ESCUELAS DEL SECTOR PRIVADO DEDICADAS A LA ENSEÑANZA DE OFICIOS",
										"ESCUELAS DEL SECTOR PRIVADO PARA LA CAPACITACION DE EJECUTIVOS",
										"ESCUELAS DEL SECTOR PRIVADO QUE COMBINAN DIVERSOS NIVELES DE EDUCACION",
										"ESCUELAS DEL SECTOR PUBLICO DEDICADAS A LA ENSEÑANZA DE OFICIOS",
										"ESCUELAS DEL SECTOR PUBLICO PARA LA CAPACITACION DE EJECUTIVOS",
										"ESCUELAS DEL SECTOR PUBLICO QUE COMBINAN DIVERSOS NIVELES DE EDUCACION",
										"SERVICIOS DE APOYO A LA EDUCACION",
										"SERVICIOS DE PROFESORES PARTICULARES",
										"OTROS SERVICIOS EDUCATIVOS PROPORCIONADOS POR EL SECTOR PRIVADO",
										"OTROS SERVICIOS EDUCATIVOS PROPORCIONADOS POR EL SECTOR PUBLICO"]
    	sectorValue = serviciosEducativos;
   }
           if(sectorValue =="SERVICIOS FINANCIEROS Y DE SEGUROS"){
    		var segurosFinancierosyDeSeguros = [
    			"ADMINISTRACION DE CAJAS DE PENSION Y DE SEGUROS INDEPENDIENTES",
				"AGENTES AJUSTADORES Y GESTORES DE SEGUROS Y FIANZAS",
				"ARRENDADORAS FINANCIERAS",
				"ASESORIA EN INVERSIONES",
				"BANCA CENTRAL",
				"BANCA DE DESARROLLO",
				"BANCA MULTIPLE",
				"BOLSA DE VALORES",
				"CAJAS DE AHORRO POPULAR",
				"CAJAS DE AHORRO POPULAR",
				"CASAS DE BOLSA",
				"CASAS DE CAMBIO",
				"CENTROS CAMBIARIOS",
				"COMPANIAS AFIANZADORAS",
				"COMPANIAS DE AUTOFINANCIAMIENTO",
				"COMPANIAS DE SEGUROS NO ESPECIALIZADAS EN SEGUROS DE VIDA",
				"COMPANIAS ESPECIALIZADAS EN SEGUROS DE VIDA",
				"COMPAÑIAS DE FACTORAJE FINANCIERO",
				"FONDOS DE ASEGURAMIENTO CAMPESINO",
				"FONDOS Y FIDEICOMISOS FINANCIEROS PARA EL DESARROLLO",
				"MONTEPIOS",
				"ONDOS DE ASEGURAMIENTO CAMPESINO",
				"SERVICIOS RELACIONADOS CON LA INTERMEDIACION CREDITICIA",
				"SOCIEDADES DE INVERSION",
				"SOCIEDADES FINANCIERAS DE OBJETO LIMITADO",
				"UNIONES DE CREDITO",
				"OTRAS INSTITUCIONES DE AHORRO Y PRESTAMO",
				"OTRAS INSTITUCIONES DE INTERMEDIACION CREDITICIA Y FINANCIERA NO BURSATIL",
				"OTROS SERVICIOS RELACIONADOS CON LA INTERMEDIACION BURSATIL"]
    	sectorValue = segurosFinancierosyDeSeguros;
   }
     if(sectorValue =="SERVICIOS INMOBILIARIOS Y DE ALQUILER DE BIENES MUEBLES E INTANGIBLES"){
    		var serviciosInmobiliariosyDeAlquilerDeBienes = [
    				"ALQUILER DE APARATOS ELECTRICOS Y ELECTRONICOS PARA EL HOGAR",
					"ALQUILER DE AUTOBUSES MINIBUSES Y REMOLQUES SIN CHOFER",
					"ALQUILER DE AUTOMOVILES SIN CHOFER",
					"ALQUILER DE CAMIONES DE CARGA SIN CHOFER",
					"ALQUILER DE EQUIPO DE COMPUTO Y DE OTRAS MAQUINAS Y MOBILIARIO DE OFICINA",
					"ALQUILER DE EQUIPO DE TRANSPORTE EXCEPTO TERRESTRE",
					"ALQUILER DE EQUIPO PARA EL COMERCIO Y LOS SERVICIOS",
					"ALQUILER DE EQUIPO PARA LEVANTAR MOVER Y ACOMODAR MATERIALES",
					"ALQUILER DE INSTRUMENTOS MUSICALES",
					"ALQUILER DE MAQUINARIA PARA CONSTRUCCION MINERIA Y ACTIVIDADES FORESTALES",
					"ALQUILER DE MAQUINARIA Y EQUIPO AGROPECUARIO PESQUERO Y PARA LA INDUSTRIA DE LA TRANSFORMACION",
					"ALQUILER DE MESAS SILLAS VAJILLAS Y SIMILARES",
					"ALQUILER DE OTROS ARTICULOS PARA EL HOGAR",
					"ALQUILER DE ROPA",
					"ALQUILER DE VIDEOCASETES Y DISCOS",
					"ALQUILER SIN INTERMEDIACION DE OFICINAS Y LOCALES COMERCIALES",
					"ALQUILER SIN INTERMEDIACION DE OTROS INMUEBLES",
					"ALQUILER SIN INTERMEDIACION DE SALONES PARA FIESTAS Y CONVENCIONES",
					"ALQUILER SIN INTERMEDIACION DE TEATROS ESTADIOS AUDITORIOS Y SIMILARES",
					"ALQUILER SIN INTERMEDIACION DE VIVIENDAS AMUEBLADAS",
					"ALQUILER SIN INTERMEDIACION DE VIVIENDAS NO AMUEBLADAS",
					"CENTROS GENERALES DE ALQUILER",
					"INMOBILIARIAS Y CORREDORES DE BIENES RAICES",
					"SERVICIOS DE ADMINISTRACION DE INMUEBLES",
					"SERVICIOS DE ALQUILER DE MARCAS REGISTRADAS PATENTES Y FRANQUICIAS",
					"OTROS SERVICIOS RELACIONADOS CON LOS SERVICIOS INMOBILIARIOS"]
    	sectorValue = serviciosInmobiliariosyDeAlquilerDeBienes;
   }
   if(sectorValue =="SERVICIOS POSTALES, MENSAJERÍA, PAQUETERÍA Y ALMACENAMIENTO"){
    		var serviciosPostalesMensajeriaPaqueteriayAlmacenamiento = [
    				"ALMACENAMIENTO CON REFRIGERACION",
					"ALMACENAMIENTO DE PRODUCTOS AGROPECUARIOS QUE NO REQUIEREN REFRIGERACION",
					"ALMACENES GENERALES DE DEPOSITO",
					"SERVICIOS DE MENSAJERIA Y PAQUETERIA FORANEA",
					"SERVICIOS DE MENSAJERIA Y PAQUETERIA LOCAL",
					"SERVICIOS POSTALES",
					"OTROS SERVICIOS DE ALMACENAMIENTO CON INSTALACIONES ESPECIALIZADAS",
					"OTROS SERVICIOS DE ALMACENAMIENTO GENERAL SIN INSTALACIONES ESPECIALIZADAS"]
    	sectorValue = serviciosPostalesMensajeriaPaqueteriayAlmacenamiento;
   }
     if(sectorValue =="SERVICIOS PROFESIONALES CIENTIFICOS Y TECNICOS"){
    		var serviciosProfesionalesCientificosyTecnicos = [
    					"AGENCIAS DE ANUNCIOS PUBLICITARIOS",
						"AGENCIAS DE COMPRA DE MEDIOS A PETICION DEL CLIENTE",
						"AGENCIAS DE PUBLICIDAD QUE OPERAN POR CORREO DIRECTO",
						"AGENCIAS DE PUBLICIDAD",
						"AGENCIAS DE RELACIONES PUBLICAS",
						"AGENCIAS DE REPRESENTACION DE MEDIOS",
						"BUFETES JURIDICOS",
						"DISENO DE MODAS Y OTROS DISEÑOS ESPECIALIZADOS",
						"DISENO GRAFICO",
						"DISENO INDUSTRIAL",
						"DISENO Y DECORACION DE INTERIORES",
						"DISTRIBUCION DE MATERIAL PUBLICITARIO",
						"LABORATORIOS DE PRUEBAS",
						"NOTARIAS PUBLICAS",
						"SERVICIOS DE APOYO PARA EFECTUAR TRAMITES LEGALESCAN",
						"SERVICIOS DE ARQUITECTURA DE PAISAJE Y URBANISMO",
						"SERVICIOS DE ARQUITECTURA",
						"SERVICIOS DE CONSULTORIA EN ADMINISTRACION",
						"SERVICIOS DE CONSULTORIA EN COMPUTACION",
						"SERVICIOS DE CONSULTORIA EN MEDIO AMBIENTE",
						"SERVICIOS DE CONTABILIDAD Y AUDITORIA",
						"SERVICIOS DE DIBUJO",
						"SERVICIOS DE ELABORACION DE MAPAS",
						"SERVICIOS DE FOTOGRAFIA",
						"SERVICIOS DE INGENIERIA",
						"SERVICIOS DE INSPECCION DE EDIFICIOS",
						"SERVICIOS DE INVESTIGACION DE MERCADOS Y ENCUESTAS DE OPINION PUBLICA",
						"SERVICIOS DE INVESTIGACION Y DESARROLLO EN CIENCIAS FISICAS DE LA VIDA E INGENIERIA PRESTADOS POR EL SE",
						"SERVICIOS DE INVESTIGACION Y DESARROLLO EN CIENCIAS FISICAS DE LA VIDA E INGENIERIA PRESTADOS POR EL SE",
						"SERVICIOS DE INVESTIGACION Y DESARROLLO EN CIENCIAS SOCIALES Y HUMANIDADES PRESTADOS POR EL SECTOR PRIVA",
						"SERVICIOS DE INVESTIGACION Y DESARROLLO EN CIENCIAS SOCIALES Y HUMANIDADES PRESTADOS POR EL SECTOR PUBLI",
						"SERVICIOS DE LEVANTAMIENTO GEOFISICO",
						"SERVICIOS DE TRADUCCION E INTERPRETACION",
						"SERVICIOS VETERINARIOS PARA LA GANADERIA PRESTADOS POR EL SECTOR PRIVADO",
						"SERVICIOS VETERINARIOS PARA LA GANADERIA PRESTADOS POR EL SECTOR PUBLICO",
						"SERVICIOS VETERINARIOS PARA MASCOTAS PRESTADOS POR EL SECTOR PRIVADO",
						"SERVICIOS VETERINARIOS PARA MASCOTAS PRESTADOS POR EL SECTOR PUBLICO",
						"OTROS SERVICIOS DE CONSULTORIA CIENTIFICA Y TECNICA",
						"OTROS SERVICIOS DE PUBLICIDAD",
						"OTROS SERVICIOS PROFESIONALES CIENTIFICOS Y TECNICOS",
						"OTROS SERVICIOS RELACIONADOS CON LA CONTABILIDAD"]
    	sectorValue = serviciosProfesionalesCientificosyTecnicos;
   }
        if(sectorValue =="TRANSPORTES CORREOS Y ALMACENAMIENTO"){
    		var trasnportesCorreosyAlmacenamiento = [
    						   	"ADMINISTRACION DE AEROPUERTOS Y HELIPUERTOS",
							   	"ADMINISTRACION DE PUERTOS Y MUELLES",
							   	"ALQUILER DE AUTOBUSES CON CHOFER",
							   	"ALQUILER DE AUTOMOVILES CON CHOFER",
							   	"AUTO TRANSPORTE LOCAL DE MADERA Y SUS DERIVADOS",
							   	"AUTOTRANSPORTE FORA NEO DE PRODUCTOS AGROPECUARIOS SIN REFRIGERACION",
							   	"AUTOTRANSPORTE FORANEO CON REFRIGERACION",
							   	"AUTOTRANSPORTE FORANEO DE MADERA Y SUS DERIVADOS",
							   	"AUTOTRANSPORTE FORANEO DE MATERIALES PARA LA CONSTRUCCION",
							   	"AUTOTRANSPORTE FORANEO DE MATERIALES Y RESIDUOS PELIGROSOS",
							   	"AUTOTRANSPORTE LOCAL CON REFRIGERACION",
							   	"AUTOTRANSPORTE LOCAL DE MATERIALES PARA LA CONSTRUCCION",
							   	"AUTOTRANSPORTE LOCAL DE MATERIALES Y RESIDUOS PELIGROSOS",
							   	"AUTOTRANSPORTE LOCAL DE PRODUCTOS AGROPECUARIOS SIN REFRIGERACION",
							   	"REMOLQUE DE VEHICULOS DE MOTOR",
							   	"SERVICIO DE LIMUSINAS",
							   	"SERVICIO DE MUDANZAS",
							   	"SERVICIOS A LA NAVEGACION AEREA",
							   	"SERVICIOS DE ADMINISTRACION DE CARRETERAS PUENTES Y SERVICIOS AUXILIARES",
							   	"SERVICIOS DE ADMINISTRACION DE CENTRALES CAMIONERAS",
							   	"SERVICIOS DE AGENCIAS ADUANALES",
							   	"SERVICIOS DE BASCULA PARA EL TRANSPORTE",
							   	"SERVICIOS DE CARGA Y DESCARGA PARA EL TRANSPORTE POR AGUA",
							   	"SERVICIOS PARA LA NAVEGACION POR AGUA",
							   	"SERVICIOS RELACIONADOS CON EL TRANSPORTE POR FERROCARRIL",
							   	"TRANSPORTE AEREO NO REGULAR",
							   	"TRANSPORTE AEREO REGULAR EN AERONAVES CON MATRICULA EXTRANJERA",
							   	"TRANSPORTE AEREO REGULAR EN AERONAVES CON MATRICULA NACIONAL",
							   	"TRANSPORTE DE GAS NATURAL POR DUCTOS",
							   	"TRANSPORTE DE PASAJEROS EN TAXIS DE RULETEO",
							   	"TRANSPORTE DE PASAJEROS EN TAXIS DE SITIO",
							   	"TRANSPORTE DE PASAJEROS INTERURBANO Y RURAL",
							   	"TRANSPORTE DE PASAJEROS URBANO Y SUBURBANO EN AUTOBUSES",
							   	"TRANSPORTE DE PASAJEROS URBANO Y SUBURBANO EN AUTOMOVILES COLECTIVOS DE RUTA FIJA",
							   	"TRANSPORTE DE PASAJEROS URBANO Y SUBURBANO EN METRO",
							   	"TRANSPORTE DE PASAJEROS URBANO Y SUBURBANO EN TROLEBUSES Y TRENES LIGEROS",
							   	"TRANSPORTE DE PETROLEO CRUDO POR DUCTOS",
							   	"TRANSPORTE ESCOLAR Y DE PERSONAL",
							   	"TRANSPORTE MARITIMO DE ALTURA EXCEPTO DE PETROLEO Y GAS NATURAL",
							   	"TRANSPORTE MARITIMO DE CABOTAJE EXCEPTO DE PETROLEO Y GAS NATURAL",
							   	"TRANSPORTE MARITIMO DE PETROLEO Y GAS NATURAL",
							   	"TRANSPORTE POR AGUAS INTERIORES",
							   	"TRANSPORTE POR DUC TOS DE OTROS PRODUCTOS EXCEPTO DE PRODUCTOS REFINADOS DEL PETROLEO",
							   	"TRANSPORTE POR DUCTOS DE PRODUCTOS REFINADOS DEL PETROLEO",
							   	"TRANSPORTE POR FERROCARRIL",
							   	"TRANSPORTE TURISTICO POR AGUA",
							   	"TRANSPORTE TURISTICO POR TIERRA",
							    "OTRO AUTOTRANSPORTE FORANEO DE CARGA GENERAL",
							    "OTRO AUTOTRANSPORTE FORANEO DE CARGA ESPECIALIZADO",
							   	"OTRO AUTOTRANSPORTE LOCAL DE CARGA ESPECIALIZADO",
							   	"OTRO AUTOTRANSPORTE LOCAL DE CARGA GENERAL",
							   	"OTRO TRANSPORTE TERRESTRE DE PASAJEROS",
							   	"OTRO TRANSPORTE TURISTICO",
							   	"OTROS SERVICIOS DE INTERMEDIACION PARA EL TRANSPORTE DE CARGA",
							   	"OTROS SERVICIOS RELACIONADOS CON EL TRANSPORTE AEREO",
							   	"OTROS SERVICIOS RELACIONADOS CON EL TRANSPORTE POR AGUA",
							   	"OTROS SERVICIOS RELACIONADOS CON EL TRANSPORTE",]
    	sectorValue = trasnportesCorreosyAlmacenamiento;
   }
    if(sectorValue =="OTROS SERVICIOS EXCEPTO ACTIVIDADES DEL GOBIERNO"){
    		var otrosServicios = [
    						  	"ADMINISTRACION DE CEMENTERIOS",
								"ALINEACION Y BALANCEO DE AUTOMOVILES Y CAMIONES",
								"ASOCIACIONES ORGANIZACIONES Y CAMARAS DE PRODUCTORES COMERCIANTES Y PRESTADORES DE SERVICIOS",
								"ASOCIACIONES Y ORGANIZACIONES CIVILES",
								"ASOCIACIONES Y ORGANIZACIONES DE PROFESIONISTAS",
								"ASOCIACIONES Y ORGANIZACIONES LABORALES Y SINDICALES",
								"ASOCIACIONES Y ORGANIZACIONES POLITICAS",
								"ASOCIACIONES Y ORGANIZACIONES RELIGIOSAS",
								"BAÑOS PUBLICOS",
								"CERRAJERIAS",
								"ESTACIONAMIENTOS Y PENSIONES PARA AUTOMOVILES",
								"FEDERACIONES Y OTRAS ASOCIACIONES REGULATORIAS DE ACTIVIDADES RECREATIVAS",
								"HOGARES CON EMPLEADOS DOMESTICOS",
								"HOJALATERIA Y PINTURA DE AUTOMOVILES Y CAMIONES",
								"INSTALACION DE CRISTALES Y OTRAS REPARACIONES A LA CARROCERIA DE AUTOMOVILES Y CAMIONES",
								"LAVADO Y LUBRICADO DE AUTOMOVILES Y CAMIONES",
								"LAVANDERIAS Y TINTORERIAS",
								"RECTIFICACION DE MOTORES DE AUTOMOVILES Y CAMIONES",
								"REPARACION DE CALZADO Y OTROS ARTICULOS DE PIEL Y CUERO",
								"REPARACION DE SUSPENSIONES DE AUTOMOVILES Y CAMIONES",
								"REPARACION DE TAPICERIA DE MUEBLES PARA EL HOGAR",
								"REPARACION DE TRANSMISIONES DE AUTOMOVILES Y CAMIONES",
								"REPARACION DEL SISTEMA ELECTRICO DE AUTOMOVILES Y CAMIONES",
								"REPARACION MECANICA EN GENERAL DE AUTOMOVILES Y CAMIONES",
								"REPARACION MENOR DE LLANTAS",
								"REPARACION Y MANTENIMIENTO DE APARATOS ELECTRICOS PARA EL HOGAR Y PERSONALES",
								"REPARACION Y MANTENIMIENTO DE BICICLETAS",
								"REPARACION Y MANTENIMIENTO DE EQUIPO ELECTRONICO DE USO DOMESTICOEEUU",
								"REPARACION Y MANTENIMIENTO DE MAQUINARIA Y EQUIPO AGROPECUARIO Y FORESTAL",
								"REPARACION Y MANTENIMIENTO DE MAQUINARIA Y EQUIPO COMERCIAL Y DE SERVICIOS",
								"REPARACION Y MANTENIMIENTO DE MAQUINARIA Y EQUIPO INDUSTRIAL",
								"REPARACION Y MANTENIMIENTO DE MAQUINARIA Y EQUIPO PARA MOVER ACOMODAR Y LEVANTAR MATERIALES",
								"REPARACION Y MANTENIMIENTO DE MOTOCICLETAS",
								"REPARACION Y MANTENIMIENTO DE OTRO EQUIPO ELECTRONICO Y DE EQUIPO DE PRECISION",
								"REPARACION Y MANTENIMIENTO DE OTROS ARTICULOS PARA EL HOGAR Y PERSONALES",
								"SALONES Y CLINICAS DE BELLEZA Y PELUQUERIAS",
								"SANITARIOS PUBLICOS Y BOLERIAS",
								"SERVICIOS DE REVELADO DE FOTOGRAFIAS",
								"SERVICIOS FUNERARIOS",
								"TAPICERIA DE AUTOMOVILES Y CAMIONES",
								"OTRAS REPARACIONES MECANICAS Y ELECTRICAS DE AUTOMOVILES Y CAMIONES",
								"OTROS SERVICIOS DE REPARACION Y MANTENIMIENTO DE AUTOMOVILES Y CAMIONES",
								"OTROS SERVICIOS PERSONALES"]
    	sectorValue = otrosServicios;
   }

   		var newClase ="<span class='plain-select'><select id='Sponsors_sector' class='tooltipstered' name='Sponsors[clase]' onchange='changeClase()'>";
    	newClase+="<option>Seleccionar Clase</option>";
    for (var item in sectorValue) {
        newClase +="<option>"+sectorValue[ item ]+"</option>";
    }

    newClase+="</select></span>";

    $("#comboClase").html(newClase);
     }
</script>



<div class="form">

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'sponsors-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation' => true,
	'htmlOptions' => array('enctype' => 'multipart/form-data'),
	'enableClientValidation' => true,
));?>


	<div class="row">

<div class="row">
  <span class="plain-select">
	<?php $this->widget('ext.CountrySelectorWidget', array(

		'value' => $modelAddresses->country,
		'name' => Chtml::activeName($modelAddresses, 'country'),
		'id' => Chtml::activeId($modelAddresses, 'country'),
		'useCountryCode' => false,
		'defaultValue' => 'Mexico',
		'firstEmpty' => true,
		'firstText' => 'Pais',

		)); ?>
</span>
        </div>

    <div class="row" class="">
		<?php echo $form->textField($modelAddresses, 'state', array('size' => 20, 'maxlength' => 20, 'placeholder' => 'Estado','onKeypress'=>'return lettersOnly(event)','title'=>'Estado'));?>
		<?php echo $form->error($modelAddresses, 'state');?>
	</div>

	<div class="row">
		<?php echo $form->textField($modelAddresses, 'zip_code', array('placeholder' => 'Código Postal', 'class' => 'numericOnly','title'=>'Código Postal'));?>
		<?php echo $form->error($modelAddresses, 'zip_code');?>
	</div>



	<div class="row">

		<?php echo $form->textField($modelAddresses, 'delegation', array('size' => 30, 'maxlength' => 30, 'placeholder' => 'Delegación','onKeypress'=>'return lettersOnly(event)','title'=>'Delegación'));?>
		<?php echo $form->error($modelAddresses, 'delegation');?>
	</div>

	<div class="row">

		<?php echo $form->textField($modelAddresses, 'city', array('size' => 50, 'maxlength' => 50, 'placeholder' => 'Ciudad','onKeypress'=>'return lettersOnly(event)','title'=>'Ciudad'));?>
		<?php echo $form->error($modelAddresses, 'city');?>
	</div>

	<div class="row">

		<?php echo $form->textField($modelAddresses, 'town', array('size' => 30, 'maxlength' => 30, 'placeholder' => 'Municipio','onKeypress'=>'return lettersOnly(event)','title'=>'Municipio'));?>
		<?php echo $form->error($modelAddresses, 'town');?>
	</div>

	<div class="row">

		<?php echo $form->textField($modelAddresses, 'colony', array('size' => 45, 'maxlength' => 45, 'placeholder' => 'Colonia','title'=>'Colonia'));?>
		<?php echo $form->error($modelAddresses, 'colony');?>
	</div>

	<div class="row">
		<?php echo $form->textField($modelAddresses, 'street', array('size' => 50, 'maxlength' => 50, 'placeholder' => 'Calle','title'=>'Calle'));?>
		<?php echo $form->error($modelAddresses, 'street');?>
	</div>

	<div class="row">

		<?php echo $form->textField($modelAddresses, 'external_number', array('size' => 8, 'maxlength' => 8, 'placeholder' => 'Número Externo','title'=>'Número Externo'));?>
		<?php echo $form->error($modelAddresses, 'external_number');?>
	</div>

	<div class="row">
		<?php echo $form->textField($modelAddresses, 'internal_number', array('size' => 8, 'maxlength' => 8, 'placeholder' => 'Número Interno', 'class' => 'numericOnly','title'=>'Número Interno'));?>
		<?php echo $form->error($modelAddresses, 'internal_number');?>
	</div>



	<div class="row">
		<?php echo $form->textField($model, 'sponsor_name', array('size' => 50, 'maxlength' => 50, 'placeholder'=>'Nombre de la empersa','title'=>'Nombre de la empersa'));?>
		<?php echo $form->error($model, 'sponsor_name');?>
	</div>

		<div>
		<span class="row plain-select">
		<?php echo $form->dropDownList($model,'type',array('no lucrativo'=>'No lucrativo','privado'=>'Privado', 'publico'=>'Publico'),
		                                                       array('title'=>'Tipo de identidad','prompt'=>'Seleccione el tipo de identidad','options' => array(''=>array('selected'=>true))),
		                                                       array('size'=>10)); ?>
		<?php echo $form->error($model,'type'); ?>
		</span>
	</div>

	<div class="row">
		<?php echo $form->textField($model, 'website', array('size' => 60, 'maxlength' => 100, 'placeholder'=>'Pagina Web','title'=>'Pagina Web'));?>
		<?php echo $form->error($model, 'website');?>
	</div>

	<div class="row">


		<?php  echo $form->dropDownList($model, 'sector', array('ACTIVIDADES DEL GOBIERNO Y DE ORGANISMOS INTERNACIONALES Y EXTRATERRITORIALES'=>'ACTIVIDADES DEL GOBIERNO Y DE ORGANISMOS INTERNACIONALES Y EXTRATERRITORIALES',
																'AGRICULTURA GANADERIA APROVECHAMIENTO FORESTAL PESCA Y CAZA'=>'AGRICULTURA GANADERIA APROVECHAMIENTO FORESTAL PESCA Y CAZA',
																'COMERCIO AL POR MAYOR'=>'COMERCIO AL POR MAYOR',
																'COMERCIO AL POR MENOR'=>'COMERCIO AL POR MENOR',
																'CONSTRUCCION'=>'CONSTRUCCION',
																'DIRECCION DE CORPORATIVOS Y EMPRESAS'=>'DIRECCION DE CORPORATIVOS Y EMPRESAS',
																'ELECTRICIDAD AGUA Y SUMINISTRO DE GAS POR DUCTOS AL CONSUMIDOR FINAL'=>'ELECTRICIDAD AGUA Y SUMINISTRO DE GAS POR DUCTOS AL CONSUMIDOR FINAL',
																'INDUSTRIA MANUFACTURERA ALIMENTARIA, TABACO, BEBIDAS Y FABRICACIÓN DE TEXTILES'=>'INDUSTRIA MANUFACTURERA ALIMENTARIA, TABACO, BEBIDAS Y FABRICACIÓN DE TEXTILES',
																'INDUSTRIA MANUFACTURERA DE MADERA, PAPEL, DERIVADOS DEL PETRÓLEO E INDUSTRIA QUÍMICA'=>'INDUSTRIA MANUFACTURERA DE MADERA, PAPEL, DERIVADOS DEL PETRÓLEO E INDUSTRIA QUÍMICA',
																'INDUSTRIA MANUFACTURERA MAQUINARÍA EQUIPO'=>'INDUSTRIA MANUFACTURERA MAQUINARÍA EQUIPO',
																'INFORMACION EN MEDIOS MASIVOS'=>'INFORMACION EN MEDIOS MASIVOS',
																'MINERIA'=>'MINERIA',
																'SERVICIOS DE ALOJAMIENTO TEMPORAL Y DE PREPARACION DE ALIMENTOS Y BEBIDAS'=>'SERVICIOS DE ALOJAMIENTO TEMPORAL Y DE PREPARACION DE ALIMENTOS Y BEBIDAS',
																'SERVICIOS DE APOYO A LOS NEGOCIOS Y MANEJO DE DERECHOS Y SERVICIOS DE REMEDIACION'=>'SERVICIOS DE APOYO A LOS NEGOCIOS Y MANEJO DE DERECHOS Y SERVICIOS DE REMEDIACION',
																'SERVICIOS DE ESPARCIMIENTO CULTURALES Y DEPORTIVOS Y OTROS SERVICIOS RECREATIVOS'=>'SERVICIOS DE ESPARCIMIENTO CULTURALES Y DEPORTIVOS Y OTROS SERVICIOS RECREATIVOS',
																'SERVICIOS DE SALUD Y DE ASISTENCIA SOCIAL'=>'SERVICIOS DE SALUD Y DE ASISTENCIA SOCIAL',
																'SERVICIOS EDUCATIVOS'=>'SERVICIOS EDUCATIVOS',
																'SERVICIOS FINANCIEROS Y DE SEGUROS'=>'SERVICIOS FINANCIEROS Y DE SEGUROS',
																'SERVICIOS INMOBILIARIOS Y DE ALQUILER DE BIENES MUEBLES E INTANGIBLES'=>'SERVICIOS INMOBILIARIOS Y DE ALQUILER DE BIENES MUEBLES E INTANGIBLES',
																'SERVICIOS POSTALES, MENSAJERÍA, PAQUETERÍA Y ALMACENAMIENTO'=>'SERVICIOS POSTALES, MENSAJERÍA, PAQUETERÍA Y ALMACENAMIENTO',
																'SERVICIOS PROFESIONALES CIENTIFICOS Y TECNICOS'=>'SERVICIOS PROFESIONALES CIENTIFICOS Y TECNICOS',
																'TRANSPORTES CORREOS Y ALMACENAMIENTO'=>'TRANSPORTES CORREOS Y ALMACENAMIENTO',
																'OTROS SERVICIOS EXCEPTO ACTIVIDADES DEL GOBIERNO'=>'OTROS SERVICIOS EXCEPTO ACTIVIDADES DEL GOBIERNO'),array('prompt'=>'Seleccionar sector','title'=>'Sector', 'id'=>'sector', 'onchange'=>'changeSector()'))?>
		<?php echo $form->error($model, 'sector');?>
	</div>

	<div class="row" id="comboClase">

  </div>

	<div class="row">
		<?php echo $form->textField($model, 'branch', array('size' => 60, 'maxlength' => 100,'placeholder'=>'Rama','title'=>'Rama'));?>
		<?php echo $form->error($model, 'branch');?>


    </div>

	<div class="row">
		<?php echo $form->textField($model, 'main_activity', array('size' => 60, 'maxlength' => 100,'placeholder'=>'Actividad Principal','title'=>'Actividad Principal'));?>
		<?php echo $form->error($model, 'main_activity');?>
	</div>

	<div class="row">
		<?php echo $form->textField($model, 'legal_structure', array('size' => 60, 'maxlength' => 100,'placeholder'=>'Estructura Legal','title'=>'Estructura Legal'));?>
		<?php echo $form->error($model, 'legal_structure');?>
	</div>

	<div class="row">
		<?php echo $form->textField($model, 'employeess_number', array('class' => 'numericOnly','placeholder'=>'Numero de empleados','title'=>'Numero de empleados'));?>
		<?php echo $form->error($model, 'employeess_number');?>
	</div>

	<div class="row">


		<?php echo $form->fileField($modelPersons, 'photo_url', array('size' => 60, 'maxlength' => 100, 'placeholder' => "Foto",'title'=>'Foto de Perfil'));?>
		<?php echo $form->error($modelPersons, 'photo_url');?>
		<br>
	</div>

	<div class="row buttons">

	  <?php echo CHtml::htmlButton('Enviar',array(
                'onclick'=>'send("sponsors-form", "sponsors/sponsorsInfo", "'.(isset($_GET['id']) ? $_GET['id'] : 0).'","'.Yii::app()->controller->id.'/'.Yii::app()->controller->action->id.'/'.(isset($_GET['id']) ? $_GET['id'] : 0).'","")',
                'class'=>'savebutton',
            ));
    ?>

		<?php echo CHtml::Button('Cancelar',array('submit' => array('sponsors/sponsorsInfo'),'confirm'=>'¿Seguro que desea Cancelar?','id'=>'cancelar')); ?>
	</div>

<?php $this->endWidget();?>

</div>
