<?php
/* @var $this BooksChaptersController */
/* @var $model BooksChapters */
/* @var $form CActiveForm */
$cs = Yii::app()->getClientScript();
$cs->registerScriptFile(Yii::app()->baseUrl.'/protected/views/booksChapters/js/script.js');
?>


<script type="text/javascript">
  $(document).ready(function() {
      $(".numericOnly").keydown(function (e) {
          if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
              (e.keyCode == 65 && e.ctrlKey === true) ||
              (e.keyCode >= 35 && e.keyCode <= 40)) {
                  return;
          }
          if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
              e.preventDefault();
          }

      });
  });
  function changeArea(){
    
    var areaValue = $("#area option:selected").val();

if(areaValue =="ANTROPOLOGIA"){
    var ANTROPOLOGIA = ["ANTROPOLOGIA CULTURAL","ANTROPOLOGIA ESTRUCTURAL",
   "ANTROPOLOGIA SOCIAL","ETNOGRAFIA Y ETNOLOGIA","OTRAS ESPECIALIDADES EN MATERIA DE ANTROPOLOGIA"]
    areaValue = ANTROPOLOGIA;
   }
   if(areaValue =="ARTES Y LETRAS"){
    var ARTESYLETRAS = ["ARQUITECTURA","TEORIA","ANALISIS Y CRITICA DE LAS BELLAS ARTES",
   "ANALISIS Y CRITICA LITERARIOS","TEORIA","OTRAS ESPECIALIDADES EN MATERIA DE ARTES Y LETRAS"]
    areaValue = ARTESYLETRAS;
  }
  if(areaValue =="ASTRONOMIA Y ASTROFISICA"){
    var ASTRONOMIAYASTROFISICA = ["ASTRONOMIA OPTICA","COSMOLOGIA Y COSMOGONIA","ESPACIOS Y MATERIA INTERPLANETARIOS",
   "PLANETOLOGIA","RADIOASTRONOMIA","SISTEMA SOLAR","OTRAS ESPECIALIDADES EN MATERIA DE ASTRONOMIA"]
    areaValue = ASTRONOMIAYASTROFISICA;
  }
  if(areaValue =="CIENCIAS AGRONOMICAS Y VETERINARIAS"){
    var CIENCIASAGRONOMICASYVETERINARIAS = ["AGRONOMIA","CIENCIAS VETERINARIAS","CIENCIAS VETERINARIAS",
   "FITOPATOLOGIA","HIGIENE VETERINARIA Y SALUD PUBLICA","HORTICULTURA","INGENIERIA RURAL",
   "OTRAS ESPECIALIDADES EN MATERIA DE CIENCIAS AGRONOMICAS Y VETERINARIAS","PECES Y ANIMALES SALVAJES",
   "SILVICULTURA","QUIMICA AGRONOMICA"]
    areaValue = CIENCIASAGRONOMICASYVETERINARIAS;
  }
  if(areaValue =="CIENCIAS DE LA OCUPACION"){
    var CIENCIASDELAOCUPACION = ["TERAPIA OCUPACIONAL"]
    areaValue = CIENCIASDELAOCUPACION;
  }
  if(areaValue =="CIENCIAS DE LA TECNOLOGIA"){
    var CIENCIASDELATECNOLOGIA = ["ANALISIS DE LAS OPERACIONES TECNOLOGICAS","CIENCIAS DE LA COMPUTACION","GESTION DE LA CALIDAD","INSTRUMENTAL TECNOLOGICO",
   "OTRAS ESPECIALIDADES EN MATERIA DE TECNOLOGIA","TECNOLOGIA BIOQUIMICA","TECNOLOGIA DE FERROCARRILES",
   "TECNOLOGIA DE LA ALIMENTACION","TECNOLOGIA DE BIOMOLECULAS","TECNOLOGIA DE BIOPROCESOS","TECNOLOGIA DE LA CONSTRUCCION",
   "TECNOLOGIA DE LA ENERGIA","TECNOLOGIA DE LA INFORMATICA","TECNOLOGIA DE LA MEDICINA","TECNOLOGIA DE LA METALURGIA",
   "TECNOLOGIA DE LAS MATERIAS","TECNOLOGIA DE LAS TELECOMUNICACIONES","TECNOLOGIA DE LOS PRODUCTOS METALICOS",
   "TECNOLOGIA DE MINAS","TECNOLOGIA ELECTRONICA","TECNOLOGIA DEL ESPACIO","TECNOLOGIA DEL MEDIO AMBIENTE","TECNOLOGIA DEL URBANISMO",
   "TECNOLOGIA DE LOS VEHICULOS DE MOTOR","TECNOLOGIA E INGENIERIA AERONAUTICA","TECNOLOGIA E INGENIERIA DE LA ELECTRICIDAD",
   "TECNOLOGIA E INGENIERIA QUIMICA","TECNOLOGIA INDUSTRIAL","TECNOLOGIA MECANICA","TECNOLOGIA NAVAL",
   "TECNOLOGIA NUCLEAR","TECNOLOGIA TEXTIL","TECNOLOGIA DEL PETROLEO Y DEL CARBON","TECNOLOGIA DE LOS SISTEMAS DE TRANSPORTE"]
    areaValue = CIENCIASDELATECNOLOGIA;
  }
  if(areaValue =="CIENCIAS DE LA TIERRA Y DEL COSMOS"){
    var CIENCIASDELATIERRAYDELCOSMOS = ["CIENCIAS ATMOSFERICAS","CLIMATOLOGIA","GEOQUIMICA","GEODESIA","GEOGRAFIA","GEOLOGIA","GEOFISICA","HIDROLOGIA","METEOROLOGIA","OCEANOGRAFIA","CIENCIAS DEL SUELO","CIENCIAS DEL COSMOS","OTRAS ESPECIALIDADES EN MATERIA DE CIENCIAS DE LA TIERRA","DEL COSMOS Y DEL MEDIO AMBIENTE"]
    areaValue = CIENCIASDELATIERRAYDELCOSMOS;
  }
  if(areaValue =="CIENCIAS DE LA SALUD"){
    var CIENCIASDELASALUD = ["ENFERMERÍA","INVESTIGACIÓN EN SALUD","SALUD PÚBLICA"]
    areaValue = CIENCIASDELASALUD;
  }
  if(areaValue =="CIENCIAS DE LA VIDA"){
    var CIENCIASDELAVIDA = ["ANTROPOLOGIA FISICA",
   "BIOFISICA","BIOLOGIA ANIMAL Y ZOOLOGIA","BIOLOGIA CELULAR","BIOLOGIA HUMANA","BIOLOGIA MOLECULAR",
   "BOTANICA","BIOQUIMICA","BIOMATEMATICA","BIOMETRIA","ENTOMOLOGIA GENERAL","ETOLOGIA",
   "EVOLUCION","FISIOLOGIA HUMANA","GENETICA","INMUNOLOGIA","MEDIO AMBIENTE","MICROBIOLOGIA",
   "OTRAS ESPECIALIDADES EN MATERIA DE BIOLOGIA","PALEONTOLOGIA","RADIOBIOLOGIA","SIMBIOSIS","VIROLOGIA"]
    areaValue = CIENCIASDELAVIDA;
  }
  if(areaValue =="CIENCIAS ECONOMICAS"){
    var CIENCIASECONOMICAS = ["ACTIVIDADES ECONOMICAS",
   "CAMBIO ECONOMICO O TECNOLOGICO","CONTABILIDAD PUBLICA","POLITICA FISCAL Y HACIENDA PUBLICA",
   "ECONOMETRIA","ECONOMIA INTERNACIONAL","ECONOMIA SECTORIAL","GESTION DE LA CALIDAD",
   "ORGANIZACION DE LA INDUSTRIA Y POLITICA ECONOMICA PUBLICA","ORGANIZACION Y DIRECCION DE EMPRESAS",
   "OTRAS ESPECIALIDADES EN MATERIA DE ECONOMIA","SISTEMAS ECONOMICOS","TEORIA ECONOMICA","ECONOMIA GENERAL"]
    areaValue = CIENCIASECONOMICAS;
  }
  if(areaValue =="CIENCIAS JURIDICAS Y DERECHO"){
    var CIENCIASJURIDICASYDERECHO = ["DERECHO CANONICO",
   "DERECHO INTERNACIONAL","DERECHO Y LEGISLACION NACIONALES",
   "ORGANIZACION PENAL","OTRAS ESPECIALIDADES EN MATERIA JURIDICA",
   "TEORIAS Y METODOS JURIDICOS GENERALES"]
    areaValue = CIENCIASJURIDICASYDERECHO;
  }
  if(areaValue =="CIENCIAS POLITICAS"){
    var CIENCIASPOLITICAS = ["ADMINISTRACION PUBLICA","BIBLIOTECONOMIA Y ARCHIVONOMIA",
   "IDEOLOGIAS POLITICAS","INSTITUCIONES POLITICAS","RELACIONES INTERNACIONALES","OPINION PUBLICA", 
   "OTRAS ESPECIALIDADES EN MATERIA DE CIENCIAS POLITICAS","POLITICA TEORICA","POLITICAS SECTORIALES",
   "POLITICA TEORICA","SOCIOLOGIA DE LA POLITICA","SISTEMAS POLITICOS","VIDA POLITICA"]
    areaValue = CIENCIASPOLITICAS;
  }
  if(areaValue =="DEMOGRAFIA"){
    var DEMOGRAFIA = ["CARACTERISTICAS DE LAS POBLACIONES",
   "FECUNDIDAD","DEMOGRAFIA GENERAL","DEMOGRAFIA GEOGRAFICA","DEMOGRAFIA HISTORICA",
   "EVOLUCION DEMOGRAFICA","MORTALIDAD","OTRAS ESPECIALIDADES EN MATERIA DE DEMOGRAFIA"]
    areaValue = DEMOGRAFIA;
  }
  if(areaValue =="ETICA"){
    var ETICA = ["ETICA CLASICA","ETICA INDIVIDUAL","ETICA DE GRUPO","ETICA PROSPECTIVA","OTRAS ESPECIALIDADES EN MATERIA DE ETICA"]
    areaValue  = ETICA;
  }
  if(areaValue =="FILOSOFIA"){
  var FILOSOFIA = ["ANTROPOLOGIA FILOSOFICA","DOCTRINAS FILOSOFICAS","FILOSOFIA DE LOS CONOCIMIENTOS",
 "FILOSOFIA GENERAL","FILOSOFIA DE LA CIENCIA","FILOSOFIA DE LA NATURALEZA",
 "FILOSOFIA SOCIAL","OTRAS ESPECIALIDADES EN MATERIA DE FILOSOFIA","SISTEMAS FILOSOFICOS"]
  areaValue = FILOSOFIA;
  }
  if(areaValue =="FISICA"){
  var FISICA = ["ACUSTICA","ELECTROMAGNETISMO","ELECTRONICA","FISICOQUIMICA",
 "FISICA DE LAS PARTICULAS NUCLEARES","FISICA DE LOS FLUIDOS","FISICA DEL ESPACIO","FISICA MOLECULAR",
 "FISICA NUCLEAR","FISICA DEL ESTADO SOLIDO","FISICA TEORICA","MECANICA","OPTICA",
 "OTRAS ESPECIALIDADES EN MATERIA DE FISICA","TERMODINAMICA","UNIDADES Y CONSTANTES FISICAS"]
  areaValue = FISICA;
}
if(areaValue =="GEOGRAFIA"){
  var GEOGRAFIA = ["GEOGRAFIA ECONOMICA","GEOGRAFIA HISTORICA","GEOGRAFIA HUMANA","GEOGRAFIA REGIONAL","OTRAS ESPECIALIDADES EN MATERIA DE GEOGRAFIA"]
  areaValue = GEOGRAFIA;
}
if(areaValue =="HISTORIA"){
  var HISTORIA = ["BIOGRAFIA","CIENCIAS AUXILIARES DE LA HISTORIA","HISTORIA GENERAL","HISTORIA DE LOS PAISES",
 "HISTORIA DE LAS EPOCAS","HISTORIA ESPECIALIZADA","OTRAS ESPECIALIDADES EN MATERIA DE HISTORIA"]
  areaValue = HISTORIA;
}
if(areaValue =="LINGÜISTICA"){
    var LINGÜISTICA = ["GEOGRAFIA LINGÜISTICA","LINGÜISTICA APLICADA",
   "LINGÜISTICA DIACRONICA","LINGÜISTICA TEORICA","LINGÜISTICA SINCRONICA",
   "POLITICAS DEL LENGUAJE","OTRAS ESPECIALIDADES EN MATERIA DE LINGÜÍSTICA"]
    areaValue = LINGÜISTICA;
}
if(areaValue =="LOGICA"){
  var LOGICA = ["APLICACIONES DE LA LOGICA","LOGICA DEDUCTIVA","LOGICA GENERAL","LOGICA INDUCTIVA","METODOLOGIA","OTRAS ESPECIALIDADES EN MATERIA DE LOGICA"]
  areaValue = LOGICA;
}
if(areaValue =="MATEMATICAS"){
  var MATEMATICAS = ["ALGEBRA","ANALISIS NUMERICO",
 "ANALISIS Y ANALISIS FUNCIONAL","CALCULO DE PROBABILIDADES",
 "ESTADISTICA","GEOMETRIA","INFORMATICA","INFORMATICA MATEMATICA",
 "INVESTIGACION OPERATIVA","MATEMATICAS","TEORIA DE LOS NUMEROS",
 "SISTEMAS","OTRAS ESPECIALIDADES EN MATERIA DE MATEMATICAS","TOPOLOGIA"]
  areaValue = MATEMATICAS;
}
if(areaValue =="MEDICINA Y PATOLOGIA HUMANA"){
  var MEDICINAYPATOLOGIAHUMANA = ["ADMINISTRACION DE HOSPITALES Y DE LA ATENCION MEDICA",
 "BIOLOGIA DE LA REPRODUCCION HUMANA","CIENCIAS DE LA INFORMACION Y COMUNICACION EN MEDICINA",
 "CIENCIAS SOCIALES EN MEDICINA","EPIDEMIOLOGIA",
 "FARMACODINAMICA","FARMACOLOGIA","FISIOLOGIA","MORFOLOGIA",
 "MEDICINA CLINICA","MEDICINA FORENSE","MEDICINA DEL TRABAJO",
 "MEDICINA INTERNA","MEDICINA PREVENTIVA","MEDICINA QUIRURGICA","NUTRICION","OBSTETRICIA",
 "OTRAS ESPECIALIDADES EN MATERIA DE MEDICINA Y PATOLOGIA HUMANAS",
 "PATOLOGIA","PSIQUIATRIA","SANIDAD PUBLICA","TOXICOLOGIA"]
  areaValue = MEDICINAYPATOLOGIAHUMANA;
}
if(areaValue =="PEDAGOGIA"){
  var PEDAGOGIA = ["FORMACION Y EMPLEO DE LOS EDUCADORES",
 "ORGANIZACION Y PLANIFICACION PEDAGOGICAS",
 "OTRAS ESPECIALIDADES EN MATERIA DE PEDAGOGIA",
 "TEORIAS Y METODOS PEDAGOGICOS GENERALES"]
    areaValue = PEDAGOGIA;
}
if(areaValue =="PSICOLOGIA"){
  var PSICOLOGIA = ["ESTUDIO DE LA PERSONALIDAD","ESTUDIO PSICOLOGICO DE FENOMENOS SOCIALES",
 "EVALUACION Y MEDICION PSICOLOGICAS","ORIENTACION PSICOLOGICA",
 "OTRAS ESPECIALIDADES EN MATERIA DE PSICOLOGIA","PARAPSICOLOGIA",
 "PSICOFARMACOLOGIA","PSICOLOGIA PATOLOGICA","PSICOLOGIA DE LA EDUCACION",
 "PSICOLOGIA DEL NIÑO Y DEL ADOLESCENTE","PSICOLOGIA EXPERIMENTAL","PSICOLOGIA GENERAL",
 "PSICOLOGIA GERIATRICA","PSICOLOGIA SOCIAL","PSICOLOGIA DEL TRABAJO Y DEL PERSONAL"]
  areaValue = PSICOLOGIA;
}
if(areaValue =="PROSPECTIVA"){
  var PROSPECTIVA = ["ANALISIS DE RIESGOS","ANALISIS DE TENDENCIAS",
 "CONSTRUCCION DE ESCENARIOS","DESARROLLO SUSTENTABLE","DISEÑO DE PRIORIDADES A LARGO PLAZO","ETICA DEL FUTURO",
 "FUTURO DE LOS CONOCIMIENTOS Y LAS NUEVAS TECNOLOGIAS","NUEVAS FUERTES DE ENERGIA","NUEVOS SISTEMAS ORGANIZACIONALES","REVISION",
 "OTRAS ESPECIALIDADES EN MATERIA PROSPECTIVA","PLANEACION Y DISEÑO DE ESTRATEGIAS","TENDENCIAS DEMOGRAFICAS Y POBLACIONALES"]
  areaValue = PROSPECTIVA;
}
if(areaValue =="QUIMICA"){
  var QUIMICA = ["BIOQUIMICA","FARMACOBIOLOGIA",
 "OTRAS ESPECIALIDADES EN MATERIA DE QUIMICA",
 "QUIMICA ANALITICA","QUIMICA DE LAS MACROMOLECULAS",
 "QUIMICA FISICA","QUIMICA INORGANICA","QUIMICA NUCLEAR","QUIMICA ORGANICA"]
  areaValue = QUIMICA;
}
if(areaValue =="SOCIOLOGIA"){
  var SOCIOLOGIA = ["CAMBIO Y DESARROLLO SOCIAL","COMUNICACION SOCIAL",
 "CULTURA FÍSICA","HUMANIDADES","GRUPOS SOCIALES","PROBLEMAS INTERNACIONALES",
 "PROBLEMAS SOCIALES","ORGANIZACION SOCIAL ESTRUCTURA E INSTITUCIONES",
 "OTRAS ESPECIALIDADES EN MATERIA DE SOCIOLOGIA","SOCIOLOGIA CULTURAL",
 "SOCIOLOGIA EXPERIMENTAL","SOCIOLOGIA GENERAL","SOCIOLOGIA MATEMATICA Y ESTADISTICA",
 "SOCIOLOGIA DE ACTIVIDADES PARTICULARES","SOCIOLOGIA DE LA IMPLANTACION HUMANA"]
  areaValue = SOCIOLOGIA;
}


    var newDiscipline ="<span class='plain-select'><select id='BooksChapters_discipline' class='tooltipstered' name='BooksChapters[discipline]' onchange='changeDiscipline()'>";
    newDiscipline+="<option>Seleccionar Disciplina</option>";
    for (var item in areaValue) {
        newDiscipline +="<option>"+areaValue[ item ]+"</option>";
    }

    newDiscipline+="</select></span>";

    $("#comboDiscipline").html(newDiscipline);
  }

  function changeDiscipline(){
  var disciplineValue = $("#BooksChapters_discipline option:selected").val();

    if(disciplineValue =="Seleccionar Disciplina"){
      var seleccionarDisciplina ="";
      disciplineValue = aplicacionesDeLaLogica;
    }

    if(disciplineValue =="LOGICA DEDUCTIVA"){
      var logicaDeductiva = ["ALGEBRA DE BOOLE", 
                  "ANALOGIA", 
                  "CALCULO DE PROPOSICIONES", 
                  "FUNCIONES RECURSIVAS", 
                  "FUNDAMENTOS DE LAS MATEMATICAS", 
                  "GENERALIZACION", 
                  "LENGUAJES FORMALIZADOS", 
                  "LOGICA FORMAL", 
                  "LOGICA MATEMATICA", 
                  "LOGICA MODAL", 
                  "LOGICA SIMBOLICA", 
                  "SISTEMAS FORMALES", 
                  "TEORIA DE DEMOSTRACIONES Y MATEMATICAS CONSTRUCTIVAS", 
                  "TEORIA DE LAS PRUEBAS", 
                  "TEORIA DE LOS LENGUAJES FORMALES", 
                  "TEORIA DE LOS MODELOS", 
                  "OTROS"]
      disciplineValue = logicaDeductiva;
    }
    if(disciplineValue =="LOGICA INDUCTIVA"){
      var logicaInductiva = ["INDUCCION", 
                 "INTUICIONISMO", 
                 "PROBABILIDAD", 
                 "OTROS"]
      disciplineValue = logicaInductiva;
    }
    if(disciplineValue =="METODOLOGIA"){
      var metodologia = ["METODO CIENTIFICO", 
               "OTROS"]
      disciplineValue = metodologia;
    }
    if(disciplineValue =="ALGEBRA"){
      var algebra = ["ALGEBRA DE LIE","ALGEBRA DIFERENCIAL", 
              "ALGEBRA HOMOLOGICA", 
              "ALGEBRA LINEAL", 
              "ALGEBRAS", 
              "ALGEBRAS NO ASOCIATIVAS", 
              "ANILLOS", 
              "CAMPOS", 
              "ESTRUCTURAS ALGEBRAICAS", 
              "GENERALIDADES", 
              "GEOMETRIA ALGEBRAICA", 
              "GRUPOS","POLINOMIOS", 
              "RETICULOS", 
              "TEORIA AXIOMATICA DE CONJUNTOS", 
              "TEORIA DE LAS CATEGORIAS", 
              "TEORIA DE LAS MATRICES", 
              "TEORIA DE LA REPRESENTACION", 
              "TEORIA K ALGEBRAICA", 
              "OTROS"]
      disciplineValue = algebra;
    }
    if(disciplineValue =="ANALISIS Y ANALISIS FUNCIONAL"){
      var analisisYAnalisisFuncional = [ "ALGEBRA DE OPERADORES LOGICOS",
                       "ANALISIS ARMONICO", 
                       "ANALISIS COMBINATORIO", 
                       "ANALISIS DE FOURIER",
                         "ANALISIS GLOBAL", 
                         "AREA",
                         "CALCULO DE VARIACIONES", 
                         "CALCULO OPERACIONAL", 
                         "CONVEXIDAD", 
                         "DESIGUALDADES", 
                         "ECUACIONES DIFERENCIALES ORDINARIAS", 
                         "ECUACIONES DIFERENCIALES PARCIALES", 
                         "ECUACIONES EN DIFERENCIAS FINITAS", 
                         "ECUACIONES FUNCIONALES", 
                         "ECUACIONES INTEGRALES", 
                         "ESPACIOS ANALITICOS", 
                         "ESPACIOS DE HILBERT", 
                         "ESPACIOS LINEALES TOPOLOGICOS",
                         "ESPACIOS Y ALGEBRAS DE BANACH",
                         "MEDIDAS", 
                         "INTEGRACION", 
                         "FUNCIONES DE UNA VARIABLE COMPLEJA", 
                         "FUNCIONES DE VARIABLES REALES", 
                         "FUNCIONES DE VARIAS VARIABLES COMPLEJAS",
                         "FUNCIONES ESPECIALES",
                           "FUNCIONES SUBARMONICAS",
                           "SERIES",
                           "SERIES E INTEGRALES TRIGONOMETRICAS",
                           "SUMABILIDAD","TEORIA DE FUNCIONES GENERALIZADA", 
                           "TEORIA DE GRAFICAS","TEORIA DE LA APROXIMACION", 
                           "TEORIA DEL POTENCIAL", 
                           "TEORIA ERGODICA", 
                           "TRANSFORMACIONES INTEGRALES", 
                           "OTROS"]
      disciplineValue = analisisYAnalisisFuncional;
    }
    if(disciplineValue =="INFORMATICA MATEMATICA"){
      var informaticaMatematica = ["BANCOS DE DATOS",
                       "CODIGOS Y SISTEMAS DE CODIFICACION", 
                       "COMPUTACION ANALOGICA", 
                       "COMPUTACION DIGITAL",
                         "COMPUTACION HIBRIDA", 
                         "CONTABILIDAD",
                         "CONTROL DE INVENTARIO", 
                         "DISEÑO CON AYUDA DE COMPUTADOR", 
                         "DISEÑO DE SISTEMAS DE SENSORES", 
                         "DISEÑO Y COMPONENTES", 
                         "ENSEÑANZA CON AYUDA DE COMPUTADOR", 
                         "HEURISTICA", 
                         "LENGUAJES ALGORITMICOS", 
                         "LENGUAJES DE PROGRAMACION", 
                         "MODELIZACION CAUSAL", 
                         "INFORMATICA", 
                         "INTELIGENCIA ARTIFICIAL", 
                         "SIMULACION",
                         "SISTEMAS AUTOMATICOS DE CONTROL DE CALIDAD",
                         "SISTEMAS DE CONTROL AMBIENTAL", 
                         "SISTEMAS DE CONTROL MEDICO", 
                         "SISTEMAS DE CONTROL DE PRODUCCION", 
                         "SISTEMAS DE INFORMACION", 
                         "SISTEMAS DE NAVEGACION DE TELEMETRIA Y ESPACIAL",
                         "SISTEMAS DE PRODUCCION AUTOMATICA",
                           "SOPORTE LOGICO DE COMPUTADORES",
                           "TEORIA DE LA PROGRAMACION",
                           "OTROS"]
      disciplineValue = informaticaMatematica;
    }
    if(disciplineValue =="GEOMETRIA"){
      var geometria = ["ANALISIS TENSORIAL",
               "DOMINIOS CONVEXOS", 
               "ESTRUCTURAS DE ORDEN GEOMETRICO", 
               "FUNDAMENTOS",
                 "GEOMETRIA AFIN", 
                 "GEOMETRIA COMPLEJA Y REAL",
                 "GEOMETRIA DESCRIPTIVA Y ANALITICA", 
                 "GEOMETRIA DIFERENCIAL", 
                 "GEOMETRIA DISCRETA", 
                 "GEOMETRIA EUCLIDIANA", 
                 "GEOMETRIA PROYECTIVA", 
                 "GEOMETRIA TOPOLOGICA", 
                 "GEOMETRIA RIEMANIANA", 
                 "GEOMETRIAS INFINITAS", 
                 "GEOMETRIAS NO EUCLIDIANAS", 
                 "PROBLEMAS DE EXTREMO", 
                 "TEORIA DE LA FUNCION GEOMETRICA", 
                 "TEORIA K",
                 "VARIEDADES COMPLEJAS",
                   "OTROS"]
      disciplineValue = geometria;
    }
    if(disciplineValue =="TEORIA DE LOS NUMEROS"){
      var teoriaDeLosNumeros = [ "GEOMETRIA DE LOS NUMEROS",
                   "PROBLEMAS DIOFANTINOS", 
                   "SUCESIONES Y CONJUNTOS", 
                   "TEORIA DE LOS NUMEROS ALGEBRAICOS",
                     "TEORIA DE LOS NUMEROS ANALITICOS", 
                     "TEORIA DE LOS NUMEROS ELEMENTALES",
                     "TEORIA K", 
                       "OTROS"]
      disciplineValue = teoriaDeLosNumeros;
    }
    if(disciplineValue =="ANALISIS NUMERICO"){
      var analisisNumerico = [ "ANALISIS DE ERRORES",
                   "CONSTRUCCION DE ALGORITMOS", 
                   "CUADRATURA", 
                   "DIFERENCIACION NUMERICA",
                     "ECUACIONES DIFERENCIALES", 
                     "ECUACIONES DIFERENCIALES ORDINARIAS",
                     "ECUACIONES DIFERENCIALES PARCIALES", 
                     "ECUACIONES FUNCIONALES",
                     "ECUACIONES INTEGRALES",
                     "ECUACIONES INTEGRODIFERENCIALES",
                     "ECUACIONES LINEALES",
                     "INTERPOLACION",
                     "MATRICES",
                     "METODOS ITERATIVOS",
                     "PROXIMACION Y AJUSTE DE CURVAS",
                       "OTROS"]
      disciplineValue = analisisNumerico;
    }
    if(disciplineValue =="INVESTIGACION OPERATIVA"){
      var invetigacionOperativa = [  
      				"ANALISIS MICROECONOMICO", 
					"CIBERNETICA",
					"COLAS", 
					"DISTRIBUCION Y TRANSPORTE",
					"FIABILIDAD DE LOS SISTEMAS", 
					"FLUJO DE RED",
					"FORMULACION DE SISTEMAS",
					"INVENTARIO", 
					"MODELACION", 
					"ORDENAMIENTO",
					"OTROS",
					"PROGRAMACION DINAMICA",
					"PROGRAMACION ENTERA",
					"PROGRAMACION LINEAL",
					"PROGRAMACION NO LINEAL",
					"SISTEMAS DE CONTROL",
					"TEORIA DE JUEGOS", ]
      disciplineValue = invetigacionOperativa;
    }
        if(disciplineValue =="CALCULO DE PROBABILIDADES"){
      var calculoProbabilidades = [  
      				"APLICACION DE LA PROBABILIDAD",
					"CONJUNTOS ALEATORIOS",
					"FUNDAMENTOS DE LA PROBABILIDAD",
					"GEOMETRIA ESTOCASTICA", 
					"MATEMATICAS ACTUARIALES", 
					"PROCESOS DE MARKOV",
					"PLAUSIBILIDAD", 
					"PROCESOS ESTOCASTICOS",
					"PROBABILIDADES SUBJETIVAS",
					"PROBABILIDAD GEOMETRICA", 
					"OTROS",
					"TEORIA ANALITICA DE LA PROBABILIDAD",
					"TEOREMAS LIMITE"]
      disciplineValue = calculoProbabilidades;
    }
      if(disciplineValue =="ESTADISTICA"){
      var estadistica = [  
      				"ANALISIS DE DATOS",
					"ANALISIS MULTIVARIANTE", 
					"COMPUTACION PARA LA ESTADISTICA", 
					"DISEÑO Y ANALISIS DE EXPERIMENTOS",
					"ESTADISTICA ANALITICA",
					"FUNDAMENTOS DE INFERENCIA ESTADISTICA",
					"METODOS NO PARAMETRICOS",
					"OTROS",
					"PROCEDIMIENTOS DE DECISION Y TEORIA DE DECISION",
					"TEORIA DE LA DISTRIBUCION Y LA PROBABILIDAD",
					"TEORIA Y TECNICAS DE MUESTREO",
					"TEORIA ESTOCASTICA Y ANALISIS DE SERIES TEMPORALES",
					"TECNICAS DE ASOCIACION ESTADISTICA",
					"TECNICAS DE INFERENCIA ESTADISTICA",
					"TECNICAS DE PREDICCION ESTADISTICA",
					"SERIES TEMPORALES", ]
      disciplineValue = estadistica;
    }
        if(disciplineValue =="TOPOLOGIA"){
      var topologia = [  
      				"COHOMOLOGIA",
					"ESPACIOS ABSTRACTOS",
					"DINAMICA TOPOLOGICA",
					"GRUPOS DE TRANSFORMACION",
					"GRUPOS DE LIE", 
					"GRUPOS TOPOLOGICOS", 
					"HACES Y ESPACIOS DE FIBRAS",
					"HOMOLOGIA",
					"HOMOTOPIA", 
					"INMERSION TOPOLOGICA",
					"OTROS",
					"TEORIA K TOPOLOGICA", 
					"TOPOLOGIA ALGEBRAICA", 
					"TOPOLOGIA COMBINATORIA",
					"TOPOLOGIA DE CONJUNTOS DE PUNTOS", 
					"TOPOLOGIA GENERAL",
					"TOPOLOGIA TRIDIMENSIONAL",
					"VARIEDADES DIFERENCIALES", 
					"VARIEDADES TOPOLOGICAS"]
      disciplineValue = topologia;
    }
           if(disciplineValue =="INFORMATICA"){
      var informatica = [  
      				"DISEÑO Y COMPONENTES",
					"GRAFICAS INFORMATICAS", 
					"ESTRUCTURA Y MANEJO DE DATOS",
					"INTELIGENCIA ARTIFICIAL",
					"LENGUAJES ALGORITMICOS", 
					"LENGUAJES DE PROGRAMACION",
					"LOGICA MATEMATICA Y LENGUAJES FORMALES",
					"MATEMATICAS DISCRETAS", 
					"MANIPULACION SIMBOLICA Y ALGEBRAICA",
					"OTROS",
					"SISTEMAS DE INFORMACION",
					"PROCESAMIENTO DE TEXTOS Y DOCUMENTOS",
					"PROGRAMAS MATEMATICOS", 
					"SIMULACION Y MODELACION",
					"TEORIA",
					"TEORIA DE LA CODIFICACION Y DE LA INFORMACION",
					"TEORIA DE LA INFORMATICA",
					"TEORIA DE LA PROGRAMACION"]
      disciplineValue = informatica;
    }
          if(disciplineValue =="SISTEMAS"){
      var sistemas = [  
      				"OTROS",
					"SISTEMAS ALGEBRAICOS TOPOLOGICOS Y DIFERENCIABLES",
					"SISTEMAS DINAMICOS",
					"SISTEMAS HAMILTONIANOS",
					"SISTEMAS LAGRANGIANOS", 
					"SISTEMAS ESTOCASTICOS Y CONTROL"]
      disciplineValue = sistemas;
    }
        if(disciplineValue =="COSMOLOGIA Y COSMOGONIA"){
      var cosmologiyCosmogonia = [  
      				"ESTRELLAS BINARIAS", 
					"CONGLOMERADOS", 
					"RAYOS COSMICOS", 
					"GALAXIAS", 
					"GRAVITACION", 
					"NEBULOSAS", 
					"NOVAS", 
					"PULSARS", 
					"QUASARS", 
					"ESTRELLAS", 
					"EVOLUCION ESTELAR Y DIAGRAMAS HR",
					"COMPOSICION ESTELAR", 
					"SUPER NOVAS", 
					"ESTRELLAS",
					"VARIABLES",
					"FUENTES DE RAYOS X",
					"OTROS ESPECIFICAR",]
      disciplineValue = cosmologiyCosmogonia;
    }
        if(disciplineValue =="ESPACIOS Y MATERIA INTERPLANETARIOS"){
      var espaciosyMateriaInterplanetarios = [  
      				"CAMPOS INTERPLANETARIOS", 
					"MATERIAS INTERPLANETARIAS", 
					"OTROS",
					"PARTICULAS INTERPLANETARIAS"]
      disciplineValue = espaciosyMateriaInterplanetarios;
    }
        if(disciplineValue =="ASTRONOMIA OPTICA"){
      var astronomiaOptica = [  
      				"ASTRONOMIA DE POSICION",
					"TELESCOPIOS",
					"ESPECTROSCOPIA",
					"OTROS",]
      disciplineValue = astronomiaOptica;
    }
     if(disciplineValue =="PLANETOLOGIA"){
      var planetologia = [  
      				"COMETAS",
					"METEORITOS",
					"ATMOSFERAS PLANETARIAS",
					"GEOLOGIA PLANETARIA",
					"FISICA PLANETARIA",
					"CAMPOS MAGNETICOS PLANETARIOS",
					"PLANETAS",
					"SATELITES",
					"TECTITAS",
					"LA LUNA",
					"OTROS"]
      disciplineValue = planetologia;
    }
    if(disciplineValue =="RADIOASTRONOMIA"){
      var radioastronimia = [  
      				"ANTENAS",
					"RADIOTELESCOPIOS", 
					"OTROS"]
      disciplineValue = radioastronimia;
    }
     if(disciplineValue =="SISTEMA SOLAR"){
      var sistemaSolar = [  
      				"ENERGIA SOLAR",
					"FISICA SOLAR", 
					"RADIACION SOLAR",
					"EL SOL",
					"OTROS"]
      disciplineValue = sistemaSolar;
    }
    if(disciplineValue =="ACUSTICA"){
      var acustica = [  
      				"PROPIEDADES ACUSTICAS DE LOS SOLIDOS",
					"ACUSTICA ARQUITECTONICA",
					"FISICA DE LA AUDICION",
					"FISICA DE LA MUSICA",
					"RUIDO",
					"ONDAS DE CHOQUE",
					"SONAR",
					"FISICA DEL HABLA",
					"ULTRASONIDOS",
					"SONIDOS SUBMARINOS",
					"VIBRACIONES",
					"OTROS"]
      disciplineValue = acustica;
    }
     if(disciplineValue =="ELECTROMAGNETISMO"){
      var electromagnetismo = [  
      				"CONDUCTIVIDAD",
					"CANTIDADES ELECTRICAS Y SU MEDICION",
					"ELECTRICIDAD",
					"RADIACION ELECTROMAGNETICA",
					"RAYOS GAMMA",
					"RADIACION INFRARROJA",
					"VISIBLE Y ULTRAVIOLETA",
					 "INTERACCION DE LAS ONDAS ELECTROMAGNETICAS CON LA MATERIA",
					"MAGNETISMO",
					"PROPAGACION DE LAS ONDAS ELECTROMAGNETICAS",
					"ONDAS DE RADIO Y MICROONDAS",
					"SUPERCONDUCTIVIDAD",
					"RAYOS X",
					"OTROS"]
      disciplineValue = electromagnetismo;
    }
      if(disciplineValue =="ELECTRONICA"){
      var electronica = [  
      				"CIRCUITOS",
					"ELEMENTOS DE CIRCUITO",
					"TUBOS ELECTRONICOS",
					"MICROSCOPIA ELECTRONICA",
					"ESTADOS ELECTRONICOS",
					"TRANSPORTE DE ELECTRONES",
					"CIRCUITOS INTEGRADOS",
					"FOTOELECTRICIDAD",
					"PIEZOELECTRICIDAD",
					"OTROS"]
      disciplineValue = electronica;
    }
     if(disciplineValue =="FISICA DE LOS FLUIDOS"){
      var fisicadelosFluidos = [  
      				"COLOIDES",
					"DISPERSIONES",
					"CORRIENTE DE FLUIDOS",
					"MECANICA DE FLUIDOS",
					"GASES",
					"FENOMENOS DE ALTA PRESION",
					"IONIZACION",
					"LIQUIDOS",
					"MAGNETO-DINAMICA DE LOS FLUIDOS",
					"FISICA DEL PLASMA",
					"FLUIDOS CUANTICOS",
					"OTROS"]
      disciplineValue = fisicadelosFluidos;
    }
    if(disciplineValue =="MECANICA"){
      var mecanica = [  
      				"MECANICA ESTADISTICA",
					"TEORIA DE N CUERPOS",
					"ELASTICIDAD",
					"FRICCION",
					"MECANICA CONTINUA",
					"MECANICA DE FLUIDOS",
					"MECANICA DE SOLIDOS",
					"MEDIDA DE LAS PROPIEDADES MECANICAS",
					"OTROS",
					"PLASTICIDAD",
					"MECANICA ANALITICA",]
      disciplineValue = mecanica;
    }
      if(disciplineValue =="FISICA MOLECULAR"){
      var fisicaMolecular = [  
      				"RADICALES LIBRES",
					"FISICA DE LAS MOLECULAS INORGANICAS",
					"FISICA DE LAS MACROMOLECULAS",
					"MOLECULAS MESIONICAS Y MUONICAS",
					"HACES MOLECULARES",
					"IONES MOLECULARES",
					"ESPECTROSCOPIA MOLECULAR",
					"ESTRUCTURA MOLECULAR",
					"FISICA DE LAS MOLECULAS ORGANICAS",
					"FISICA DE POLIMEROS",
					"OTROS"]
      disciplineValue = fisicaMolecular;
    }

     if(disciplineValue =="FISICA NUCLEAR"){
      var fisicaNuclear = [  
      				"ATOMO DE HELIO",
					"ATOMO DE HIDROGENO",
					"ATOMOS CON Z>2",
					"CONVERSION DE LA ENERGIA",
					"DESINTEGRACION NUCLEAR",
					"ENERGIA NUCLEAR",
					"ESTRUCTURA DEL NUCLEO",
					"FISICA ATOMICA",
					"FISION NUCLEAR",
					"FUSION TERMONUCLEAR",
					"HACES ELECTRONICOS",
					"IONES ATOMICOS",
					"ISOTOPOS",
					"OTROS",
					"PROCESOS DE COLISION",
					"RADIOISOTOPOS",
					"REACTORES NUCLEARES",
					"RESONANCIA DE ROTACION DEL ELECTRON",
					"RESONANCIA MAGNETICA NUCLEAR",
					"RESONANCIA PARAMAGNETICA ELECTRONICA",
					"REACCIONES Y DISPERSION NUCLEARES",
					"HACES ATOMICOS"]
      disciplineValue = fisicaNuclear;
    }

    if(disciplineValue =="FISICA DE LAS PARTICULAS NUCLEARES"){
      var fisicadelasParticulasNucleares = [  
      				"ACELERADORES DE PARTICULAS",
					"DETECTORES DE RADIACION",
					"FISICA DE PARTICULAS",
					"FUENTES DE HACES",
					"FUENTES DE PARTICULAS",
					"OTROS",
					"CONFINAMIENTO DEL PLASMA",
					"NUCLEOS",
					"REACTORES DE FUSION",
					"MANEJO DE HACES"]
      disciplineValue = fisicadelasParticulasNucleares;
    }
      if(disciplineValue =="OPTICA"){
      var optica = [  
      				"CINEMATOGRAFIA",
					"COLORIMETRIA",
					"ESPECTROSCOPIA DE EMISION",
					"ESPECTROSCOPIA",
					"FISICA DE LA VISION",
					"FOTOGRAFIA",
					"HOLOGRAFIA",
					"ILUMINACION",
					"INSTRUMENTACION FOTOGRAFICA",
					"LASER",
					"LUZ",
					"MICROSCOPIOS",
					"OPTICA FISICA",
					"OPTICA GEOMETRICA",
					"OPTICA NO LINEAL",
					"OPTOMETRIA",
					"OTROS",
					"OPTICA DE FIBRAS FOTOCONDUCTORAS",
					"PROPIEDADES OPTICAS DE LOS SOLIDOS",
					"RADIACION VISIBLE",
					"RADIACION INFRARROJA",
					"RADIACION ULTRAVIOLETA",
					"RADIOMETRIA",
					"ESPECTROSCOPIA DE ABSORCION",
					"FOTOMETRIA"]
      disciplineValue = optica;
    }

    if(disciplineValue =="FISICOQUIMICA"){
      var fisicoquimica = [  
      				"CATALISIS",
					"CINETOQUIMICA",
					"ESPECTROSCOPIA ELECTRONICA",
					"ESTADOS DE LA MATERIA",
					"EXPLOSIVOS",
					"FENOMENOS DE MEMBRANA",
					"ELECTROLITOS",
					"ELECTROQUIMICA",
					"EMULSIONES",
					"EQUILIBRIOS DE FASE",
					"EQUILIBRIOS QUIMICOS",
					"ESPECTROSCOPIA MOLECULAR",
					"FENOMENOS DE DISPERSION",
					"FENOMENOS DE TRANSPORTE",
					"FISICA DE ESTADO LIQUIDO",
					"FISICA DE LA FASE GASEOSA",
					"FISICA DEL ESTADO SOLIDO",
					"FOTOQUIMICA",
					"INTERCAMBIO IONICO",
					"LLAMAS",
					"OTROS",
					"PROCESOS DE RELACION",
					"QUIMICA COLOIDAL",
					"QUIMICA DE ALTA TEMPERATURA",
					"QUIMICA DEL ESTADO SOLIDO",
					"QUIMICA INTERFACIAL",
					"RADIOQUIMICA",
					"REACCIONES RAPIDAS",
					"SALES FUNDIDAS",
					"SOLUCIONES",
					"TEORIA CUANTICA",
					"TEORIA DE LA VALENCIA",
					"TEORIA DE PILAS DE COMBUSTIBLE",
					"TERMODINAMICA",
					"TERMOQUIMICA",
					"TRANSFERENCIA DE ENERGIA"]
      disciplineValue = fisicoquimica;
    }
    if(disciplineValue =="FISICA DEL ESTADO SOLIDO"){
      var fisicaDelEstadoSolido = [  
      				"ALEACIONES",
					"COMPUESTOS",
					"CONDUCTORES METALICOS",
					"CRECIMIENTO CRISTALINO",
					"CRISTALOGRAFIA",
					"DENDRITAS",
					"DIELECTRICIDAD",
					"DIFUSION EN LOS SOLIDOS",
					"DISPOSITIVOS DE ESTADO SOLIDO",
					"ESTADOS ELECTRONICOS",
					"ESTADOS NO CRISTALINOS",
					"ESTRUCTURA CRISTALINA",
					"IMPERFECCIONES",
					"INTERACCION DE LA RADIACION CON LOS SOLIDOS",
					"INTERFACES",
					"LUMINOSIDAD",
					"MECANICA DE RETICULOS",
					"MECANOGRAFIA",
					"NANOCIENCIAS Y NANOTECNOLOGIA",
					"OTROS",
					"PROPIEDADES DE PORTADORES DE LOS ELECTRONES",
					"PROPIEDADES DE TRANSPORTE ELECTRONICO",
					"PROPIEDADES MAGNETICAS",
					"PROPIEDADES MECANICAS",
					"PROPIEDADES OPTICAS",
					"PROPIEDADES TERMODINAMICAS DE LOS SOLIDOS",
					"RESONANCIA MAGNETICA",
					"SEMICONDUCTORES",
					"SUPERCONDUCTORES",
					"SUPERFICIES",
					"TECNOLOGIA METALURGICA",
					"TRIBOLOGIA"]
      disciplineValue = fisicaDelEstadoSolido;
    }
    if(disciplineValue =="FISICA TEORICA"){
      var fisicaTeorica = [  
      				"CAMPOS GRAVITATORIOS", 
					"CAMPOS ELECTROMAGNETICOS",
					"CAMPOS",
					"FISICA DE LA ENERGIA",
					"FOTONES",
					"GRAVITACION",
					"GRAVITONES",
					"HADRONES",
					"LEPTONES",
					"MASA",
					"OTROS",
					"PARTICULAS ELEMENTALES",
					"RADIACION ELECTROMAGNETICA",
					"TEORIA DE LA RELATIVIDAD",
					"TEORIA DE LOS CAMPOS CUANTICOS"]
      disciplineValue = fisicaTeorica;
    }
    if(disciplineValue =="TERMODINAMICA"){
      var termodinamica = [  
      				"ALTA PRESION",
					"ALTA TEMPERATURA",
					"BAJAS TEMPERATURAS",
					"CAMBIOS DE ESTADO",
					"EQUILIBRIOS TERMODINAMICOS",
					"FENOMENOS DE TRANSPORTE",
					"FISICA DE LA TRANSMISION DE CALOR",
					"OTROS",
					"RELACIONES TERMODINAMICAS",
					"TECNICAS DE MEDIDAS TERMICAS",
					"TEORIA CINETICA",
					"TRANSICION DE FASE",]
      disciplineValue = termodinamica;
    }
    if(disciplineValue =="UNIDADES Y CONSTANTES FISICAS"){
      var unidadesyConstantesFisicas = [  
      				"CONSTANTES (FISICAS)",
					"CONVERSION DE UNIDADES",
					"CALIBRACION DE UNIDADES",
					"METROLOGIA",
					"OTROS",
					"UNIDADES ESTANDAR",]
      disciplineValue = unidadesyConstantesFisicas;
    }
      if(disciplineValue =="QUIMICA ANALITICA"){
      var quimicaAnalitica = [  
      				"ANALISIS ELECTROQUIMICO",
					"ANALISIS BIOQUIMICO",
					"ANALISIS CROMATOGRAFICO",
					"ANALISIS DE LOS POLIMEROS",
					"ANALISIS MICROQUIMICO",
					"ANALISIS RADIOQUIMICO",
					"ESPECTROSCOPIA DE MASAS",
					"ESPECTROSCOPIA DE RAMAN",
					"ESPECTROSCOPIA INFRARROJA",
					"ESPECTROSCOPIA POR MICROONDAS",
					"ESPECTROSCOPIA DE EMISION",
					"ESPECTROSCOPIA POR RAYOS X",
					"ESPECTROSCOPIA POR RESONANCIA MAGNETICA",
					"FLUORIMETRIA",
					"FOSFORIMETRIA",
					"GRAVIMETRIA",
					"METODOS DE ANALISIS TERMICO",
					"MICROSCOPIA",
					"OTROS",
					"VOLUMETRIA",
					"ESPECTROSCOPIA DE ABSORCION"]
      disciplineValue = quimicaAnalitica;
    }
     if(disciplineValue =="BIOQUIMICA"){
      var bioquimica = [  
      				"ACEITES ESENCIALES",
					"ACIDOS GRASOS",
					"ACIDOS NUCLEICOS",
					"ALMIDON",
					"AMINOACIDOS",
					"ANTIMETABOLITOS",
					"BIOLOGIA MOLECULAR",
					"BIOQUIMICA FISICA",
					"BIOSINTESIS",
					"CERAS",
					"COENZIMAS",
					"ELEMENTOS TRAZA",
					"ENZIMOLOGIA",
					"ESTEROIDES",
					"FARMACOLOGIA MOLECULAR",
					"FERMENTACION",
					"FOTOSINTESIS",
					"GENETICA BIOQUIMICA",
					"GLUCIDOS",
					"HIDROCARBUROS TERPENICOS",
					"HORMONAS",
					"INMUNOQUIMICA",
					"METABOLISMO INTERMEDIO",
					"QUIMICA CLINICA",
					"REGULACION DE LA REALIMENTACION",
					"LIPIDOS",
					"OTROS",
					"PEPTIDOS",
					"PROCESOS METABOLICOS",
					"PROTEINAS",
					"QUIMICA MICROBIOLOGICA",
					"QUIMIOTERAPIA",
					"ALCALOIDES",
					"VITAMINAS"]
      disciplineValue = bioquimica;
    }

    if(disciplineValue =="QUIMICA INORGANICA"){
      var quimicaInorganica = [  
      				"ALQUILOS METALICOS",
					"CARBONO",
					"COMPUESTOS DEFICIENTES EN ELECTRONES",
					"COMPUESTOS DE AZUFRE",
					"COMPUESTOS DE BORO",
					"COMPUESTOS DE CLORO",
					"COMPUESTOS DE COORDINACION",
					"COMPUESTOS DE FLUOR",
					"COMPUESTOS DE FOSFORO",
					"COMPUESTOS DE NITROGENO",
					"COMPUESTOS DE SODIO",
					"COMPUESTOS ORGANOMETALICOS",
					"ELEMENTOS ALCALINOS",
					"ELEMENTOS DE TRANSICION",
					"ELEMENTOS ELECTROPOSITIVOS",
					"ELEMENTOS TRANSURANICOS",
					"ELEMENTOS SINTETICOS",
					"ESTRUCTURA DE LOS COMPUESTOS INORGANICOS",
					"GERMANIO",
					"GRAFITO",
					"HALOGENOS",
					"HIDROGENO",
					"HIDRUROS",
					"MECANISMOS DE REACCIONES INORGANICAS",
					"METALES",
					"OTROS",
					"QUIMICA DE LOS PIGMENTOS",
					"QUIMICA DEL AGUA",
					"TIERRAS ALCALINAS",
					"TIERRAS RARAS",
					"COMPUESTOS DE PLOMO",
					"QUIMICA DE LOS ACTINIDOS"]
      disciplineValue = quimicaInorganica;
    }
    if(disciplineValue =="QUIMICA DE LAS MACROMOLECULAS"){
      var quimicaDeLasMacromoleculas = [  
      				"ANALISIS DE LOS POLIMEROS",
					"FIBRAS SINTETICAS",
					"POLIESTIRENOS",
					"POLIETILENO",
					"POLIMEROS INORGANICOS",
					"QUIMICA DE LOS MONOMEROS",
					"CELULOSA",
					"ELASTOMEROS",
					"ESTABILIDAD DE LAS MACROMOLECULAS",
					"FIBRAS NATURALES",
					"GOMAS",
					"MACROMOLECULAS",
					"MODIFICACION DE LAS MACROMOLECULAS",
					"OTROS",
					"POLIELECTROLITOS",
					"POLIESTERES",
					"POLIMEROS COMPUESTOS",
					"POLIMEROS DISPERSOS",
					"POLIMEROS ELEVADOS",
					"POLIMEROS RETICULADOS",
					"POLIPEPTIDOS Y PROTEINAS",
					"POLISACARIDOS",
					"POLIURETANOS",
					"PLASTICOS CELULARES",
					"SINTESIS DE LAS MACROMOLECULAS"]
      disciplineValue = quimicaDeLasMacromoleculas;
    }
     if(disciplineValue =="QUIMICA NUCLEAR"){
      var quimicaNuclear = [  
      				"MOLECULAS MARCADAS",
					"OTROS",
					"RADIOISOTOPOS",
					"RADIOQUIMICA",
					"SEPARACION DE ISOTOPOS",
					"TRAZADORES DE ISOTOPOS",
					"QUIMICA DE LOS ATOMOS RADIACTIVOS",
					"QUIMICA DE LAS RADIACIONES"]
      disciplineValue = quimicaNuclear;
    }
     if(disciplineValue =="QUIMICA ORGANICA"){
      var quimicaOrganica = [  
      				"PRODUCTOS ORGANOMETALICOS",
					"QUIMICA DE LAS MATERIAS TINTOREAS",
					"QUIMICA DE LOS ESTEROIDES",
					"QUIMICA DEL CARBANION",
					"QUIMICA DEL ORGANOAZUFRE",
					"COMPUESTOS HETEROCICLICOS",
					"DERIVADOS DEL BENCENO",
					"ESTEROQUIMICA Y ANALISIS DE CONFIGURACION",
					"ESTRUCTURA DE LAS MOLECULAS ORGANICAS",
					"HIDROCARBUROS AROMATICOS",
					"HIDROCARBUROS ALIFATICOS",
					"MECANICA DE LAS REACCIONES",
					"OTROS",
					"QUIMICA BICICLICA",
					"QUIMICA DE LOS HIDRATOS DE CARBONO",
					"QUIMICA DE LOS ORGANOFOSFOROS",
					"QUIMICA DE LOS ORGANOSILICONES",
					"QUIMICA DEL CARBONIO",
					"RADICALES LIBRES"]
      disciplineValue = quimicaOrganica;
    }
    if(disciplineValue =="FARMACOBIOLOGIA"){
      var farmacobiologia = [  
      				"QUIMICA BIOMOLECURAR",
					"QUIMICA MEDICINAL"]
      disciplineValue = farmacobiologia;
    }
       if(disciplineValue =="BIOLOGIA ANIMAL Y ZOOLOGIA"){
      var biologiaAnimalyZoologia = [  
      				"ANATOMIA ANIMAL",
					"CRECIMIENTO DE LOS ANIMALES",
					"FISIOLOGIA ANIMAL",
					"CITOLOGIA ANIMAL",
					"COMPORTAMIENTO ANIMAL",
					"COMUNICACION ANIMAL",
					"DESARROLLO ANIMAL",
					"ECOLOGIA ANIMAL",
					"EMBRIOLOGIA ANIMAL",
					"GENETICA ANIMAL",
					"HERPETOLOGIA",
					"HISTOLOGIA ANIMAL",
					"INVERTEBRADOS",
					"MAMIFEROS",
					"ORNITOLOGIA",
					"OTROS",
					"PARASITOLOGIA ANIMAL",
					"PATOLOGIA ANIMAL",
					"PRIMATOLOGIA",
					"PROTOZOOLOGIA",
					"TAXONOMIA ANIMAL",
					"VERTEBRADOS",
					"ZOOLOGIA GENERAL",
					"ZOOLOGIA MARINA"]
      disciplineValue = biologiaAnimalyZoologia;
    }
       if(disciplineValue =="ANTROPOLOGIA FISICA"){
      var antroplogiaFisica = [  
      				"ANTROPOLOGIA MEDICA",
					"ANTROPOMETRIA Y ANTROPOLOGIA FORENSE",
					"ARCHIVOS ANTROPOLOGICOS",
					"BIOLOGIA DE LA POBLACION",
					"BIOLOGIA RACIAL",
					"COMPORTAMIENTO DE LOS PRIMATES",
					"CONSTITUCION CORPORAL",
					"CRECIMIENTO SOMATICO",
					"COMPOSICION CORPORAL",
					"HABITOS DE NUTRICION",
					"SOMATOLOGIA DE LOS PRIMATES",
					"ENVEJECIMIENTO SOMATICO",
					"ETNOLOGIA",
					"GENETICA ANTROPOLOGICA",
					"OSTEOLOGIA",
					"OTROS"]
      disciplineValue = antroplogiaFisica;
    }
     if(disciplineValue =="BIOMATEMATICA"){
      var biomatematica = [  
      				"BIOESTADISTICA",
      				"OTROS"]
      disciplineValue = biomatematica;
    }
    if(disciplineValue =="BIOMETRIA"){
      var biometrica = [  
      				"BIOACUSTICA"
					,"BIOELECTRICIDAD"
					,"BIOENERGETICA"
					,"BIOMECANICA"
					,"BIOOPTICA"
					,"FISICA MEDICA"
					,"OTROS"]
      disciplineValue = biometrica;
    }
    if(disciplineValue =="BIOLOGIA CELULAR"){
      var biologiaCelular = [  
      				"CULTIVO CELULAR"
					,"GENETICA CELULAR"
					,"MORFOLOGIA CELULAR"
					,"CITOLOGIA"
					,"CULTIVO DE TEJIDOS"
					,"OTROS"]
	disciplineValue = biologiaCelular;
    }
    if(disciplineValue =="ETOLOGIA"){
      var etopologia = [  
      				"ANIMAL",
					"DE LOS INSECTOS",
					"HUMANA",
					"OTROS",]
	disciplineValue = etopologia;
    }
      if(disciplineValue =="GENETICA"){
      var genetica = [  
      				"EMBRIOLOGIA",
					"GENETICA DE POBLACIONES",
					"INGENIERIA GENETICA",
					"OTROS"]
	disciplineValue = genetica;
    }
      if(disciplineValue =="BIOLOGIA HUMANA"){
      var biologiaHumana = [  
      				"EMBRIOLOGIA HUMANA",
					"FISIOLOGIA HUMANA",
					"ANATOMIA HUMANA",
					"ANATOMIA SISTEMATICA",
					"ANATOMIA TOPOGRAFICA",
					"CITOLOGIA HUMANA",
					"DESARROLLO HUMANO",
					"ECOLOGIA HUMANA,",
					"GENETICA HUMANA",
					"GRUPOS SANGUINEOS",
					"HISTOLOGIA HUMANA",
					"NEUROANATOMIA HUMANA,",
					"ORGANOS SENSORIALES",
					"OTROS"]
	disciplineValue = biologiaHumana;
    }
      if(disciplineValue =="FISIOLOGIA HUMANA"){
      var fisiologiaHumana = [  
      				"FISIOLOGIA DE LAS ACTITUDES",
					"ANESTESIOLOGIA",
					"FISIOLOGIA CARDIOVASCULAR,",
					"FISIOLOGIA DEL SISTEMA ENDOCRINO",
					"FISIOLOGIA DEL EJERCICIO",
					"FISIOLOGIA GASTROINTESTINAL,",
					"METABOLISMOS HUMANOS",
					"REGULACION DE LA TEMPERATURA HUMANA",
					"FISIOLOGIA MUSCULAR",
					"NEUROFISIOLOGIA",
					"FISIOLOGIA DEL SISTEMA NERVIOSO CENTRAL",
					"FISIOLOGIA DE LA AUDICION",
					"FISIOLOGIA DEL HABLA",
					"FISIOLOGIA DE LA VISION",
					"FISIOLOGIA DE LA REPRODUCCION",
					"FISIOLOGIA DE LA RESPIRACION",
					"FISIOLOGIA DE LA LOCOMOCION",
					"OTROS"]
	disciplineValue = fisiologiaHumana;
    }
          if(disciplineValue =="ENTOMOLOGIA GENERAL"){
      var entomologiaGeneral = [  
      				"ENTOMOLOGIA GENERAL",
					"DESARROLLO DE LOS INSECTOS",
					"ECOLOGIA DE LOS INSECTOS",
					"MORFOLOGIA DE LOS INSECTOS",
					"FISIOLOGIA DE LOS INSECTOS",
					"TAXONOMIA DE LOS INSECTOS",
					"OTROS"]
	disciplineValue = entomologiaGeneral;
    }
         if(disciplineValue =="MICROBIOLOGIA"){
      var microbiologia = [  
      				"ANTIBIOTICOS",
					"FISIOLOGIA BACTERIANA",
					"METABOLISMO BACTERIANO",
					"BACTERIOLOGIA",
					"BACTERIOFAGOS",
					"HONGOS",
					"METABOLISMO MICROBIANO",
					"PROCESOS MIROCROBIANOS",
					"MOHOS",
					"MICOLOGIA (LEVADURAS)",
					"OTROS"]
	disciplineValue = microbiologia;
    }
           if(disciplineValue =="PALEONTOLOGIA"){
      var paleontologia = [  
      				"PALEONTOLOGIA ANIMAL",
					"PALEONTOLOGIA DE LOS INVERTEBRADOS",
					"PALINOLOGIA",
					"PALEONTOLOGIA VEGETAL",
					"PALEONTOLOGIA DE LOS VERTEBRADOS",
					"OTROS"]
	disciplineValue = paleontologia;
    }
          if(disciplineValue =="BOTANICA"){
      var botanica = [  
      				"BRIOLOGIA",
					"DENDROLOGIA",
					"BOTANICA GENERAL",
					"LIMNOLOGIA",
					"BIOLOGIA MARINA",
					"MICOLOGIA (HONGOS)",
					"FICOLOGIA",
					"FOTOBIOLOGIA",
					"FITOPATOLOGIA",
					"PALEOBOTANICA",
					"ANATOMIA VEGETAL",
					"CITOLOGIA VEGETAL",
					"ECOLOGIA VEGETAL",
					"GENETICA VEGETAL",
					"CRECIMIENTO DE LAS PLANTAS",
					"HISTOLOGIA VEGETAL",
					"NUTRICION DE LAS PLANTAS",
					"PARASITOLOGIA VEGETAL",
					"FISIOLOGIA VEGETAL",
					"TAXONOMIA VEGETAL",
					"TERIDOLOGIA",
					"OTROS",]
	disciplineValue = botanica;
    }
           if(disciplineValue =="VIROLOGIA"){
      var virologia = [  
      				"ARBOVIRUS",
					"BACTERIOFAGOS",
					"VIRUS DERMATROPICOS",
					"VIRUS ENTERICOS",
					"VIRUS NEUROTROPICOS",
					"VIRUS PANTROPICOS",
					"POXVIRUS",
					"VIRUS DEL SISTEMA RESPIRATORIO",
					"VIRUS VISCEROTROPICOS",
					"OTROS"]
	disciplineValue = virologia;
    }
      if(disciplineValue =="MEDIO AMBIENTE"){
      var medioAmbiente = [  
      			"GESTIÓN AMBIENTAL"]
	disciplineValue = medioAmbiente;
    }
     if(disciplineValue =="CIENCIAS ATMOSFERICAS"){
      var cienciasAtmosfericas = [  
      			"AERONOMIA",
				"RESPLANDOR CELESTE",
				"INTERACCION AIRE-MAR",
				"ACUSTICA DE LA ATMOSFERA",
				"QUIMICA DE LA ATMOSFERA",
				"DINAMICA DE LA ATMOSFERA",
				"ELECTRICIDAD ATMOSFERICA",
				"OPTICA DE LA ATMOSFERA",
				"RADIACTIVIDAD ATMOSFERICA",
				"ESTRUCTURA DE LA ATMOSFERA",
				"TERMODINAMICA DE LA ATMOSFERA",
				"TURBULENCIA ATMOSFERICA",
				"AURORA",
				"FISICA DE LAS NUBES",
				"RAYOS COSMICOS",
				"DIFUSION ATMOSFERICA",
				"PULSACIONES GEOMAGNETICAS",
				"IONOSFERA",
				"PARTICULAS MAGNETOSFERICAS",
				"ONDAS MAGNETOSFERICAS",
				"MODELIZACION NUMERICA",
				"FISICA DE LAS PRECIPITACIONES",
				"TRANSFERENCIA RADIACTIVA",
				"RADIACION SOLAR",
				"OTROS"]
	disciplineValue = cienciasAtmosfericas;
    }
    
    if(disciplineValue =="CLIMATOLOGIA"){
      var climatologia = [ "BIOCLIMATOLOGIA",
      "CLIMATOLOGIA ANALITICA",
      "CLIMATOLOGIA APLICADA",
      "CLIMATOLOGIA FISICA",
      "CLIMATOLOGIA REGIONAL",
      "MICROCLIMATOLOGIA",
      "OTROS",
      "PALEOCLIMATOLOGIA"]
	disciplineValue = climatologia;
    }

     if(disciplineValue =="GEOQUIMICA"){
      var geoquimica = ["COSMOQUIMICA",
      "PETROLOGIA EXPERIMENTAL",
      "GEOQUIMICA DE EXPLORACION",
      "GEOCRONOLOGIA Y RADIOISOTOPOS",
      "GEOQUIMICA DE ALTA TEMPERATURA",
      "EOQUIMICA DE BAJA TEMPERATURA",
      "GEOQUIMICA ORGANICA",
      "ISOTOPOS ESTABLES",
      "DISTRIBUCION DE ELEMENTOS TRAZA",
      "OTROS"]
	disciplineValue = geoquimica;
    }
 
     if(disciplineValue =="GEODESIA"){
      var geodesia = ["ASTRONOMIA GEODESICA",
      "CARTOGRAFIA GEODESICA",
      "NAVEGACION GEODESICA",
      "FOTOGRAMETRIA GEODESICA",
      "EXPLORACION"]
	disciplineValue = geodesia;
    }
     if(disciplineValue =="GEOGRAFIA"){
      var geografia = [  
				"BIOGEOGRAFIA",
				"CARTOGRAFIA GEOGRAFICA",
				"GEOGRAFIA DE LOS RECURSOS NATURALES",
				"GEOGRAFIA FISICA",
				"GEOGRAFIA MEDICA",
				"GEOGRAFIA TOPOGRAFICA",
				"TEORIA DE LA SITUACION",
				"USO DE LAS TIERRAS",
				"OTROS"]
	disciplineValue = geografia;
    }
      if(disciplineValue =="GEOLOGIA"){
      var geologia = [  
				"ANALISIS DE DIAGRAMAS DE POZO",
				"ECONOMIA DE LOS HIDROCARBUROS",
				"ESTRATIGRAFIA",
				"EXPLORACION GEOLOGICA",
				"FOTOGEOLOGIA",
				"GEOHIDROLOGIA",
				"GEOLOGIA DE LAS DIVERSAS AREAS DE LA SUPERFICIE TERRESTRE",
				"GEOLOGIA DEL CARBON",
				"GEOLOGIA DEL MEDIO AMBIENTE",
				"GEOLOGIA DEL PETROLEO",
				"GEOLOGIA ESTRUCTURAL",
				"GEOLOGIA GLACIAL",
				"GEOMORFOLOGIA",
				"INGENIERIA GEOLOGICA",
				"MECANICA DE LAS ROCAS",
				"MINERALOGIA",
				"PETROLOGIA IGNEA Y METAMORFICA",
				"PETROLOGIA SEDIMENTARIA",
				"PROCESOS Y ENERGIA GEOTERMICOS",
				"SEDIMENTOLOGIA",
				"TELEDETECCION (GEOLOGIA)",
				"VULCANOLOGIA",
				"YACIMIENTOS MINERALES",
				"OTROS"]
	disciplineValue = geologia;
    }
     if(disciplineValue =="GEOFISICA"){
      var geofisica = [  
				"EXPLORACION GEOFISICA",
				"FLUJO DE CALOR (TERRESTRE)",
				"GEOFISICA DE LA TIERRA SOLIDA",
				"GEOMAGNETISMO Y EXPLORACION MAGNETICA",
				"GRAVEDAD TERRESTRE Y EXPLORACION DE LA GRAVEDAD",
				"PALEOMAGNETISMO",
				"SISMOLOGIA Y EXPLORACION SISMICA",
				"TECTONICA",
				"OTROS"]
	disciplineValue = geofisica;
    }
     if(disciplineValue =="HIDROLOGIA"){
      var hidrologia = [  
				"AGUAS SUBTERRANEAS",
				"AGUAS SUPERFICIALES",
				"CALIDAD DEL AGUA",
				"EROSION DEL AGUA",
				"EVAPORACION",
				"GLACIOLOGIA",
				"HIDROBIOLOGIA",
				"HIDROGRAFIA",
				"HIELO",
				"HUMEDAD DEL SUELO",
				"LIMNOLOGIA",
				"NIEVE",
				"PRECIPITACIONES",
				"SUELOS HELADOS",
				"TRANSPIRACION",
				"OTROS"]
	disciplineValue = hidrologia;
    }
       if(disciplineValue =="METEOROLOGIA"){
      var metereologia = [  
				"ANALISIS METEOROLOGICO",
				"CONTAMINACION DEL AIRE",
				"CONTROL DEL TIEMPO (METEOROLOGIA)",
				"HIDROMETEOROLOGIA",
				"INSTRUCCIONES DE OBSERVACION (METEOROLOGIA)",
				"MESOMETEOROLOGIA",
				"METEOROLOGIA AGRICOLA",
				"METEOROLOGIA INDUSTRIAL",
				"METEOROLOGIA MARINA",
				"METEOROLOGIA MEDIANTE COHETES",
				"METEOROLOGIA MEDIANTE SATELITES",
				"METEOROLOGIA POLAR",
				"METEOROLOGIA POR RADAR",
				"METEOROLOGIA SINOPTICA",
				"METEOROLOGIA TROPICAL",
				"MICROMETEOROLOGIA",
				"PREDICCION METEOROLOGICA NUMERICA",
				"PREVISION METEOROLOGICA OPERACIONAL",
				"PREVISION METEOROLOGICA PROLONGADA",
				"RADIOMETEOROLOGIA",
				"OTROS"]
	disciplineValue = metereologia;
    }
     if(disciplineValue =="OCEANOGRAFIA"){
      var oceonografia = [  
			"BOTANICA MARINA",
			"HIELO MARINO",
			"INTERACCIONES MAR-AIRE",
			"OCEANOGRAFIA BIOLOGICA",
			"OCEANOGRAFIA DESCRIPTIVA",
			"OCEANOGRAFIA FISICA",
			"OCEANOGRAFIA QUIMICA",
			"PROCESOS DE LAS COSTAS Y DE LAS AREAS PROXIMAS A LAS COSTAS",
			"PROCESOS DEL FONDO DEL MAR",
			"SONIDOS SUBMARINOS",
			"ZOOLOGIA MARINA",
			"OTROS"]
	disciplineValue = oceonografia;
    }
      if(disciplineValue =="CIENCIAS DEL SUELO"){
      var cienciasDelSuelo = [  
			"BIOLOGICA DE SUELOS",
			"BIOQUIMICA DEL SUELO",
			"CARTOGRAFIA DE SUELOS",
			"CLASIFICACION DE SUELOS",
			"CONSERVACION DEL SUELO",
			"FISICA DEL SUELO",
			"INGENIERIA EDAFOLOGICA",
			"MECANICA DEL SUELO (AGRICULTURA)",
			"MICROBIOLOGIA DE LOS SUELOS",
			"MINERALOGIA DE LOS SUELOS",
			"MORFOLOGIA Y GENESIS DE LOS SUELOS",
			"QUIMICA DEL SUELO",
			"OTROS"]
	disciplineValue = cienciasDelSuelo;
    }
     if(disciplineValue =="CIENCIAS DEL COSMOS"){
      var cienciasDelCosmos = [  
			"BIOLOGIA ESPACIAL",
			"FISIOLOGIA ESPACIAL",
			"MEDICINA AEROSPACIAL",
			"OTROS"]
	disciplineValue = cienciasDelCosmos;
    }
      if(disciplineValue =="SALUD PÚBLICA"){
      var saludPublica = [  
			"ADMINISTRACIÓN DE LOS SERVICIOS DE SALUD",
				"ANTROPOLOGÍA MÉDICA",
				"EPIDEMIOLOGÍA",
				"OTROS"]
	disciplineValue = saludPublica;
    }
     if(disciplineValue =="INVESTIGACIÓN EN SALUD"){
      var investigacionEnSalud = [  
			"BIOMEDICINA",
			"INVESTIGACION CLÍNICA",
			"INVESTIGACIÓN EN ADICCIONES",
			"SISTEMAS DE SALUD",
			"OTROS"]
	disciplineValue = investigacionEnSalud;
    }
       if(disciplineValue =="ENFERMERÍA"){
      var enfermeria = [  
			"SALUD MATERNA"]
	disciplineValue = enfermeria;
    }
       if(disciplineValue =="QUIMICA AGRONOMICA"){
      var quimicaAgronomica = [  
			"BIOQUIMICA AGRONOMICA",
			"FUNGICIDAS",
			"HERBICIDAS",
			"INSECTICIDAS",
			"PLAGUICIDAS",
			"PRODUCTOS DE CULTIVOS NO COMESTIBLES",
			"PRODUCTOS DE PESCADO",
			"PRODUCTOS LACTEOS",
			"REGULADORES DEL CRECIMIENTO DE LAS PLANTAS",
			"TECNICAS DE PRODUCCION DE FERTILIZANTES",
			"USO DE FERTILIZANTES",
			"OTROS"]
	disciplineValue = quimicaAgronomica;
    }
     if(disciplineValue =="INGENIERIA RURAL"){
      var ingenieriaRural = [  
			"CONSTRUCCION RURAL",
			"DRENAJE",
			"EQUIPO DE GRANJA",
			"MECANICA AGRICOLA",
			"RIEGO",
			"OTROS"]
	disciplineValue = ingenieriaRural;
    }
       if(disciplineValue =="AGRONOMIA "){
      var agronomia = [  
			"AGRICULTURA EN ZONAS ARIDAS",
			"AGRICULTURA EN ZONAS TEMPLADAS",
			"AGRICULTURA EN ZONAS TROPICALES",
			"CESPED",
			"COMPORTAMIENTO DEL SUELO CON UTILIZACIONES ALTERNADAS",
			"CONTROL DE MALEZAS",
			"CULTIVOS DE CAMPO",
			"CULTIVOS FORRAJEROS",
			"CULTIVOS ORNAMENTALES",
			"DIVULGACION Y EXTENSION AGRICOLA",
			"FERTILIDAD DEL SUELO",
			"FITOGENETICA",
			"GESTION DE CULTIVOS",
			"GESTION DE LA PRODUCCION VEGETAL",
			"HIBRIDACION DE CULTIVOS",
			"PASTIZALES",
			"PROTECCION DE CULTIVOS",
			"SEMILLAS",
			"TECNOLOGIA DE CULTIVOS",
			"OTROS"]
	disciplineValue = agronomia;
    }
        if(disciplineValue =="CIENCIAS VETERINARIAS"){
      var cienciasVeterinarias = [  
			"APICULTURA",
			"ATENCION Y GESTION",
			"AVES DE CORRAL",
			"BOVINOS",
			"CONTROL Y NORMAS",
			"CUNICULTURA",
			"EQUINOS",
			"GENETICA",
			"INSTRUMENTACION",
			"NUTRICION",
			"OVINOS",
			"PORCINOS",
			"PRODUCTOS",
			"REPRODUCCION",
			"SELECCION",
			"SERICULTURA",
			"ZOOTECNIA GENERAL",
			"OTROS"]
	disciplineValue = cienciasVeterinarias;
    }
        if(disciplineValue =="PECES Y ANIMALES SALVAJES"){
      var pecesYAnimalesSalvajes = [  
			"BIOLOGIA PESQUERA",
			"CAZA (ANIMALES)",
			"CONSERVACION Y ORDENAMIENTO DE LOS ANIMALES SALVAJES",
			"CONTROLES",
			"DINAMICA POBLACIONES",
			"ELABORACION DEL PESCADO",
			"HABITOS DE ALIMENTACION",
			"INFLUENCIAS DEL HABITAT",
			"LOCALIZACION DE PECES",
			"MECANICA DE LA PESCA",
			"PISCICULTURA",
			"PROPAGACION Y ORDENAMIENTO",
			"PROTECCION DE PECES",
			"OTROS"]
	disciplineValue = pecesYAnimalesSalvajes;
    }
      if(disciplineValue =="HORTICULTURA"){
      var horticultura = [  
			"FITOGENETICA",
			"FLORICULTURA",
			"FRUTAS",
			"HIBRIDACION",
			"HORTALIZAS",
			"TECNICAS DE CULTIVO",
			"OTROS"]
	disciplineValue = horticultura;
    }
      if(disciplineValue =="FITOPATOLOGIA"){
      var fitopatologia = [  
			"BACTERIAS",
			"CONTROL AMBIENTAL DE ENFERMEDADES",
			"CONTROL BIOLOGICO DE ENFERMEDADES",
			"CONTROL QUIMICO DE ENFERMEDADES",
			"FISIOGENESIS",
			"HONGOS",
			"NEMATODOS",
			"SENSIBILIDAD Y RESISTENCIA DE LAS PLANTAS",
			"VIRUS",
			"OTROS"]
	disciplineValue = fitopatologia;
    }
         if(disciplineValue =="CIENCIAS VETERINARIAS"){
      var cienciasVeterinarias = [  
			"ANATOMIA",
			"ANESTESIOLOGIA",
			"BIOQUIMICA",
			"CIRUGIA",
			"FARMACOLOGIA",
			"FISIOLOGIA",
			"GENETICA",
			"HEMATOLOGIA",
			"INMUNOLOGIA",
			"MEDICINA INTERNA",
			"MICROBIOLOGIA",
			"MORFOLOGIA",
			"NUTRICION",
			"OBSTETRICIA",
			"PATOLOGIA",
			"RADIOLOGIA",
			"VIROLOGIA",
			"OTROS"]
	disciplineValue = cienciasVeterinarias;
    }
        if(disciplineValue =="MEDICINA CLINICA"){
      var medicinaClinica = [  
			"CANCEROLOGIA",
			"DERMATOLOGIA",
			"GENETICA CLINICA",
			"GERIATRIA",
			"GINECOLOGIA",
			"MICROBIOLOGIA CLINICA",
			"OFTALMOLOGIA",
			"PATOLOGIA CLINICA",
			"PEDIATRIA",
			"PSICOLOGIA CLINICA",
			"RADIOLOGIA",
			"RADIOTERAPIA",
			"SIFILOGRAFIA",
			"OTROS"]
	disciplineValue = medicinaClinica;
    }
      if(disciplineValue =="MEDICINA DEL TRABAJO"){
      var medicinaDelTrabajo = [  
			"ENFERMEDADES PROFESIONALES",
			"MEDICINA NUCLEAR",
			"REHABILITACION MEDICA",
			"SANIDAD DEL TRABAJO",
			"OTROS"]
	disciplineValue = medicinaDelTrabajo;
    }
      if(disciplineValue =="MEDICINA INTERNA"){
      var medicinaInterna = [  
			"CARDIOLOGIA",
			"ENDOCRINOLOGIA",
			"ENFERMEDADES INFECCIOSAS",
			"ENFERMEDADES PULMONARES",
			"GASTROENTEROLOGIA",
			"HEMATOLOGIA",
			"NEFROLOGIA",
			"NEUROLOGIA",
			"REUMATOLOGIA",
			"OTROS"]
	disciplineValue = medicinaInterna;
    }
      if(disciplineValue =="NUTRICION"){
      var nutricion = [  
			"DEFICIENCIAS ALIMENTARIAS",
			"DIGESTION",
			"ELEMENTOS MINERALES DE LOS ALIMENTOS",
			"ELEMENTOS TRAZA EN LOS ALIMENTOS",
			"ENFERMEDADES NUTRICIONALES",
			"INTOXICANTES NATURALES",
			"METABOLISMO DE LA ENERGIA",
			"NECESIDADES ALIMENTARIAS",
			"NUTRIENTES",
			"PATOGENOS DE LOS ALIMENTOS",
			"TOXICIDAD DE LOS ALIMENTOS",
			"VALORES NUTRIENTES",
			"VITAMINAS",
			"OTROS"]
	disciplineValue = nutricion;
    }
      if(disciplineValue =="PATOLOGIA"){
      var patologia = [  
			"ALERGIAS",
			"ARTERIOSCLEROSIS",
			"CARCINOGENESIS",
			"ENDOTOXINAS",
			"HEMATOLOGIA",
			"HISTOPATOLOGIA",
			"INMUNOPATOLOGIA",
			"NEUROPATOLOGIA",
			"ONCOLOGIA",
			"OSTEOPATOLOGIA",
			"PARASITOLOGIA",
			"PATOLOGIA CARDIOVASCULAR",
			"PATOLOGIA COMPARADA",
			"PATOLOGIA DE LAS RADIACIONES",
			"PATOLOGIA EXPERIMENTAL",
			"STRESS",
			"TERATOLOGIA",
			"TROMBOSIS",
			"OTROS"]
	disciplineValue = patologia;
    }
      if(disciplineValue =="FARMACODINAMICA"){
      var farmacodinamica = [  
			"ABSORCION DE LOS MEDICAMENTOS",
			"ACTIVACION",
			"AUTOCATALISIS",
			"CATALISIS",
			"EFECTO DE LOS MEDICAMENTOS",
			"INMUNOCATALISIS",
			"INTERACCION DE ANTIGENOS",
			"LUGARES RADIACTIVOS",
			"MECANISMOS DE ACCION DE LOS MEDICAMENTOS",
			"PROCESOS METABOLICOS DE LOS MEDICAMENTOS",
			"PROCESOS MULTIPLES",
			"RECEPTORES",
			"TERAPIA CON MEDICAMENTOS",
			"OTROS"]
	disciplineValue = farmacodinamica;
    }
        if(disciplineValue =="FARMACOLOGIA"){
      var farmacologia = [  
			"ANALISIS DE LOS PRODUCTOS FARMACEUTICOS",
			"COMPOSICION DE LOS MEDICAMENTOS",
			"EVALUACION DE LOS MEDICAMENTOS",
			"FARMACIA GALENICA",
			"FARMACOGNOSIA",
			"FARMACOPEAS",
			"FITOFARMACOS",
			"MEDICAMENTOS DE ORIGEN NATURAL",
			"MEDICAMENTOS SINTETICOS",
			"NORMALIZACION DE LOS MEDICAMENTOS",
			"PSICOFARMACOLOGIA",
			"RADIOFARMACOS",
			"OTROS"]
	disciplineValue = farmacologia;
    }
       if(disciplineValue =="MEDICINA QUIRURGICA"){
      var medicinaQuirurgica = [  
			"ANESTESIOLOGIA",
			"CIRUGIA ABDOMINAL",
			"CIRUGIA CARDIACA",
			"CIRUGIA DE TRANSPLANTES",
			"CIRUGIA ESTETICA",
			"CIRUGIA EXPERIMENTAL",
			"CIRUGIA MAXILO-FACIAL",
			"CIRUGIA OCULAR",
			"CIRUGIA ORTOPEDICA",
			"CIRUGIA OSEA",
			"CIRUGIA OTORRINOLARINGOLOGICA",
			"CIRUGIA VASCULAR",
			"ENDODONCIA",
			"ESTOMATOLOGIA-ORTODONCIA",
			"EXODONCIA",
			"FISIOTERAPIA",
			"NEUROCIRUGIA",
			"PARADONCIA",
			"PROCTOLOGIA",
			"PROSTODONCIA",
			"TRAUMATOLOGIA",
			"UROLOGIA",
			"OTROS"]
	disciplineValue = medicinaQuirurgica;
    }
      if(disciplineValue =="TECNOLOGIA E INGENIERIA AERONAUTICA"){
      var tecnologiaeIngenieriaAeronautica = [  
			"A LA ROTATORIA",
			"AERODINAMICA",
			"AERONAVES",
			"AEROPUERTOS Y TRANSPORTE AEREO",
			"CARGAS AERODINAMICAS",
			"CARGAS DE ATERRIZAJE",
			"COMBUSTIBLE PARA AERONAVES COMBUSTION",
			"COMPRESORES Y TURBINAS",
			"DISPOSITIVOS DE SUSPENSION NEUMATICA",
			"ESTABILIDAD Y CONTROL",
			"ESTRUCTURAS DE AERONAVES",
			"HIDRODINAMICA",
			"INSTRUMENTACION (AVIACION)",
			"MATERIALES PARA SISTEMAS DE PROPULSION",
			"SISTEMAS DE PROPULSION",
			"TEMBLOR Y VIBRACION",
			"TEORIA AERODINAMICA",
			"VUELOS: ENSAYO E INVESTIGACION",
			"OTROS"]
	disciplineValue = tecnologiaeIngenieriaAeronautica;
    }
        if(disciplineValue =="TECNOLOGIA BIOQUIMICA"){
      var tecnologiaBioquimica = [  
			"BIOTECNOLOGIA MARINA",
			"MICROBIOLOGIA INDUSTRIAL",
			"TECNOLOGIA DE LA FERMENTACION",
			"TECNOLOGIA DE LOS ANTIBIOTICOS",
			"OTROS"]
	disciplineValue = tecnologiaBioquimica;
    }
        if(disciplineValue =="TECNOLOGIA E INGENIERIA QUIMICA"){
      var tecnologiaeIngenieriaQuimica = [  
			"DESIONIZACION",
			"ECONOMIA QUIMICA",
			"GALVANOPLASTIA",
			"OPERACIONES ELECTROQUIMICAS",
			"PROCESOS NUCLEOQUIMICOS",
			"PROCESOS QUIMICOS",
			"PROYECTOS",
			"QUIMICA INDUSTRIAL",
			"RECUBRIMIENTOS IMPERMEABLES",
			"RECUBRIMIENTOS PROTECTORES",
			"RECUBRIMIENTOS REFRACTARIOS",
			"SEPARACION QUIMICA",
			"SINTESIS QUIMICA",
			"TECNOLOGIA DE LA CATALISIS",
			"TECNOLOGIA DE LA COMBUSTION",
			"TECNOLOGIA DE LA CORROSION",
			"TECNOLOGIA DE LA PRESERVACION",
			"OTROS"]
	disciplineValue = tecnologiaeIngenieriaQuimica;
    }
      if(disciplineValue =="TECNOLOGIA DE LA INFORMATICA"){
      var tecnologiaDeLaInformatica = [  
			"ARITMETICA E INSTRUCCIONES PARA LA UTILIZACION DE MAQUINAS",
			"ARQUITECTURA DE COMPUTADORES",
			"COMPUTADORES ANALOGICOS",
			"COMPUTADORES DIGITALES",
			"COMPUTADORES HIBRIDOS",
			"CONVERTIDORES DE SISTEMA ANALOGICO A SISTEMA NUMERICO",
			"DISEÑO DE SISTEMAS DE CALCULO NUMERICO",
			"DISEÑO LOGICO",
			"DISPOSITIVOS DE ALMACENAMIENTO",
			"DISPOSITIVOS DE CONTROL",
			"DISPOSITIVOS DE TRANSMISION DE DATOS",
			"EQUIPO PERIFERICO DE COMPUTADORES",
			"FIABILIDAD DE LOS COMPUTADORES",
			"SISTEMAS DE RECONOCIMIENTO DE CARACTERES",
			"SISTEMAS DE TIEMPO REAL",
			"TERMINALES DE COMPUTADOR TERMINALES DE VIDEO Y TRAZADORES DE CURVAS",
			"UNIDADES CENTRALES DE TRATAMIENTO",
			"UTILIZABILIDAD DE LOS COMPUTADORES",
			"OTROS"]
	disciplineValue = tecnologiaDeLaInformatica;
    }
    var newSubdiscipline ="<span class='plain-select'><select id='BooksChapters_subdiscipline' class='tooltipstered' name='BooksChapters[subdiscipline]'>";
    newSubdiscipline+="<option>Seleccionar Subdisciplina</option>";
    for (var item in disciplineValue) {
        newSubdiscipline +="<option>"+disciplineValue[ item ]+"</option>";
    }

    newSubdiscipline+="</select></span>";

    $("#comboSubdiscipline").html(newSubdiscipline);
}
</script>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
  'id'=>'books-chapters-form',
  // Please note: When you enable ajax validation, make sure the corresponding
  // controller action is handling ajax validation correctly.
  // There is a call to performAjaxValidation() commented in generated controller code.
  // See class documentation of CActiveForm for details on this.
  'enableAjaxValidation'=>true,
  'enableClientValidation'=>true,
  'htmlOptions' => array('enctype' => 'multipart/form-data'),
)); ?>



    <div class="row">
        <?php echo $form->textField($model,'isbn', array('placeholder'=>'ISBN','title'=>'ISBN')); ?>
        <?php echo $form->error($model,'isbn'); ?>
    </div>

  <div class="row">

    <?php echo $form->textField($model,'chapter_title',array('size'=>60,'maxlength'=>100, 'placeholder'=>'Capítulo de libro','title'=>'Capítulo de libro')); ?>
    <?php echo $form->error($model,'chapter_title'); ?>
  </div>

  <div class="row">

    <?php echo $form->textField($model,'book_title',array('size'=>60,'maxlength'=>100, 'placeholder'=>'Titulo de libro','title'=>'Titulo de libro')); ?>
    <?php echo $form->error($model,'book_title'); ?>
  </div>

  <div class="row">
    <span class="plain-select">
    <?php echo $form->dropDownList($model,'publishing_year',array(
              '1930'=>'1930','1931'=>'1931','1932'=>'1932','1933'=>'1933',
          '1934'=>'1934','1935'=>'1935','1936'=>'1936','1937'=>'1937',
          '1938'=>'1938','1939'=>'1939','1940'=>'1940','1941'=>'1941',
          '1942'=>'1942','1943'=>'1943','1944'=>'1944','1945'=>'1945',
          '1946'=>'1946','1947'=>'1947','1948'=>'1948','1949'=>'1949',
          '1950'=>'1950','1951'=>'1951','1952'=>'1952','1953'=>'1953',
          '1954'=>'1954','1955'=>'1956','1956'=>'1956','1957'=>'1957',
          '1958'=>'1958','1959'=>'1959','1960'=>'1960','1961'=>'1961',
          '1962'=>'1962','1963'=>'1963','1964'=>'1964','1965'=>'1965',
          '1962'=>'1962','1963'=>'1963','1964'=>'1964','1965'=>'1965',
          '1966'=>'1966','1967'=>'1967','1968'=>'1968','1969'=>'1969',
          '1970'=>'1970','1971'=>'1971','1972'=>'1972','1973'=>'1973',
          '1974'=>'1974','1975'=>'1975','1976'=>'1976','1977'=>'1977',
          '1978'=>'1978','1979'=>'1979','1980'=>'1980','1981'=>'1981',
          '1982'=>'1982','1983'=>'1983','1984'=>'1984','1985'=>'1985',
          '1986'=>'1986','1987'=>'1987','1988'=>'1988','1989'=>'1989',
          '1990'=>'1990','1991'=>'1992','1993'=>'1993','1994'=>'1994',
          '1995'=>'1995','1996'=>'1996','1997'=>'1997','1998'=>'1998',
          '1999'=>'1999','2000'=>'2000','2001'=>'2001','2002'=>'2002',
          '2003'=>'2003','2004'=>'2004','2005'=>'2005','2006'=>'2006',
          '2007'=>'2007','2008'=>'2008','2009'=>'2009','2010'=>'2010',
          '2011'=>'2011','2012'=>'2012','2013'=>'2013','2014'=>'2014',

          '2015'=>'2015'),array('title'=>'Año de publicación','prompt'=>'Seleccionar año de publicación'));?>
</span>
    <?php echo $form->error($model,'publishing_year'); ?>
  </div>

  <div class="row">
    <?php echo $form->textField($model,'publishers',array('size'=>60,'maxlength'=>255, 'placeholder'=>'Editores','title'=>'Editores')); ?>
    <?php echo $form->error($model,'publishers'); ?>
  </div>

  <div class="row">
    <?php echo $form->textField($model,'editorial',array('size'=>45,'maxlength'=>45, 'placeholder'=>'Editorial','title'=>'Editorial')); ?>
    <?php echo $form->error($model,'editorial'); ?>
  </div>

  <div class="row">

    <?php echo $form->textField($model,'volume',array('size'=>45,'maxlength'=>45, 'placeholder'=>'No. Volumen','title'=>'No. Volumen')); ?>
    <?php echo $form->error($model,'volume'); ?>
  </div>

  <div class="row">

    <?php echo $form->textField($model,'pages',array('placeholder'=>'No. páginas','title'=>'No. paginas')); ?>
    <?php echo $form->error($model,'pages'); ?>
  </div>

  <div class="row">

    <?php echo $form->textField($model,'citations',array('placeholder'=>'No. citas','title'=>'No. citas')); ?>
    <?php echo $form->error($model,'citations'); ?>
  </div>

  <div class="row">
    <span class="plain-select">
    <?php echo $form->dropDownList($model,'area',array('ANTROPOLOGIA'=>'ANTROPOLOGIA',
                              'ARTES Y LETRAS'=>'ARTES Y LETRAS',
                              'ASTRONOMIA Y ASTROFISICA'=>'ASTRONOMIA Y ASTROFISICA',
                              'CIENCIAS AGRONOMICAS Y VETERINARIAS'=>'CIENCIAS AGRONOMICAS Y VETERINARIAS',
                              'CIENCIAS DE LA OCUPACION'=>'CIENCIAS DE LA OCUPACION',
                              'CIENCIAS DE LA TECNOLOGIA'=>'CIENCIAS DE LA TECNOLOGIA',
                              'CIENCIAS DE LA TIERRA Y DEL COSMOS'=>'CIENCIAS DE LA TIERRA Y DEL COSMOS',
                              'CIENCIAS DE LA SALUD'=>'CIENCIAS DE LA SALUD',
                              'CIENCIAS DE LA VIDA'=>'CIENCIAS DE LA VIDA',
                              'CIENCIAS ECONOMICAS'=>'CIENCIAS ECONOMICAS',
                              'CIENCIAS JURIDICAS Y DERECHO'=>'CIENCIAS JURIDICAS Y DERECHO',
                              'CIENCIAS POLITICAS'=>'CIENCIAS POLITICAS',
                              'DEMOGRAFIA'=>'DEMOGRAFIA',
                              'ETICA'=>'ETICA',
                              'FILOSOFIA'=>'FILOSOFIA',
                              'FISICA'=>'FISICA',
                              'GEOGRAFIA'=>'GEOGRAFIA',
                              'HISTORIA'=>'HISTORIA',
                              'LINGÜISTICA'=>'LINGÜISTICA',
                              'LOGICA'=>'LOGICA',
                              'MATEMATICAS'=>'MATEMATICAS',
                              'MEDICINA Y PATOLOGIA HUMANA'=>'MEDICINA Y PATOLOGIA HUMANA',
                              'PEDAGOGIA'=>'PEDAGOGIA',
                              'PSICOLOGIA'=>'PSICOLOGIA',
                              'PROSPECTIVA'=>'PROSPECTIVA',
                              'QUIMICA'=>'QUIMICA', 'SOCIOLOGIA'=>'SOCIOLOGIA'),array('prompt'=>'Seleccionar área','title'=>'Area', 'id'=>'area', 'onchange'=>'changeArea()'));?>
                                                      </span>
    <?php echo $form->error($model,'area'); ?>
  </div>
  <div class="row"id="comboDiscipline">

  </div>
  <div class="row"id="comboSubdiscipline">

  </div>
  

   <div class="row">

        <?php echo $form->textField($model,'keywords',array('size'=>60,'maxlength'=>250, 'placeholder'=>'Palabras claves','title'=>'Palabras Claves')); ?>
        <?php echo $form->error($model,'keywords'); ?>
    </div>

  <div class="row">

    <?php echo $form->fileField($model,'url_doc',array('size'=>60,'maxlength'=>100,'title'=>'Documento')); ?>
    <?php echo $form->error($model,'url_doc'); ?>
  </div>


  <?php
      $this->widget('ext.widgets.reCopy.ReCopyWidget', array(
      'targetClass'=>'authorsRegistry',
      'addButtonLabel'=>'Agregar nuevo autor',
     ));
      ?>
      <div class="authorsRegistry">


      <?php
          echo"<input type='hidden' name='idsBooksChapters[]'>";
       ?>
    <div class="row">
      <?php echo $form->textField($modelAuthor,'names',array('name'=>'names[]','size'=>30,'maxlength'=>30, 'placeholder'=>'Nombre(s)','title'=>'Nombres(s)')); ?>
      <?php echo $form->error($modelAuthor,'names');?>
    </div>

    <div class="row">
      <?php echo $form->textField($modelAuthor,'last_name1',array('name'=>'last_names1[]','size'=>20,'maxlength'=>20, 'placeholder'=>'Apellido Paterno','title'=>'Apllido Paterno')); ?>
      <?php echo $form->error($modelAuthor,'last_name1'); ?>
    </div>

    <div class="row">

      <?php echo $form->textField($modelAuthor,'last_name2',array('name'=>'last_names2[]','size'=>20,'maxlength'=>20,'placeholder'=>'Apellido Materno','title'=>'Apellido Materno')); ?>
      <?php echo $form->error($modelAuthor,'last_name2'); ?>
    </div>

    <div class="row">

      <?php echo $form->textField($modelAuthor,'position',array('name'=>'positions[]','class' => 'numericOnly','placeholder'=>'Posición','title'=>'Posición')); ?>
      <?php echo $form->error($modelAuthor,'position'); ?>
      </div>
      </div>


      <?php
      if(!$model->isNewRecord)
      foreach ($modelAuthors as $key => $value) {
        ?>

      <?php
          echo"<input type='hidden' value='".$value->id."' name='idsBooksChapters[]'>";
         ?>
    <div class="row">
      <?php echo $form->textField($value,'names',array('name'=>'names[]','value'=>$value->names,'size'=>30,'maxlength'=>30, 'placeholder'=>'Nombre(s)','title'=>'Nombres(s)')); ?>
      <?php echo $form->error($value,'names');?>
    </div>

    <div class="row">
      <?php echo $form->textField($value,'last_name1',array('name'=>'last_names1[]','value'=>$value->last_name1,'size'=>20,'maxlength'=>20, 'placeholder'=>'Apellido Paterno','title'=>'Apellido Paterno')); ?>
      <?php echo $form->error($value,'last_name1'); ?>
    </div>

    <div class="row">

      <?php echo $form->textField($value,'last_name2',array('name'=>'last_names2[]','value'=>$value->last_name2,'size'=>20,'maxlength'=>20,'placeholder'=>'Apellido Materno','title'=>'Apellido Materno')); ?>
      <?php echo $form->error($value,'last_name2'); ?>
    </div>

     <div class="row">
      <?php echo $form->textField($value,'position',array('name'=>'positions[]','value'=>$value->position,'class' => 'numericOnly','placeholder'=>'Posición','title'=>'Posición')); ?>
      <?php echo $form->error($value,'position');
    ?>
  </div>
  <hr>
    <?php } ?>

  </div>

  <div class="row buttons">

    <?php echo CHtml::submitButton($model->isNewRecord ? 'Guardar' : 'Modificar',array('class'=>'savebutton')); ?>
    <?php echo CHtml::link('Cancelar',array('booksChapters/admin'),array('confirm'=>'Si cancela todo los datos escritos se borraran. ¿Está seguro de que desea cancelar?')); ?>


  </div>

<?php $this->endWidget(); ?>

</div><!-- form -->